### ISSUE TITLE
hotkey to quickly switch between curve and {rectangle, straight, arrow}

### ISSUE THREAD

**Issue by hungrysnake** [pubpub-zz/ppInk#10]
Is there a hot key combination to enable quick toggle between the curve and straight line?
it is more efficient than switching back and fore when drawing many lines and curve in the same screen. eg. writing and plotting lines in a graph.

For example.
In curve mode, hold the Ctrl to temporarily switch to rectangle mode
Hold SHIFT to switch straight line
Hold Ctrl-SHIFT to switch Arrow

Releasing the above keys to switch back to curve.

**Comment by pubpub-zz** [comment]
Ctrl and Shift are already used for activating the magnetic effects. The default shortcuts are defined only with one letter(eg A = arrow, L = Line , H=Hand, R=Rectangle). Can you evaluate this solution to toggle between tools?

**Comment by pubpub-zz** [comment]
Re-thinking about, I can propose the following approach :
when a  tool is selected (clicking or shortcut) with alt depressed, it will be active until alt is released. at that time, the tool previously selected is reselected. This induce that you should not use alt in the drawing shortcuts (both R and alt+R will activate rectangle tool) I've build a moke-up not with still some bugs. Can you tell me what you of this proposal:
[ppInk.zip](https://github.com/pubpub-zz/ppInk/files/5147470/ppInk.zip)

**Comment by hungrysnake** [comment]
trying to open the attached zip file but I'm not able to toggle with alt key. not sure if I missed a step to activate it. the option menu can't be opened in this build. right-click > select option, and no response.

the toggling between curve (free form)  and straight line, rectangle, arrow can be reference to the tool ZoomIt which I used long time ago. It is a good tool but lack of some key feature like anit-aliasing, switching to mouse mode while keeping the drawing on the screen. However, the key combination is very handy when I use it in teaching.

zoomit and hotkey
https://docs.microsoft.com/en-us/sysinternals/downloads/zoomit

hotkey cheatsheet
https://edutech4teachers.edublogs.org/files/2012/03/ZoomIt-Cheat-Sheet-1ptohg9.pdf
![image](https://user-images.githubusercontent.com/42885440/91684798-13990b80-eb8b-11ea-94d5-c2add31b7620.png)

**Comment by pubpub-zz** [comment]
In the demo version, the OneTimeCommand is always active (can not be disactivated yet). Engage Hand writing. Press and hold ALT, press and release R : Rectangle is engaged and active. once drawn, release Alt, Hand is reselected. As said, the ctrl and shift are reserved for magnetic, (observable when magnetic icon is off)

**Comment by hungrysnake** [comment]
Oh I get it. using alt to select the mode without releasing the alt key to stay in the mode.

I found that the problem for me is that using alt+<key> quite often I need to look at the keyboard to find the <key>. if the switch is very often, like straight, curve, straight, curve, arrow, curve. I was lost in the mental switching between keys.

the benefit of using just ctrl, alt and switch is that I don't need to look at the keyboard. Keeping my left hand on keyboard to switch mode, while my right hand controlling mouse for the entire period of drawing. Maybe it is just my habit.

**Comment by pubpub-zz** [comment]
What you can do also to ease finding keys is the use some grouped keys (eg on QWERTY keyboard : Q=Line  ; A = Rect ;W = Oval) and just keep the fingers on Alt and release only when you've done your specific action. Remember also that pressing tools shortcut will select the different filling options which is not possible with ctrl/shift but is ok with my Alt+ option.
I'm finishing the coding and now this option will also work with Erasor or Move

**Comment by hungrysnake** [comment]
Thanks. Moving those options closer to alt key helps. Just need to make sure that those combinations don't conflict with the application default hotkey.

**Comment by pubpub-zz** [comment]
Implemented in pp1.2RC1

**Comment by hungrysnake** [comment]
the new alt temporary switch actually works better than I think. I could even temporary switch color with it. absolutely love it. thank you so much

**Comment by pubpub-zz** [comment]
And if you have downloaded the 1.2RC1, it works also with erasor... :)
