### ISSUE TITLE
Add option to swap between Standard snapshot and snapshot with continue drawing

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#102]
Currently short button press on snapshot (or hotkey ) makes a standard snapshot and stops inking while long button press or alt+hotkey allows to carry on editing after snapshot. An option to allow those two behaviors should be nice

**Comment by pubpub-zz** [comment]
A beta verVersion for evaluation includes fixes for #107 #106 #102:
[ppInk64_01a.zip](https://github.com/pubpub-zz/ppInk/files/6577838/ppInk64_01a.zip)

**Comment by NOVAinc** [comment]
It works! I would only suggest fixing the documentation so all the templates use http as opposed to https. I spent a bit of time pulling my hair wondering what I was doing wrong since I had copied and pasted the addresses 😄

**Comment by chrisj0192** [comment]
Hello @ pubpub-zz I was testing the snapshot swap option and I can say that It's perfect! it works perfectly!
A short test video about it:
https://user-images.githubusercontent.com/20199672/120955621-66ee4a80-c717-11eb-9ce8-86db90779109.mp4

My favorite part of this implementation is that both "snap + exit" and "snap + continue" save screenshots. amazing!

Just an observation: is there an option to swap from one type of snapshot to another using a custom hotkey?

**Comment by pubpub-zz** [comment]
Hotkey does one and alt+hotkey does the other

**Comment by chrisj0192** [comment]
Oh I see, I was trying what you said, but it works if I enable Process alt as a temporary command.😥, isn't there other way? if possible)

**Comment by pubpub-zz** [comment]
Most of the time if you need one, you don't need the other. implementing both in independent hotkeys is too much time/complexity. If you want something more configurable, I would recommend to have a look at https://www.touch-portal.com/ or other alternatives. ppInk REST API is compatible with it and snapshot command accepts to continue or not as an independent parameter.

**Comment by chrisj0192** [comment]
Perfect! thanks friend!
