### ISSUE TITLE
missing shortcuts for load/save strokes

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#106]
https://github.com/pubpub-zz/ppInk/issues/75#issuecomment-851178597

> So, Could I request you something? Could you please implement a hotkey for that load button?, because I'm less dynamic using the toolbar than using hotkeys and have also gotten used to using ppInk with keyboard and mouse. Please, consider it!

I thought it was already implemented.... Will put that in the stack... 👍 

_Originally posted by @pubpub-zz in https://github.com/pubpub-zz/ppInk/issues/75#issuecomment-851266162_

**Comment by pubpub-zz** [comment]
@chrisj0192
A beta Version for evaluation includes fixes for #107 #106 #102:
[ppInk64_01a.zip](https://github.com/pubpub-zz/ppInk/files/6577838/ppInk64_01a.zip)

**Comment by chrisj0192** [comment]
Hello @pubpub-zz I was testing your beta version (ppInk64_01a.zip) in different cases and I can say that there are problems with shortcut combinations.

Hotkey load/save results:
hotkey option for both "load" hotkey and "save" hotkey don't work properly. There are problems differentiating "ctrl/shift/a key of letter or combinations"

This is the video of tests:
https://user-images.githubusercontent.com/20199672/120954032-e7ab4780-c713-11eb-9e25-a2f66a069815.mp4

**Comment by pubpub-zz** [comment]
Thanks for bug report
Try this version 
[ppInk64_MultiSel07a.zip](https://github.com/pubpub-zz/ppInk/files/6612286/ppInk64_MultiSel07a.zip)

**Comment by chrisj0192** [comment]
Hello @pubpub-zz , the problem still remains. I've already tested all the combinations as I told you and showed  in the video above.

**Comment by pubpub-zz** [comment]
found something odd in my code... 😒
may explain also the problem with the pen dialog appearing at startup....

Work for tomorrow 🥱😴

**Comment by pubpub-zz** [comment]
Found! slightly different to the issue where the pen dialog opening on clipart shortcut
[ppInk64_MultiSel9b.zip](https://github.com/pubpub-zz/ppInk/files/6627115/ppInk64_MultiSel9b.zip)

**Comment by chrisj0192** [comment]
Hello @pubpub-zz which one is the last beta version ? ppInk64_MultiSel9a or ppInk64_MultiSel9b ? I'm a little confused. I guess it's multisel9b?

**Comment by pubpub-zz** [comment]
Yes I'm using the day first and if 2 beta are issued the same day, I increment the letter 😊

**Comment by chrisj0192** [comment]
Hello @pubpub-zz I was testing the new beta version (ppInk64_MultiSel9b.zip) these last days and my results are the following:
- Issue about the color/pen dialog opening on clipArt shortcut: Fixed! So far I've not had this problem again.
- Issue about loading strokes: Fixed! it's working perfectly. Now the program differentiates custom shortcuts and also its short/long function to load strokes with the same shortcut key works perfectly!
- Issue about saving strokes: Fixed! it's also working perfectly. Now the program differentiates custom shortcuts and the multi-window appearance about overriding strokes has been fixed!

I think you can close this issue, nothing more to report.

I really appreciate your improvements.
