### ISSUE TITLE
Pen width adjustment not restarting at current value after changing Pen

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#107]
https://github.com/pubpub-zz/ppInk/issues/75#issuecomment-851178597

> > The first time I've coded that way and I wonder What is the best solution between the two options : like currently coded, you can recover the width before selecting the new pen. in another hand, It can be a little confiousing to not restart fro the current size. Can you open a new issue about this specific point opening the question to get other opinions.
 
> For me, it's really confusing because I use the arrow and with it I cannot see how wide my pen is or which my last width was before swaping to another pen color (because when I swap from a pen to another one, the pen width restarts from the preset value (that's great). I think if it restarts when using the mouse wheel or hotkeys starting the pen width from its preset value, it will be more intuitive. Even so, I'm willing to open an issue about this topic. It would be interesting to get other opinions.

I seen what you mean : will put in the stack 👍 

_Originally posted by @pubpub-zz in https://github.com/pubpub-zz/ppInk/issues/75#issuecomment-851266162_

**Comment by pubpub-zz** [comment]
@chrisj0192
A beta verVersion for evaluation includes fixes for #107 #106 #102:
[ppInk64_01a.zip](https://github.com/pubpub-zz/ppInk/files/6577838/ppInk64_01a.zip)

**Comment by chrisj0192** [comment]
Hello @pubpub-zz I'm testing your beta version in different cases, I'll post my observations about the multiple selector, pen width, load/save shortcuts and snapshot in a few hours.

**Comment by chrisj0192** [comment]
Hello @pubpub-zz I was testing your beta version (ppInk64_01a.zip) in different cases and I can say that everything is perfect!
I only have one observation that you might want to consider. here you are my results:

Pen width test results:
- Stroke test with shortcuts (Perfect)
- Stroke test with the mouse wheel (Perfect)
- Shape test with the mouse wheel (Perfect)
This is the video if you want to see it
https://user-images.githubusercontent.com/20199672/120950796-1f62c100-c70d-11eb-8448-5e7732e4e40f.mp4

- Shape test with shape shortcuts and (+/-) shorcuts (it's missing)
In my case, when pressing Alt + W (to draw rectangles) and release W key holding down alt and then pressing S to draw ellipses, in this case those combinations work perfectly, but it's missing with pen width +/-. 
Honestly I don't find it necessary for now. But You might want to consider implementing this requeriment, (If possible)
This is the video:
https://user-images.githubusercontent.com/20199672/120950901-546f1380-c70d-11eb-93c5-a79cb1d23f63.mp4

Tha's all about my tests.

Grateful for your work.

**Comment by chrisj0192** [comment]
This additional observation is not related to the pen width but I've also noticed that when pressing alt + a custom key for the "toggle fading" option and releasing that custom key (it works) but finally when realeasing alt, and you makes strokes, toggle fading option keeps working.

**Comment by pubpub-zz** [comment]
see #111 for alt as temporary for Fading

**Comment by chrisj0192** [comment]
Done! I think you can close this issue if you want. There's nothing more to report.

Thank you so much!
