### ISSUE TITLE
Crash when insert  clipart from clipboard or file

### ISSUE THREAD

**Issue by argostelios** [pubpub-zz/ppInk#108]
![crash](https://user-images.githubusercontent.com/13959459/121875852-d3adaa00-cd00-11eb-942c-1716f931e28c.png)

06 / 14 / 2021 10:58UIThreadException

version 1.6.1.23490 built on 30/05/2021 13:02
Oops, ppInk crashed! Please include the following information if you plan to contact the developers (a copy of the following information is stored in crash.txt in the application folder):

An item with the same key has already been added.

Stack Trace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at gInk.ImageLister.FromClipB_Click(Object sender, EventArgs e) in D:\gink.git\ppInk\src\ImageLister.cs:line 131
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by pubpub-zz** [comment]
Hi @argostelios,
It looks like you are reporting 2 errors.
The first one (dialog box image)seems to have occured during drawing, most probably after inserting an image, can you confirm my analysis and provide the image you had just inserted
the second one seems to have occured during insertion of the clipboard. Can you confirm and detail how you filled the clipboard.

Thanks

**Comment by argostelios** [comment]
I will try to show you all the steps  from cold start
1) First   i start the ppink  
2)second i make a screen snip  from my windows 10 
![image](https://user-images.githubusercontent.com/13959459/121953149-1e591180-cd55-11eb-9964-0b0ec8dcf851.png)
3) then i go to ppink and click the clipart ---->  click from clipboard 
![image](https://user-images.githubusercontent.com/13959459/121954115-49903080-cd56-11eb-8a2e-fc60d5a92b1b.png)
![image](https://user-images.githubusercontent.com/13959459/121954598-da670c00-cd56-11eb-9574-d4af7165a57e.png)
4)i repeat step 2 and 3 for a second screen snip 
![image](https://user-images.githubusercontent.com/13959459/121955253-a213fd80-cd57-11eb-86b3-5a4a7a74c9f0.png)

at this point everything is working fine,  now im going to show what im doing and the ppink bugs 

5) When i delete the two clipboard that ppink stores witch i don't need them any more
![image](https://user-images.githubusercontent.com/13959459/121955983-7e04ec00-cd58-11eb-97e7-d06cbb12ef88.png)
and i repeat step 2 and 3  for a third screen snip i am getting this error 
![image](https://user-images.githubusercontent.com/13959459/121956536-261ab500-cd59-11eb-9e82-cfe0cb7df693.png)

no  i am going to show you what i am doing and i can go around from this bug 

6) i press no when that error occurs on step 5 second picture and the ppink restores the clipboard 1 from step 2 and 3
![image](https://user-images.githubusercontent.com/13959459/121957344-2cf5f780-cd5a-11eb-8a9e-a0176fac2613.png)
then i press again from clipboard 
![image](https://user-images.githubusercontent.com/13959459/121957628-937b1580-cd5a-11eb-851b-84e0cf469d67.png)
and the ppink shows the error from step 5 second picture and i press no
the the ppink paste the second clipboard witch was made from step 4 
![image](https://user-images.githubusercontent.com/13959459/121958162-464b7380-cd5b-11eb-8238-5969b62669ef.png)

and from this point everythink is working, i press from clipboard and ppink inserts the third screen snip without error 
![image](https://user-images.githubusercontent.com/13959459/121958510-a93d0a80-cd5b-11eb-8748-fb7ec463e9ee.png)

summary 

ppink  as many clipboards you delete in ppink as many  no you have to press  on the error message  
looks  likes ppink wants to restore all deleted clipbords before let you insert another one.


i hope so i point out the problem 
Thank you

**Comment by pubpub-zz** [comment]
I understand the problem  (reuse of an internal name) this should fix it. Be aware this includes the beta changes in progress (as discussed in other threads)
[ppInk64_varFix14a.zip](https://github.com/pubpub-zz/ppInk/files/6651439/ppInk64_varFix14a.zip)

Can you also describe the first test case (this was very well described 👍 )

**Comment by argostelios** [comment]
it was the same error exactly what i described above  but i just post the crash report that ppink creates for developers i thought that would help.   im not developer no programmer i can't understand a think in that file

**Comment by argostelios** [comment]
Thank you very much   i didn't  realize you fix it  and you send me the app. 
that was quick 
it works perfect! Thank you
