### ISSUE TITLE
No all Toolbar Orientations work, my opinion for some changes on that 

### ISSUE THREAD

**Issue by argostelios** [pubpub-zz/ppInk#110]
Figure 1
![image](https://user-images.githubusercontent.com/13959459/122185389-f8328f00-ce84-11eb-8e72-cb69274efe09.png)

One of the orientation of the toolbar the default one it woks fine the other ones they don't work the way it collapse and expand, some of them they flip the tools on the toolbar

i want to say my opinion for the orientation of the toolbar and the options

i want to think three option orientation (horizontal , vertical ), collapse ( if horizontal left to right figure1(A) or right to left figure1(B) if vertical top to bottom figure1(E) or bottom to top)figure1(F) and last one flip of the tools on the toolbar like  figure1(A)  figure1(D)

and if i want to change one of them i don't want the other two to have any change by the program. 

at the moment you can't have option figure1(B) and option figure1(F)

and i want to think the orientation and collapse as major options and the flip of the tools on the toolbar as minor change separated of the other two in the options( i say that because when you flip the tools on the toolbar it feels like you have to learn the new locations of the tools) .

**Comment by pubpub-zz** [comment]
Hi @argostelios,
Toolbar construction is quite static and too much variability is too much time consuming and subject to regression such as the tool flipping you have noticed. There is currently 4 configuration which is already more than any others similar programs are proposing.

About the flipping, bug  can you make a video or provide a detail description of your testcase.
Thanks

**Comment by argostelios** [comment]
yes there are tons of features no worries . There is no bug about the flipping. its just what it is when i choose  deferent orientation it flips the tools.  
Thank you.

**Comment by pubpub-zz** [comment]
> yes there are tons of features no worries . There is no bug about the flipping. its just what it is when i choose deferent orientation it flips the tools.
> Thank you.

It is designed to have always the dock/undock away from border this why tools are flipped.



> 
> 
> https://drive.google.com/file/d/1fDUi9JDg0D0Mt2GqUpvIhb91dSommrD9/view?usp=sharing
> this is from other orientations what is happening

This is a bug. Normally fixed in this beta version can you confirm it is fixed for you and without side effects
[ppInk64_varFix26a.zip](https://github.com/pubpub-zz/ppInk/files/6720287/ppInk64_varFix26a.zip)

**Comment by argostelios** [comment]
Yes it works all toolbar orientations they working without any issues 
thank you very much
