### ISSUE TITLE
Line styles not restarting when alt + shortcut keys are used.

### ISSUE THREAD

**Issue by chrisj0192** [pubpub-zz/ppInk#111]
From Dashed Lines issue #98 
> I was trying to combine "line" with "dashed line" and was trying to find an easy way to do it dynamically by setting "alt + d" for the dashed lines. But the dashed line doesn't reset when I release "alt" key.

Agree with your idea, not sure how to code that yet. Will put that in the stack.

(...)

_Originally posted by @pubpub-zz in https://github.com/pubpub-zz/ppInk/issues/98#issuecomment-850978877_

**Comment by pubpub-zz** [comment]
@chrisj0192,
I've implemented the alt as temporary for dash and for fading. Give me your feedback
[ppInk64_apng_alt_dash_07a.zip](https://github.com/pubpub-zz/ppInk/files/6756735/ppInk64_apng_alt_dash_07a.zip)

**Comment by chrisj0192** [comment]
Hello @pubpub-zz I'm testing the beta release (ppInk64_apng_alt_dash_07a.zip) and it's too laggy when starting inking.

**Comment by pubpub-zz** [comment]
Can you try to reboot : it's fluid on my computer

**Comment by chrisj0192** [comment]
Hello @pubpub-zz it seems ppInk is laggy when I make strokes. I cannot test propertly 😔
https://user-images.githubusercontent.com/20199672/124342396-551e8c80-db89-11eb-800b-8c8577b6b1f9.mp4

**Comment by pubpub-zz** [comment]
Regenerated just in case...
[ppInk64_apng_alt_dash_03a.zip](https://github.com/pubpub-zz/ppInk/files/6758094/ppInk64_apng_alt_dash_03a.zip)

If still lagging, can you capture with the debug window opened.
It would be great also to have a some capture with the windows task manager detail tab displaying ppInk.

Note : you seem to be have more performance issues than anyone else based on your results and your analysis from #97. I've started to review before some code refactoring. But your current issue is too far away from my test. waiting for your results

**Comment by chrisj0192** [comment]
Hello @pubpub-zz I was testing ppInk64_apng_alt_dash_03a.zip and it's fluid on my laptop. no lag problem anymore.

About alt as a temporary funciont for:
- Line styles, It works perfect! No problem about it.
- Fading, it works perfect! No problem about it.

I have a question. Have you made any changes to the ppInk toolbar? I found this bug. In previous versions this problem didn't happen.
Escape key and Space key issue: The toolbar is not closed by pressing ESC, you can reopen it by pressing the SPACE key.
This is the video:
https://user-images.githubusercontent.com/20199672/124421354-e5460880-dd26-11eb-91f0-4257d540c547.mp4

About three months ago I found a snapshot save path issue (I forgot to report it). The first time I set my own path to save my own images, they are saved in the previous folder instead of the last folder according to the path I set. I need to close ppInk and then open it so that my configuration works.
This is the video:
https://user-images.githubusercontent.com/20199672/124422703-5edef600-dd29-11eb-94e7-a0ea0335a5cd.mp4

> Note : you seem to be have more performance issues than anyone else based on your results and your analysis from #97. I've started to review before some code refactoring. But your current issue is too far away from my test. waiting for your results.

I'm not sure about it. If it's a performance issue, I'll test ppInk on other laptops/computers much better than mine in order to get more reliable results about it.

Thanks.

**Comment by pubpub-zz** [comment]
> I have a question. Have you made any changes to the ppInk toolbar? I found this bug. In previous versions this problem didn't happen.
> Escape key and Space key issue: The toolbar is not closed by pressing ESC, you can reopen it by pressing the SPACE key, even if the space key is not set as a shortcut key for dock/undock.
> This is the video:
> https://user-images.githubusercontent.com/20199672/124421354-e5460880-dd26-11eb-91f0-4257d540c547.mp4

There has been no change. Looking at your video, I see the same behavior that I'm expecting : when you press esc you close the toolbar, the floating window reappears at it takes automatically the focus : when you press the space bar, you apply a click like which is restarting a new session. You can press as esc as often as you want, only the first one closes the toolbar : the others(applied on the floating window) are ignored and therefore the space after reopens the toolbar. It is independant of the hotkey you have setup (you can  make a test changing it to confirm my analysis)



> About three months ago I found a snapshot save path issue (I forgot to report it). The first time I set my own path to save my own images, they are saved in the previous folder instead of the last folder according to the path I set. I need to close ppInk and then open it so that my configuration works.
> This is the video:
> https://user-images.githubusercontent.com/20199672/124422703-5edef600-dd29-11eb-94e7-a0ea0335a5cd.mp4

Not seen 3 months ago, Under analysis.



> > Note : you seem to be have more performance issues than anyone else based on your results and your analysis from #97. I've started to review before some code refactoring. But your current issue is too far away from my test. waiting for your results.
> 
> I'm not sure about it. If it's a performance issue, I'll test ppInk on other laptops/computers much better than mine in order to get more reliable results about it.
> 

I did a test with more than 100 strokes without any issues. My computer being quite performant. Next time you are experiencing som hickups on Lasso or Handwritting (actually using the same stroke component) can you save the strokes and send them : it may help to do more representative testing.

thanks

**Comment by chrisj0192** [comment]
> There has been no change. Looking at your video, I see the same behavior that I'm expecting : when you press esc you close the toolbar, the floating window reappears at it takes automatically the focus : when you press the space bar, you apply a click like which is restarting a new session. You can press as esc as often as you want, only the first one closes the toolbar : the others(applied on the floating window) are ignored and therefore the space after reopens the toolbar. It is independant of the hotkey you have setup (you can make a test changing it to confirm my analysis)

In summary, I forgot to disable the floating window option🤦‍♂️I thought that Esc and Space keys were mixing with the floating window (assuming this was disabled). I apologize for that.

> I did a test with more than 100 strokes without any issues. My computer being quite performant. Next time you are experiencing som hickups on Lasso or Handwritting (actually using the same stroke component) can you save the strokes and send them : it may help to do more representative testing.

Regardless of your results or mine, I'm pretty curious to see how ppInk behaves or performs on other high-performance computers. I'll save the strokes and send you the stroke files, for better analysis when I do.

Thanks for your attention.

**Comment by chrisj0192** [comment]
> There has been no change. Looking at your video, I see the same behavior that I'm expecting : when you press esc you close the toolbar, the floating window reappears at it takes automatically the focus : when you press the space bar, you apply a click like which is restarting a new session. You can press as esc as often as you want, only the first one closes the toolbar : the others(applied on the floating window) are ignored and therefore the space after reopens the toolbar. It is independant of the hotkey you have setup (you can make a test changing it to confirm my analysis)

In summary, I forgot to disable the floating window option🤦‍♂️I thought that Esc and Space keys were mixing with the floating window (assuming this was disabled). I apologize for that.

> I did a test with more than 100 strokes without any issues. My computer being quite performant. Next time you are experiencing som hickups on Lasso or Handwritting (actually using the same stroke component) can you save the strokes and send them : it may help to do more representative testing.

Regardless of your results or mine, I'm quite curious to see how ppInk behaves or performs on other high-performance computers. I'll save the strokes and send you the stroke files, for better analysis when I do.

Thanks for your attention.
