### ISSUE TITLE
Bar doesn't appear on main display when using laptop screen as secondary display; mouse pointer disappears

### ISSUE THREAD

**Issue by MikeTheGreat** [pubpub-zz/ppInk#114]
ppInk is awesome!  Thank you for sharing! 

I use a laptop.
Laptop screen is my secondary display.

I use a separate monitor/screen.
I extend my desktop across both.
I tell Windows that separate monitor/screen is my primary display

ppInk button appears on my separate monitor/screen:
![image](https://user-images.githubusercontent.com/551619/124698873-9de28800-de9e-11eb-9ff2-ce6f0c0d7c79.png)

But ppInk bar appears on my laptop screen:
![image](https://user-images.githubusercontent.com/551619/124698936-b652a280-de9e-11eb-8c8f-af79ebaf8660.png)

**ALSO:**

My mouse pointer disappears so I can't choose anything on ppInk bar.

I can close ppInk bar by pressing Escape key (Esc).

**Comment by pubpub-zz** [comment]
Hi @MikeTheGreat 
ppInk can be started 3 ways
Hotkey
Click on ppInk icon in taskbar, on the right side
And finally with the floating icon.
The floating icon bar can be drag to the position and screen  you like with right click.

For the toolbar you can drag it with left click on any button. Don't move it too quickly to ensure it moves as you want. Again you can drag it through screens

Once both are set as desired, open options (right click on the icon in taskbar then select option dialog. Then save the options.

About the 'dissapearing' cursor I would guess it is the default pen size tip. You can use the arrow cursor ( select it in the options) or simply press and hold alt: the cursor will be replaced with the arrow until you release it. I personally prefer this second option.

**Comment by pubpub-zz** [comment]
Hi @MikeTheGreat,
can you confirm it is ok

**Comment by pubpub-zz** [comment]
@MikeTheGreat,
I assume it is good. Do not hesitate to add comments even if closed.
Do not hesitate to star the project (My Objective : reach 200 before end of July 😊)

**Comment by pubpub-zz** [comment]
about the difficulty to find the cursor, you have 2 solutions:
a) select the arrow cursor in the options
b) use the alt key with your cursor :  the cursor will temporarily change to the arrow which ease to find it.
