### ISSUE TITLE
Quick q

### ISSUE THREAD

**Issue by jumanjaydazed** [pubpub-zz/ppInk#115]
I love this program. But have a suggestion or maybe I've missed it somewhere...
I teach online and use obs. I crop window capture or use slides which are also cropped to fit half my obs screen.
Is there a way to change/choose the actual area of the screen , like a specific sized window instead of the whole screen? Whenever I try to highlight or even circle a word, it's always out of place. i've tred everthing. 
Keep up the good work  :)

**Comment by pubpub-zz** [comment]
Hi @jumanjaydazed,
ppInk has a Window mode where you can limit the working area 
https://user-images.githubusercontent.com/4083478/112311221-c656c580-8ca5-11eb-895b-2279366c0fc4.mp4
(extracted from https://github.com/pubpub-zz/ppInk, looking for Window Mode)
even in window mode you will be able to capture the window 
![image](https://user-images.githubusercontent.com/4083478/124801171-d9408d80-df56-11eb-83d1-4f6628f5b514.png)
(and make it transparent with a filter if required)
![image](https://user-images.githubusercontent.com/4083478/124801260-efe6e480-df56-11eb-88aa-b40af86555d3.png)

If you like it, do not hesitate to star it 😊

**Comment by jumanjaydazed** [comment]
Thanks, I seen this aboit an hour after I posted! I decided to use display capture. Love your product by the way...😊



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 8, 2021 01:11 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pubpub-zz/ppInk] Quick q (#115)




 
Hi @jumanjaydazed,
 ppInk has a Window mode where you can limit the working area
 https://user-images.githubusercontent.com/4083478/112311221-c656c580-8ca5-11eb-895b-2279366c0fc4.mp4
 (extracted from https://github.com/pubpub-zz/ppInk, looking for Window Mode)
 even in window mode you will be able to capture the window
 
 (and make it transparent with a filter if required)
 
 
If you like it, do not hesitate to star it 😊
