### ISSUE TITLE
Implementing the Edit tool within the Lasso Tool

### ISSUE THREAD

**Issue by YouFoundJK** [pubpub-zz/ppInk#118]
Since we already have a working Lasso Tool, I wanted to suggest that we extent the Lasso Tool for Editing the selected region as well (in terms of color, line style, etc.)

**Comment by pubpub-zz** [comment]
@xxBloodyMaryxx 
This beta should contains the new edit feature.

**Comment by xxBloodyMaryxx** [comment]
I am using ppInk64_varFixes09b.zip that you had provided in the other thread.

It works some times, it doesnt work some other times, I can't understand the reason. Here is the recording:

https://user-images.githubusercontent.com/72195985/125159818-7be74f00-e197-11eb-9f7a-39285ff51f47.mp4

Here is the crash txt for all the crashes during the recording:
[crash.txt](https://github.com/pubpub-zz/ppInk/files/6795062/crash.txt)

**Comment by pubpub-zz** [comment]
@YouFoundJK,
Can you check this version :
[ppInk64_edit10b.zip](https://github.com/pubpub-zz/ppInk/files/6795191/ppInk64_edit10b.zip)

**Comment by YouFoundJK** [comment]
Amazing this seems to be flawless in implementing the edit lasso combo. Ill let you know if I find something interesting.
