### ISSUE TITLE
UIThreadException When Selecting ClipArt Tool

### ISSUE THREAD

**Issue by jlogix** [pubpub-zz/ppInk#120]
ClipArt Tool dialog does not show when I select the tool. See details below:

07 / 13 / 2021 11:03UIThreadException

version 1.7.1.20789 built on 11/07/2021 11:32
Oops, ppInk crashed! Please include the following information if you plan to contact the developers (a copy of the following information is stored in crash.txt in the application folder):

Form that is already visible cannot be displayed as a modal dialog box. Set the form's visible property to false before calling showDialog.

Stack Trace:
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at gInk.FormCollection.btTool_Click(Object sender, EventArgs e) in D:\gink.git\ppInk\src\FormCollection.cs:line 5497
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.PerformClick()
   at gInk.FormButtonHitter.FormButtonHitter_Click(Object sender, EventArgs e) in D:\gink.git\ppInk\src\FormButtonHitter.cs:line 79
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at gInk.FormButtonHitter.WndProc(Message& msg) in D:\gink.git\ppInk\src\FormButtonHitter.cs:line 66
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by pubpub-zz** [comment]
I can not reproduce your problem. what is the sequence you've used? best can you make a video?

**Comment by jlogix** [comment]
I think at the heart of the problem is, on my PC (Windows 10) the ClipArt selection dialog does not show for some reason - I can see it on the taskbar but the dialog is invisible. But since the dialog is present in the background I can't proceed unless I press Esc to dismiss the dialog or Alt+Tab to switch to another application. If I press Alt+Tab to switch to another application and click ClipArt icon again I get this exception.

![image](https://user-images.githubusercontent.com/8962258/125554028-7c1a5164-e29c-4d1c-aded-27456a416f63.png)

**Comment by pubpub-zz** [comment]
Can you tell me how many screen you have, which resolution and scale they are.

**Comment by jlogix** [comment]
There are 3 screens. Each with 1920 x 1080 resolution and each at 100% scale

**Comment by pubpub-zz** [comment]
Can you run this version.
[ppInk64_varFix14a.zip](https://github.com/pubpub-zz/ppInk/files/6815646/ppInk64_varFix14a.zip)

After starting the program, go to Options dialog, click on debug Window and raise back to the very beginning of the log. you will find some debug lines

> Screen #\\.\DISPLAY1
> {X=0,Y=0,Width=1920,Height=1080} == {X=0,Y=0,Width=1920,Height=1080}
Can you tell me what you are getting

**Comment by jlogix** [comment]
```
Screen #\\.\DISPLAY1
{X=0,Y=0,Width=1920,Height=1080} == {X=0,Y=0,Width=1920,Height=1040}
Screen #\\.\DISPLAY4
{X=966,Y=-1080,Width=1920,Height=1080} == {X=966,Y=-1080,Width=1920,Height=1040}
Screen #\\.\DISPLAY2
{X=1920,Y=0,Width=1920,Height=1080} == {X=1920,Y=0,Width=1920,Height=1040}


```

I'm getting the exception even with the default config. See below:

```

----------
[Basic Settings]

# Language
Language_File = en-us

# Use a white icon in system tray instead of the default red one (looks better in windows 10 :)
White_Tray_Icon = False

Hide_In_AltTab = False

Fading_Time=.1

# The folder that snapshots are saved to
Snapshot_Path = %USERPROFILE%/Pictures/gInk/

# Engage directly Capture when opening toolbar (from hotkey/floating window/tray icon)
Open_Into_Snap = False

#Swap Snapshots Behavior ; if true Long= Std Snap and Short = Snap & Continuous ; Legacy = False ; note: opposite from options dlg
Swap_Snapshot_Behaviors=False

# set Pens buttons on twoLines
Pens_On_Two_Lines = True

# Show eraser icon
Eraser_Icon = True

# Show pan icon
Pan_Icon = True

# Show pointer icon
Pointer_Icon = True

# engage Pointer when alt+tab is depressed
AltTab_Pointer = True

# Show pen width icon
Pen_Width_Icon = True

# Set pen width to pen's default at selection, even if Pen Width Icon is available to modify it after.
Pen_Width_At_Selection = True

# Show view/hide inks icon
InkVisible_Icon = True

#Capture strokes only
Snapshot_StrokesOnly = False

# Show snapshot icon
Snapshot_Icon = True

# Show undo icon
Undo_Icon = True

# Show clear icon
Clear_Icon = True

# Show Tools icons
Drawing_Icon = True

# Show Load/Save icons
LoadSave_Icon = True

# Enabled Color Pickup function
ColorPickup_Enabled = True

# Zoom Icon : 0 : no Zoom icon ; 1 : Magnifier ; 2 : freeze  ; 3 : both
Zoom_Icon = 3

# Show tools subtools in a toolbar
SubToolsBar_Enabled = False


# Arrow ends definitions : aperture angle (Â°) and length(% screen)
Arrow= 15,1.85000002384186

FitToCurve = True

#increments for penwidth +/- shortcuts
PenWidth_Delta = 40
# defaults for options
PenWidth_Thin_Default = 30
PenWidth_Normal_Default = 80
PenWidth_Thick_Default = 500

Default_Arrow = START

# 1.04 % should be about 20 pix ; will also change size of circles in tags and selection Size
Text = Comic Sans MS,False,True,1.30208333333333
Numbers = Comic Sans MS,False,True,.7
# is MagneticEffect active when opening the Window
Magnet = 0.625

# Which mouse cursor to use on canvas
Canvas_Cursor = 1

# Allow dragging toolbar
Allow_Dragging_Toolbar = True

#ToolBar color(ARGB) Default WhiteSmoke slightly transparent = 200,245,245,245
Toolbar_Color = 255,245,245,245

# Process Alt as Temporary Command (configuration reset when Alt Released)
Alt_As_Temporary_Command = True

# Allow all non-global hotkeys in mouse pointer mode (may cause a mess)
Allow_Hotkey_In_Pointer_Mode = False

# Toolbar location (only applicable when allowing dragging toolbar)
Toolbar_Left = 600
Toolbar_Top = 1000

# Toolbar deployement direction Left(Original),Right,Up,Down
Toolbar_Direction=Left

# inking area : Top,Left,Width,Height ; all set to -1 for full screen
Inking_Area = -1,-1,-1,-1

# Calll Window position: Top,Left,Width(=Height),transparency
Window_POS = 990,1871,48,50

#Semi-transparent colors(ARGB) for Custom background; Gray_Board2 is reserved for future
Gray_Board1 = 80,150,150,150
Gray_Board2 = 100,100,100,100

#Background at Opening : 0:Transparent/1:White/2:Customed/3:Black / 4:Sel at Startup
BoardAtOpening = 4

# Video recording Mode ; 0 = NoVideo(and no button) ; 1 = OBS recording ; 2 = OBS Broadcast ; 3 = FFmpeg
Video_Record_Mode = NoVideo
OBS_ws_Url = ws://localhost:4444
OBS_ws_PWD = obs
FFmpeg_cmd = ffmpeg -y -f gdigrab -framerate 15 -offset_x $xx$ -offset_y $yy$ -video_size $ww$x$hh$ -show_region 1 -i desktop -c:v libx264 -preset ultrafast -crf 25 -pix_fmt yuv420p %USERPROFILE%/CAPT_%DD%%MM%%YY%_%H%%M%%S%_$nn$.mp4

#Rest Server : to be left empty to disable function
RESTServer_Url = http://localhost:7999/

#images
#size of the images in the selection form ; max 512
ImageStamp_Size = 128
#Image Background when stamped : -1 = no Frame ; 0 = empty ; 1 = ColorFilled ; 2 = White Filled ; 3 = Black Filled
ImageStamp_Filling = -1
# can work in multiple lines ; names / path are separated by semi-colons
ImageStamp_FileNames = happy.png;neutral.png;sad.png
ImageStamp_FileNames = Star.png
ImageStamp_FileNames = thumb_up.png;thumb_dn.png
ImageStamp_FileNames = tick.png;cross.png
ImageStamp_FileNames = ppinkCliparts[5x].apng
ImageStamp1 = happy.png
ImageStamp2 = neutral.png
ImageStamp3 = sad.png
----------
[Advanced Settings]

# Whether the toolbar automatically closes itself after taking a snapshot
# Values could be True, False or BlankOnly
# If Close_On_Snap = True, the toolbar closes itself after taking a snapshot
# If Close_On_Snap = False, the toolbar does not close itself
# If Close_On_Snap = BlankOnly (default value), the toolbar closes itself after taking a snapshot if there is no drawings on the screen, while not if otherwise.
Close_On_Snap = True

# Whether to hide the toolbar completely
# If Always_Hide_Toolbar = True, the toolbar will never be shown. You will have to use hotkeys.
Always_Hide_Toolbar = False

# Height of toolbar, in proportional of primary screen height.
Toolbar_Height = 0.06

#Zoom : Width;Height;Scale;Continuous(Y/N)
Zoom = 150;150;2;Y

#Measurement tools 
#Enabled
Measures_Enabled = true

# Scaling Length Factor vs 1 Pixel
Measure_Len_Scale = 1.0
# Number of decimals for Length
Measure_Len_Decimals = 1

# Length unit
Measure_Len_Unit = Pixel

# angle positive = counterClockwise(True) / ClockWise(False)
Measure_Angle_Dir=true


Inverse_MouseWheel_Control = False

```

**Comment by pubpub-zz** [comment]
For me the problem is not the exception, but the fact that the window is not displayed the first time. Can you try to redo the test keeping only one screen active

**Comment by jlogix** [comment]
When I disconnect one of the displays, the dialog appears. So it might be that the dialog is positioned off screen when there are 3 displays.

**Comment by jlogix** [comment]
I found a workaround to this issue. If I Shift+Right Click on the ClipArt dialog icon on the task bar and select Maximize, the dialog appears maximized on my display #1. I can also move the dialog using the arrow keys into a visible area on the display.

**Comment by pubpub-zz** [comment]
From the data you've send I understand that your 3 screens are in triangle. Can you tell on which screen (printscreen if possible) the toolbar is deployed and roughtly the toolbar Top Left position

**Comment by jlogix** [comment]
Here is what I noticed:

1. Toolbar on display 1 (left side screen): ClipArt dialog is offscreen regardless of the position of the toolbar on the screen
2. Toolbar on display 2 (right side screen): Clip Art dialog appears at the bottom of the screen when the toolbar is at the top of the screen
3. Toolbar on display 3 (top middle screen): Clip Art dialog appears on the bottom screen(s) (display 1 or display 2) depending on the position of the toolbar on the top screen

Hope this helps in troubleshooting.

**Comment by pubpub-zz** [comment]
the clipart dialog normally appears just above the toolbar. but if the topleft point is off any screen the dialogbox should go below the toolbar.
a) I've simplified the code, can you tell me if it is better and you can see the dialogbox on first call.
b) Also, I've added some code to prevent the exception you have indicated : can you tell me if you can still get it.
c) Finally, I've improved the moving of the toolbar. give me your feed back
[ppInk64_move15a.zip](https://github.com/pubpub-zz/ppInk/files/6826083/ppInk64_move15a.zip)

**Comment by jlogix** [comment]
a) dialog is still offscreen on first call as before
b) Still getting the exception:

![image](https://user-images.githubusercontent.com/8962258/126095220-3af9c2ce-6235-40a2-a3a6-d08f6d1400bf.png)

c) Yes, the toolbar moving is much better now - it does not jump around anymore


Thanks.

**Comment by pubpub-zz** [comment]
I've prepared a new investigation version to get the position of the toolbar and dialog at opening
[ppInk64_invt19a.zip](https://github.com/pubpub-zz/ppInk/files/6843256/ppInk64_invt19a.zip)

With debug window open, can you reopen the clipart.
you will get in the debug window at the end 2 lines starting with Toolbar and ClipArtDlg (eg)

> Toolbar 600.1000-903.65
> ClipArtDlg 686.577-816.422

They provide the position and size of the toolbar and dialogbox. Can you provide me those two lines pls

Also I've modified also the code the prevent the exception. ( you should observed that the clipart dialog to close when engaging pointer mode (with the alt+tab))

waiting for your feedbacks
PS :  the toolbar may fold when engaging inking. No worries about, unfold the toolbar and continue your test

**Comment by pubpub-zz** [comment]
@jlogix,
I think I've been able to reproduce the problem on a friend's computer : The problem was that some screens were configured with a different scale. I fixed it with changing the PPP advanced compatibility (https://github.com/pubpub-zz/ppInk/issues/92#issuecomment-841703174)

can you apply the same configuration and provide feedbacks.

**Comment by pubpub-zz** [comment]
Hi @jlogix,
Any feedbacks.

PS : if you like the program, do not hesitate to star it : I would have liked to reach 200 by the end of the month 😊

**Comment by pubpub-zz** [comment]
Hi @jlogix 
+1

**Comment by jlogix** [comment]
Sorry got busy with work. Things look much better now. Will respond if I find any problem.
