### ISSUE TITLE
[Idea] Clipart-on-stroke

### ISSUE THREAD

**Issue by NOVAinc** [pubpub-zz/ppInk#122]
Hey there again! I have had this idea for a potential feature for your tool, which I think might be quite useful for many users. I think having the ability to repeat a clipart throughout a stroke could be very handy, in special for artists and general illustration.

How I suggest it could work: When drawing a stroke, clipart instances would be generated along it. This is kind of like a particle system for the line but much simpler. These cliparts would be internally attached to the stroke so they would get deleted if the stroke is deleted, or moved all at once if the stroke is moved. There could be a setting which allows you to adjust randomness from 0 to 1 so the cliparts either generate in a straight line and follow the stroke closely, or get generated in a noisier manner and deviate from the stroke track to have a more random look. There could be a spacing option which would determine how spaced each instance gets drawn from the previous one. Here is an example. 

![proposal_fixed](https://user-images.githubusercontent.com/19545604/125819221-13bc0070-dda6-4baa-9e68-c77c10f0db04.png)

I have used an isometric brick for the example, but this could be useful to lay cliparts in a perfectly straight line such as if you wanted to insert windows on a house doodle, line up houses on a block illustration, or add random leaves to a tree drawing without having to do it manually. This would also be useful for people who would like to make their own custom stroke styles as they can make a clipart for the pattern/shape they want to use for the stroke.

PS/1: I'll make a LUT to darken grays and make them black to work around the black keying limitation with OBS. I can share the resulting LUT if you'd be interested in delivering it alongside the tool, and maybe write documentation on how it works. If you'd be interested in something like that let me know if I should post it here or elsewhere.

PS/2: Would you like to see proposals for potential UI redesigns? I'm not an expert designer, but if you would like to see an alternative look I could put something up.

**Comment by pubpub-zz** [comment]
under thinking
about PS/1 : it will be welcomed
about PS/2 : UI redesign may be very time comsuming, but I'm always open to proposals

**Comment by YouFoundJK** [comment]
@NOVAinc Interesting... This is the same feature that's available on GIMP, Photoshop and their like right? 
Hey @pubpub-zz , I wanted to know, do you have plans to include a resizing tool, where we can select things with the lasso tool and resize them? It would be especially useful for people like me who have huge handwriting.

**Comment by NOVAinc** [comment]
Yes, this is a very basic implementation for a stencil brush of sorts. I understand ppink is an annotation tool only and there must be limits drawn so people don't expect this to become more of a full drawing editor with the ability to crop, resize, rotate stuff, add layers etc. I have a specific use case for a feature like this and I thought of use cases for others too, but I would understand it getting rejected as well.

**Comment by pubpub-zz** [comment]
> Yes, this is a very basic implementation for a stencil brush of sorts. I understand ppink is an annotation tool only and there must be limits drawn so people don't expect this to become more of a full drawing editor with the ability to crop, resize, rotate stuff, add layers etc. I have a specific use case for a feature like this and I thought of use cases for others too (such as applying custom stroke styles like using rounded dots instead of squares, spacing things evenly on a straight line, etc), but I would understand it getting rejected as well.

The point is that design relies on strokes. Feasability is not yet acquired

**Comment by pubpub-zz** [comment]
> Hey @pubpub-zz , I wanted to know, do you have plans to include a resizing tool, where we can select things with the lasso tool and resize them? It would be especially useful for people like me who have huge handwriting.

the Strokes Library have a scaling option. Not sure yet on how to implement the feature, but you may raise it as an issue

**Comment by pubpub-zz** [comment]
Hi @NOVAinc @YouFoundJK 
    I've finally found a starting point to implement this function.
[ppInk64_Pattern07b.zip](https://github.com/pubpub-zz/ppInk/files/6949453/ppInk64_Pattern07b.zip)
to engage the function, select Clipart button, and in the dialog box,check the new  checkbox.
the button will be tagged with a S to identify that you are now in the tool to draw pattern along a stroke.
the cursor will change to a target : you will have to select the size as a box (or just click to use the clipartsize),
then click and release in order to adjust the distance between 2 images.
then the cursor will go to arrow, and now you can draw a(or many) stroke : images will be drawn along.

Currently copy,move are working,  but resize and rotate not yet.

Tool selection may very slightly change in order to be able to get this function through clipart1/2/3 and in order to store size and distance and accelerate drawing.

Give me your first feedbacks

**Comment by pubpub-zz** [comment]
> Woah! I'm sorry it took some time to get to this. I'm testing it now and it's amazing!

Happy you are enjoying.

> This is definitely enough to start doing very interesting stuff with it at least with my use case. I'm very much looking forward to being able to use it with line, circle, etc. It's impressive work. I'm wondering if you're planning to make the first two steps automatable by using the rest server?

I will implement the REST API with capability to provide the size and distance in order to automate. I've just finished to implement also the parameter storage in Clip1/2/3 :
[ppInk64_Pattern12a.zip](https://github.com/pubpub-zz/ppInk/files/6974415/ppInk64_Pattern12a.zip)

> I'll try to get the ppink video done soon. Let me know if you would prefer me to upload it privately and share a link with you so you can share it as a tutorial (viewable with link only) or if you'd prefer a public video people could find by searching for annotation tools instead. My YT channel is for Age of Empires, so I'd have to use a different account but I can sort that out I think.

Do your best :  I'm not sure I could not be linked with your AoE channel in some way: I remember seeing people being admiring your way to document your videos. Personnally I considerer that your videos can be both for guiding and advertising (and then the more visible it will be visible, the best it will be 😊)

**Comment by NOVAinc** [comment]
If I made the video for my channel I could link it to age for sure, but it would be something pretty niche along the lines of "how I use ppink to annotate AoE matches" instead of something more broad like "this is the best annotation tool out there - ppink guide" or something like that. My channel isn't very popular so I don't think it'd affect outreach too much (~100 subs at the moment)

**Comment by pubpub-zz** [comment]
@NOVAinc @YouFoundJK 
normally, the new object type is now complete : scale, rotate, and REST API are implemented.
[ppInk64_Pattern14a.zip](https://github.com/pubpub-zz/ppInk/files/6987201/ppInk64_Pattern14a.zip)
waiting for your feed back before release

**Comment by NOVAinc** [comment]
Hey pubpub! I seem unable to make it work, currently. I noticed the checkbox isn't there anymore, however I found the option in the drop down menu inside the frame options. I can set the size and the spacing, but drawing doesn't display the cliparts currently.


https://user-images.githubusercontent.com/19545604/129649044-64ae3201-2549-4dc5-8867-ea6afe0f8bdc.mp4

**Comment by pubpub-zz** [comment]
Oups. Wrong cleanup
[ppInk64_pattern17a.zip](https://github.com/pubpub-zz/ppInk/files/6997580/ppInk64_pattern17a.zip)

**Comment by pubpub-zz** [comment]
> 
> 
> I will create a new issue then. Thanks for the answer, looking forward to the 5º version!
I've just issued 1.8RC1 and the option is available in 

https://github.com/pubpub-zz/ppInk/releases/tag/v1.8RC1
