### ISSUE TITLE
Allow user to select which stroke styles to cycle through

### ISSUE THREAD

**Issue by NOVAinc** [pubpub-zz/ppInk#123]
I'm currently using 2 stroke styles. Standard and the last dash one. If there was an option to turn off the other styles, I could just alternate between those two without pressing D 5 times to get from the first one to the next. Alternatively, having a hotkey to reverse-cycle would solve this issue for me but probably not for someone who uses 2 equidistant styles. This is just a suggestion as currently the existing implementation is already pretty functional and works great. This is more of a quality of life or UX thing I imagine. Definitely not a pressing matter.

I understand it is possible to save a pen with a pre-defined stroke style, and that I could save one stroke style to each pen but I'm currently using 8 different colors for which I have saved different pens, and I need then to cycle through styles individually when using each pen.

**Comment by pubpub-zz** [comment]
I take the idea, 
for the moment you can use Alt+Hotkey to get temporary. Also,what about using RestAPI?

**Comment by NOVAinc** [comment]
That is a good point. I could do anything with the rest server on paper. It would be more of a workaround and take longer to set-up but it should be possible. I think having the option would still be valuable for anyone who might not know how to make use of REST or uses virtual buttons as opposed to OBS source-state to trigger the actions. For those it would add extra buttons that they could use for other actions.

**Comment by pubpub-zz** [comment]
@NOVAinc,
I agreed with this proposal. 😊
Try tihis version
[ppInk64_LSEna16a.zip](https://github.com/pubpub-zz/ppInk/files/6828870/ppInk64_LSEna16a.zip)

**Comment by NOVAinc** [comment]
I have tested the new version! It works without any regressions for me. Seems stable!
