### ISSUE TITLE
ppink unfolding itself when closing windows

### ISSUE THREAD

**Issue by NOVAinc** [pubpub-zz/ppInk#125]
I am not 100% sure if this is a feature or not, but I was unable to find an option for this in the settings.

When folded, sometimes ppink will unfold itself when you close some windows. I have been unable to replicate exactly what the behavior is. I tried a few times for it to unfold for the video but some times it will unfold and some times it doesn't. Am I missing something here or is this a bug?

https://user-images.githubusercontent.com/19545604/126201075-25564fa0-9e91-4cd8-98d6-9c5cb0fb362f.mp4

**Comment by pubpub-zz** [comment]
When ppInk get Focus, either using alt+tab or because, of closing other windows, it finally gets focus. I can not change its position in the Z-order stack as the window(s) is/are topmost to be visible which is incompatible.
Nothing to be done

**Comment by NOVAinc** [comment]
Thanks, this explains it! this should make preventing this from happening unintendedly easier. I'll close the issue then.
