### ISSUE TITLE
Allow for clipart creation with center pivot point

### ISSUE THREAD

**Issue by NOVAinc** [pubpub-zz/ppInk#126]
I think it could be useful having the ability (an option for) to have a clipart create around the click instead of using the click pixel as the 0,0 coordinate. What I mean is if there is a square clipart 100px wide and tall, when this option was enabled you would click on the screen and it would create drawing 50px to the left, and 50px to the right instead of being drawn to the bottom right of the click.

Different sizes could work still the same. Dragging the box bottom right would draw it right side up, and up left would draw it left side down.

**Comment by pubpub-zz** [comment]
In order to match Oval/Rectangle tools, I propose to use right click to center the clipart.

**Comment by pubpub-zz** [comment]
on a touchscreen, long click with the finger engages right click no way to do the same on tablet ?

**Comment by NOVAinc** [comment]
You are correct. There are a few different function methods for the pen with my tablet software and I thought the one I was using didn't support this but it turns out it does. It is definitely not essential/necessary such an option in that case. Good catch!

**Comment by NOVAinc** [comment]
I would like to add an additional suggestion for having the ability to right click without dragging for cliparts to appear at their original size around the pointer the same way left click currently makes them appear to the bottom right.

**Comment by pubpub-zz** [comment]
It was part of my thoughts 😄

**Comment by pubpub-zz** [comment]
Can you check this version
[ppInk64_CtrClip20a.zip](https://github.com/pubpub-zz/ppInk/files/6847754/ppInk64_CtrClip20a.zip)

**Comment by NOVAinc** [comment]
It works well! For whatever reason holding the pen down triggers right click on all other programs but here it just spawns the clipart normally. I can do right-click drag, but I can't seem to draw the clipart around the cursor when right clicking with the pen. I'm not sure if it is related to ppink or if there's anything that you can do, but I can also just bind the right click to a pen button and remap the function I had on that one to something else on the keyboard so it's definitely not a big issue anyway. Here's the video to demonstrate.

https://user-images.githubusercontent.com/19545604/126381909-9cb80310-77ac-4e79-aaa0-97a1d696c4ac.mp4

**Comment by NOVAinc** [comment]
This also works pretty good. The issue I had with the pen can be worked around by using one of the pen buttons for the right click or just switching to mouse for this action specifically.
