### ISSUE TITLE
Rotation/Resize tool

### ISSUE THREAD

**Issue by YouFoundJK** [pubpub-zz/ppInk#127]
I think adding an Resizing tool would be an cool upgrade for ppInk. I would love to see a tool that can essentially rescale a selection done using the Lasso Tool, preferably preserving the Ratio Aspect.

Why I would want to have something similar is that for quite a long time I have been using gInk and now ppInk to solve math problems and I have pretty huge handwriting. As of now the way round is to push the whole canvas outside the display to create space to continue the solution. It has a major drawback that I am unable to see the whole solution in one go. So what I would want to do is to rescale it to a smaller size so that I can see the whole solution on screen. 

I know it this particular feature doesn't sit well for a screen annotation app, nevertheless I think this can be quite useful for a lot of things, so perhaps it would be great to see this implemented either straight in the main app or maybe as addon or something.

**Comment by pubpub-zz** [comment]
@YouFoundJK , @NOVAinc
This is a first release for Resizing / Rotating.
the tools are within the pan button (Move / Copy / Resize / Rotate / Pan)
a short cut (default S) allow access directly to Resize/Rotate.
Currently you have first to select object(s) with the Lasso and then Resize/Rotate tool. once fixed if lasso has not been selected, the transformation will apply on the hovered stroke/object
the cursor just after tool selection is a target : you have to select the center of the rotation/scale. You can at this step use Right click to select the center position of the selection.
then the cursor becomes the arrow, and you can click and hold to rotate or resize.
Resize applies also to pen width, font size and text/image rotation.

lots of change had to be applied (old saved files are not compatible for example) do not hesitate to extend your tests

[ppInk64_ScaleRot26a.zip](https://github.com/pubpub-zz/ppInk/files/6881061/ppInk64_ScaleRot26a.zip)

**Comment by pubpub-zz** [comment]
Update : new version with the Hover working.
[ppInk_ScaleRot26b.zip](https://github.com/pubpub-zz/ppInk/files/6881433/ppInk_ScaleRot26b.zip)

**Comment by NOVAinc** [comment]
I have tested the new version. It works good as intended! I have only found the following bug:

If you resize something too big it will disappear. I have a second screen so I can drag my cursor quite far. If you try to resize text too big it will make ppink crash as well. Here is the crash log.

I would suggest storing the pivot point for each element though, since if, for example, I right click on a string of text to have it center-pivot but then when I hover on an empty part of the text, when I hover above a letter again the pivot point changes to where the cursor is.

[crash.txt](https://github.com/pubpub-zz/ppInk/files/6881505/crash.txt)

**Comment by pubpub-zz** [comment]
new version fixing the crash reported by @NOVAinc
[ppInk64_Click4LS27a.zip](https://github.com/pubpub-zz/ppInk/files/6888014/ppInk64_Click4LS27a.zip)

**Comment by YouFoundJK** [comment]
@pubpub-zz wow so cool. That is exactly what I wanted. Keeping the anchor free is a super brilliant idea. Thank you man!!

Testing ppInk_ScaleRot26b.zip - 

Here are some bugs you might want to take a look at - 
1. If you are using Eraser and then move to Mouse pointer mode, and then come back to ppInk, apparently no tool is selected by default. This DOESNT happen if you where using pen instead of eraser. I would suggest keeping the default tool a pen (even if you where using a eraser before toggling to pointer mode), while remembering the pen style selected.


https://user-images.githubusercontent.com/72195985/127212223-ec2b1290-b150-4670-868e-93810f53aef5.mp4


2. Windows Ink compatibility bug - If you toggle between the pen and eraser using the WIndows ink feature, the last drawn curve remain selected, so as soon as you use eraser anywhere on the screen, that curve gets erased.


https://user-images.githubusercontent.com/72195985/127214063-5502ddf0-17f2-4a4e-a7ef-b59499cf0155.mp4

**Comment by NOVAinc** [comment]
I have also found an issue where if you resize by dragging the cursor too far it will stop resizing at a certain distance, and then "snap" to a larger size after you get past a point further away.

Here is a video. I am dragging my cursor over to my second screen. It stops resizing when I'm about 1/3 across the second screen. It gets larger all of a sudden when I get about 2/3 across it and then works normally until I get to the end.

https://user-images.githubusercontent.com/19545604/127228847-f102a33f-6e88-47d2-8c2f-465678aafb1c.mp4

**Comment by pubpub-zz** [comment]
@YouFoundJK,
The Erase Mode and Ink compatibility should be solved

same for you issue about resisizing @NOVAinc 
[ppInk64_Pen31a.zip](https://github.com/pubpub-zz/ppInk/files/6911117/ppInk64_Pen31a.zip)

**Comment by chrisj0192** [comment]
Hello @pubpub-zz I was testing your new release (ppInk64_Pen31a.zip) and it's great. I have a recommendation and I'd like to know your opinon. As you know I use full hotkeys and my recommendation is that you could leave "move/copy/pan" as one hotkey combination and another one with "scale/rotate". From my point of view one hotkey combination have a lot of functions that to reach one from another is a little bit uncomfortable it's less dynamic I've also noticed that you put anoter hotkey for "scale/rotate" too unless there are a way to deactivate scale/rotate in "move/copy/scale/rotate/pan" hotkeys.

**Comment by pubpub-zz** [comment]
Hi @chrisj0192,
This is an interim solution first focusing on the functions.
The biggest point is  about the fact is that I would like to put Scale / Rotate in an independant button. I might be a small one, next the lasso/move and I'm thinking about something like that :
![image](https://user-images.githubusercontent.com/4083478/127750526-8f73ccf4-e402-48fc-bd77-0fdc6c6814a4.png)

There will be a little of room for further function

**Comment by pubpub-zz** [comment]
@chrisj0192, @NOVAinc , @YouFoundJK 
I've prepared a new version putting in a separate button, I've also done some rework on save/load strokes in order to save variable width stroke drawn with a pen.
[ppInk64_SavLoad05a.zip](https://github.com/pubpub-zz/ppInk/files/6938258/ppInk64_SavLoad05a.zip)

**Comment by NOVAinc** [comment]
I like the new separate icons better myself as well! From my testing it seemed to work well still. I haven't encountered any issues besides maybe performance when upscaling to ridiculous scales which I don't think is intended and won't affect most people 99% of the time most likely.

**Comment by pubpub-zz** [comment]
1.8RC1 released
