### ISSUE TITLE
Suggestion for cycling through stroke styles by clicking on pen icon

### ISSUE THREAD

**Issue by NOVAinc** [pubpub-zz/ppInk#129]
This is just a suggestion I thought. Similarly to how you can click more than once on the freehand or shape tools to switch between stroke only, fill shape, etc I think it could be good for the UX to be able to click again on the same pen and have it switch to the next stroke style. What do you think?

**Comment by pubpub-zz** [comment]
@NOVAinc,
I'm boggled about this idea : I'm not so fond of having a click that may change the configuration. I personnally dislike this idea but this may interest others. If I introduce it,I will certainly add a option to enable/disable it. I will evaluate the work to be done before any work.

**Comment by NOVAinc** [comment]
Sure thing man. The reason I thought this might be good was because it is already possible to cycle through fill styles when clicking on the freehand or shape tools more than once, so I thought it would be consistent. In any case, it wouldn't be more than a small convenience.

**Comment by pubpub-zz** [comment]
Prefer you to publish yourself.

**Comment by pubpub-zz** [comment]
@NOVAinc,
This version includes the option(you have to enable it in options/Pens panel)
[ppInk64_Click4LS27a.zip](https://github.com/pubpub-zz/ppInk/files/6888014/ppInk64_Click4LS27a.zip)
Give me your feedbacks.
PS :this version also includes the fix for crash during resizing

**Comment by NOVAinc** [comment]
The style cycling feature works perfect! I found a bug on the resize feature but I'll report it on the other issue thread.

**Comment by NOVAinc** [comment]
I think this is working well in the last few releases so I'd consider it closed myself.
