### ISSUE TITLE
QUESTION: Toolbar resize

### ISSUE THREAD

**Issue by santiagoc** [pubpub-zz/ppInk#13]
Hello, it is possible to resize the toolbar icons?

**Comment by pubpub-zz** [comment]
Yes Toolbar resizing was already implemented but was only accessible through config.ini
I've added the parameter in option dialog. This version includes also to work in progress with a new dialog box to edit pen's attribute
[ppInk.zip](https://github.com/pubpub-zz/ppInk/files/5198134/ppInk.zip)
