### ISSUE TITLE
new translation?

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#131]
@YouFoundJK
Looking on the network view, I've noticed that you are working on some translation. Could it be interested to share with other users?

**Comment by YouFoundJK** [comment]
Hey, yes I plan to get at least two Indian language translation done. As of now I am half way through one of them - mal.txt. I will merge them  them as soon as I am done. I am running on a pretty hectic schedule right now, so it might take some time.

**Comment by pubpub-zz** [comment]
I close this thread. If you can please publish in #17 when you will be ready 😊
