### ISSUE TITLE
Dragging the dock will result in a weird interaction

### ISSUE THREAD

**Issue by rexelbartolome** [pubpub-zz/ppInk#134]
Yellow: Not Clicking
Purple: Left Click

https://user-images.githubusercontent.com/88552647/128984257-bfb52c6b-e85b-46fe-a62f-f004be9da124.mp4

The current workaround is to just drag the window slower, as the bug is more likely to happen when the dock can't catch up to the cursor.

**Comment by pubpub-zz** [comment]
This was reported earlier and a beta is available:
https://github.com/pubpub-zz/ppInk/issues/120#issuecomment-880995088

It will be part of next official release

**Comment by rexelbartolome** [comment]
> This was reported earlier and a beta is available:
> [#120 (comment)](https://github.com/pubpub-zz/ppInk/issues/120#issuecomment-880995088)
> 
> It will be part of next official release

Oh, okay then!
