### ISSUE TITLE
Options window only opens when toolbar is closed with X

### ISSUE THREAD

**Issue by mrvainv2** [pubpub-zz/ppInk#14]
Excellent fork of gink. 

In my case on two systems - 1) 1 screen and 2) 3 screens - I was only able to access the option panel via the icon when I closed the toolbar with the X (the transparent pencil icon appears).

**Comment by pubpub-zz** [comment]
Hi @mrvainv2 ,
Happy my fork please you.
About your issue, I've adapted the patch https://github.com/pubpub-zz/ppInk/commit/d149bb81ff8120df746af3fc7208305564ce0687 from the original gink. It was wanted to be able to open only one option window and to prevent it to be opened while the toolbar is already opened. However, I've noted that you should be able to open the option window, and then open the toolbar. I'm using this configuration when I'm modifying parameters to adjust them before saving.

**Comment by pubpub-zz** [comment]
Is my explaination clear. Ok to close it ?
