### ISSUE TITLE
Feature request: ability to type text along an arrow or arbitary direction

### ISSUE THREAD

**Issue by chuong** [pubpub-zz/ppInk#142]
This app really excites me particularly at this time when many of us work from home and need to communicate over a computer screen.
Text annotation is one of the most important features. It would be great if we could rotate text or select text direction from the start. In the case of an arrow, the ability to type along its axis will add more meaning and make it look cleaner together.
Many thanks.

**Comment by pubpub-zz** [comment]
Too Late for version 1.8RC1, but this should be good for your test:
[ppInk64_TextOnArrow28a.zip](https://github.com/pubpub-zz/ppInk/files/7071421/ppInk64_TextOnArrow28a.zip)

To activate the function, draw your arrow, then select the text tool, press ctrl, and hover the arrow : the arrow will be selected to indicate which shape to use. then press left button and release it where you want to start your text :  the orientation will apply immediately on the text.
This will also work with any other shapes, even hand , in this case the orientation next to the cursor when pressing down the left button will be used.

Give me your feed back

**Comment by chuong** [comment]
@pubpub-zz It works great for the arrow when it points left to right, up, or down. 
When the arrow points from right to left, the text becomes inverted. Not sure what is the best way to deal with this.

I am not sure if it makes sense for other shapes because those have fixed orientation, unless there's an option to rotate other shapes and the text will copy the orientation.

**Comment by pubpub-zz** [comment]
I see I've changed the angle calculation This is what you will get
![image](https://user-images.githubusercontent.com/4083478/131243944-87c246d6-198a-41c9-869c-efaee68ff0f4.png)
I've attached  an example with a rotated rectangle which can also be usefull.

[ppInk64_TextOnArrow29a.zip](https://github.com/pubpub-zz/ppInk/files/7072142/ppInk64_TextOnArrow29a.zip)

**Comment by chuong** [comment]
@pubpub-zz Thanks. This works well. 

For the corner case when the arrow points exactly down (-90 degrees), maybe keep the text going down the arrow direction, instead of going up like in your example?

**Comment by pubpub-zz** [comment]
sorry for late answer. 
this should be good
[ppInk64_eras06a.zip](https://github.com/pubpub-zz/ppInk/files/7115651/ppInk64_eras06a.zip)

**Comment by chuong** [comment]
This version looks great, the text goes as intended. Thanks @pubpub-zz
