### ISSUE TITLE
Remove Red/Black Border on "Window Mode"

### ISSUE THREAD

**Issue by jdwolin** [pubpub-zz/ppInk#143]
The Window Mode is extremely useful but the red border is distracting.  Is there an easy way to make it transparent/invisible?

**Comment by pubpub-zz** [comment]
I've introduced the option in 1.8RC1 : you have to change the parameters in config.ini
https://github.com/pubpub-zz/ppInk/releases/tag/v1.8RC1

Do not hesitate to star the project if you enjoy it 😉

**Comment by jdwolin** [comment]
Perfect!  Starred.

**Comment by jdwolin** [comment]
I use the window mode so that I can click outside the drawing area to scroll.  However, when we scroll, the drawing overlays no longer make sense.  Can we create an option to automatically erase the drawing area when ppink looses focus?

**Comment by pubpub-zz** [comment]
Here you are a beta version
[ppInk64_eras06a.zip](https://github.com/pubpub-zz/ppInk/files/7115651/ppInk64_eras06a.zip)

the function is controled in config.ini by Erase_On_FocusLost
In next versions it will be set to false.

**Comment by jdwolin** [comment]
I am so appreciative of the help you've provided and the quick response to enhancements.  Love the software!  Great work.  One more request.  Is there a way to make a separate hotkey to start ppink and another to close ppink rather than the current toggle functionality that defaults to ctrl + alt + g.   The reason is so that when the gui is hidden it would be nice to be certain that draw  mode is now active rather than wonder if perhaps it was already active and it was accidentally turned off.  Something to consider.

**Comment by jdwolin** [comment]
I am so appreciative of the help you've provided and the quick response to enhancements. Love the software! Great work. One more request. Is there a way to make a separate hotkey to start ppink and another to close ppink rather than the current toggle functionality that defaults to ctrl + alt + g. The reason is so that when the gui is hidden it would be nice to be certain that draw mode is now active rather than wonder if perhaps it was already active and it was accidentally turned off. Something to consider.
