### ISSUE TITLE
您好，在使用橡皮擦工具后，鼠标箭头光标再次变成红色的大箭头

### ISSUE THREAD

**Issue by mingyiewang** [pubpub-zz/ppInk#146]
您好，在使用橡皮擦工具后，鼠标箭头光标再次变成红色的大箭头

**Comment by pubpub-zz** [comment]
Sorry can translate it into english. I can not read chinese

**Comment by mingyiewang** [comment]
Thank you for your help.
Could you make the big red arrow smaller&nbsp; or change its&nbsp; shape&nbsp; like a pen.
like this


Thank you very much.

**Comment by pubpub-zz** [comment]
put the ico file from this zip in ppInk folder and it should be good.
[cursorarrow.zip](https://github.com/pubpub-zz/ppInk/files/7117682/cursorarrow.zip)
as said you just need to modify the file with any image editor such as gimp.

Do not hesitate to star the project if you enjoy it/

**Comment by mingyiewang** [comment]
Thank you, but the problem haven't been sovled yet.

**Comment by pubpub-zz** [comment]
Can you please clarify all the actions you have done

**Comment by pubpub-zz** [comment]
I checked on my side and everything looks good:
here you are my deployed version
[ppInk_wand09a.zip](https://github.com/pubpub-zz/ppInk/files/7135989/ppInk_wand09a.zip)

**Comment by mingyiewang** [comment]
Thank you. It has solved already.

**Comment by pubpub-zz** [comment]
happy you are enjoying. Do not hesitate to star the project 😊

**Comment by mingyiewang** [comment]
yeah, I like it very much. Thanks a lot again.
