### ISSUE TITLE
When choosing Canvas Cursor (arrow) 0 unable to enter text 

### ISSUE THREAD

**Issue by mrvainv2** [pubpub-zz/ppInk#15]
I changed the canvas cursor to the arrow via the ini file as on my screens I loose track of the small "laser". When I change the settings (did this on two machines), I was not able to enter text when I click the text icon.

**Comment by pubpub-zz** [comment]
Can you please clarify the parameter you've changed and indicate the values before and after. Normally the cursor parameter can be changed from options panel ("Canvus Cursor") Can you tell me is this is working through there ?

**Comment by mrvainv2** [comment]
Canvus = Canvas
I used the options settings now (and changed to arrow - back and forth - I need to apologize, I misinterpreted the icons. I thought "the correction icon" was text-entry icon.

**Comment by pubpub-zz** [comment]
I understand that this is clear now. If so can you close it ?
