### ISSUE TITLE
Language Lose

### ISSUE THREAD

**Issue by xue-blood** [pubpub-zz/ppInk#152]
The Language key `LineSubToolsHints` in english has six item split by `\n`, but only five in other   Language.
And It will cause an exception at this line:
![image](https://user-images.githubusercontent.com/18024882/136726749-2aaa2890-824f-4612-ac4b-a797a0ac0a7f.png)
Finding in `ar.txt`, `es.txt`,`es-es.txt`, `id-in.txt` `pt-pt.txt` `zh-cn.txt` `zh-tw.txt`
![image](https://user-images.githubusercontent.com/18024882/136726971-f0eef504-9921-4af4-a59b-bd00a26443ac.png)

**Comment by pubpub-zz** [comment]
exception handling has been added to prevent crash.
beta version available here :[ppInk64_M3uObs19a.zip](https://github.com/pubpub-zz/ppInk/files/7741103/ppInk64_M3uObs19a.zip)

**Comment by xue-blood** [comment]
> exception handling has been added to prevent crash. beta version available here :[ppInk64_M3uObs19a.zip](https://github.com/pubpub-zz/ppInk/files/7741103/ppInk64_M3uObs19a.zip)

Yes, I'd tested all language and they all are working fine.
Thanks for your hard work.
