### ISSUE TITLE
Weird crash.

### ISSUE THREAD

**Issue by ignash3d** [pubpub-zz/ppInk#154]
![image](https://user-images.githubusercontent.com/83746652/138040915-84609345-d99c-4488-93b0-38047e31a14d.png)

It happens everytime I draw something and then click ESC to remove it.

**Comment by pubpub-zz** [comment]
@ignash3d 
the error seems to deal with cliparts buttons. can you please provide your config.ini file in order to try to reproduce it

**Comment by pubpub-zz** [comment]
@ignash3d 
any update ?

**Comment by pubpub-zz** [comment]
@ignash3d
any update ?

**Comment by pubpub-zz** [comment]
Without update, I close this issue for the moment. fell free to reopen it when you will have more details to provide
