### ISSUE TITLE
Potential Ransomware Attack detected when running this application by my Admin

### ISSUE THREAD

**Issue by vallabhdutt** [pubpub-zz/ppInk#156]
Potential Ransomware Attack detected when running this application by my Admin

**Comment by pubpub-zz** [comment]
Hi @vallabhdutt ,
ppInk has been reported as a false positive.
have a look at #145 : you may try the simplified version.

**Comment by pubpub-zz** [comment]
@vallabhdutt, what is the status ?

**Comment by pubpub-zz** [comment]
@vallabhdutt, what is the status ?

**Comment by pubpub-zz** [comment]
@vallabhdutt Any update?

**Comment by pubpub-zz** [comment]
@vallabhdutt Without update, I consider that my beta fixed your issue. Do not hesitate to re-open the issue if you have any update
