### ISSUE TITLE
Add the option to hide specific icons

### ISSUE THREAD

**Issue by borjafg** [pubpub-zz/ppInk#159]
I have tried to hide those icons, but checking the option that hides them also hides the tools for drawing geometric shapes and inserting text.

I guess that means they can't be hidden separately. Could this option be included in a future version of the program?

-----

I want to hide this icons:

![image](https://user-images.githubusercontent.com/6740268/142160544-d7eb21b9-2681-4d18-84fd-adc03b6b7d78.png)

But the result is:

![image](https://user-images.githubusercontent.com/6740268/142161506-bf3e88b5-3e20-496e-9428-118aeea7d887.png)

**Comment by pubpub-zz** [comment]
hi @borjafg,
I've implement some options to hide some buttons, but those are introducing some are introducing complexity. I have currently no intend to add extra options to hide buttons. maybe a more advanced configuration in a further future....
