### ISSUE TITLE
Remote Desktop and Citrix Windows are on top of the ppink

### ISSUE THREAD

**Issue by mrvainv2** [pubpub-zz/ppInk#16]
Small Issue - in of usage of Citrix or Remote Desktop, the drawings of ppInk are created but in the background of the Citrix or Remote desktop window. Gink puts the annotations on top.

**Comment by pubpub-zz** [comment]
ppInk (and gInk) are  working with a transparent window which with topmost set. Some other program, maybe citrix is using the same attribute. when multiple windows are using this same attribute they behave in the same way and will overlap each others. My assumption is that randomly, To confirm that,"fix that", what you can do is to use alt-tab to reselect ppink which whill bring it back to effective topmost. next time can you test that ?
