### ISSUE TITLE
API call to set Line type to Stroke is broken

### ISSUE THREAD

**Issue by mmc-terraform** [pubpub-zz/ppInk#162]
When I try to set Line type to Stroke, I get this error. The other types works fine.
`!!!! Error in Query (GET) - http://localhost:7999/PenDef?P=0&L=Stroke `

**Comment by pubpub-zz** [comment]
Hi I've found the bug
Can you test this version
[ppInk_ApiRest28a.zip](https://github.com/pubpub-zz/ppInk/files/7614511/ppInk_ApiRest28a.zip)
PS : I've also added the linestype in the return.

**Comment by mmc-terraform** [comment]
Thanks so much for the quick turn around. It works perfectly.

**Comment by pubpub-zz** [comment]
can I ask you how you are using the REST API?

**Comment by mmc-terraform** [comment]
I'm using the REST API to setup my Streamdeck. I toggle between Stroke and Dash using an AutoHotKey script assigned to a button on the Streamdeck.

```
#NoEnv
/*
	[settings]
	line_type=Dash
*/
Full_URL := "http://localhost:7999/PenDef?P=0&L="
IniRead, lt, %A_ScriptFullPath%, settings, line_type
Full_URL := "http://localhost:7999/PenDef?P=0&L=" . lt

WebRequest := ComObjCreate("WinHttp.WinHttpRequest.5.1")
WebRequest.Open("GET", Full_URL, false)
WebRequest.Send()

if (lt = "Stroke")
{
	IniWrite, Dash, %A_ScriptFullPath%, settings, line_type
}
else
{
	IniWrite, Stroke, %A_ScriptFullPath%, settings, line_type
}


```

**Comment by pubpub-zz** [comment]
if you just want to toggle, have you tried to use just standard streamdesk / toggle 
![image](https://user-images.githubusercontent.com/4083478/143955633-b0794aad-c035-4000-a771-e03c02d2eb42.png)

and add in the actions just a web action

![image](https://user-images.githubusercontent.com/4083478/143955583-9819b86f-0cfc-4eb6-b19c-c4e93e0bbc32.png)

**Comment by mmc-terraform** [comment]
Ah! I didn't know there was a multi action switch. Makes life much easy for me. Thanks a lot for letting me know.

**Comment by abolfazlkhosravani** [comment]
> 



> Hi I've found the bug Can you test this version [ppInk_ApiRest28a.zip](https://github.com/pubpub-zz/ppInk/files/7614511/ppInk_ApiRest28a.zip) PS : I've also added the linestype in the return.
> 
> Give me your feed back and star the project if you enjoy it😊



> Hi I've found the bug Can you test this version [ppInk_ApiRest28a.zip](https://github.com/pubpub-zz/ppInk/files/7614511/ppInk_ApiRest28a.zip) PS : I've also added the linestype in the return.
> 
> Give me your feed back and star the project if you enjoy it😊

https://user-images.githubusercontent.com/47294908/143980367-676cdc2b-1ded-4ed4-992b-bb1c9ad2693a.mp4


Thanks, this version has been improved. When I press the mouse pointer, the text is deleted after the mouse click, and secondly, when I hide the text, it is displayed with the mouse click.

**Comment by pubpub-zz** [comment]
Oups, a new feature was aded in #143, and the activation parameter was left active:
in the config.ini 
change  Erase_On_FocusLost to False
