### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by xx299x** [pubpub-zz/ppInk#166]
![image](https://user-images.githubusercontent.com/23482348/146535191-a2ecb31d-7e84-4235-8804-e16c6867a36f.png)

**Comment by pubpub-zz** [comment]
it sounds like a duplicate of #164 a beta is available in the thread can you try it

**Comment by xx299x** [comment]
> it sounds like a duplicate of #164 a beta is available in the thread can you try it

it works well! thanks you!

**Comment by pubpub-zz** [comment]
You are the second to report this issue, the fix will be embedded in the next release in the next days/weeks. meanwhile I will keep this thread open for any one to find quicker the beta (also available here: [ppInk_CrashExit10a.zip](https://github.com/pubpub-zz/ppInk/files/7692740/ppInk_CrashExit10a.zip) )
