### ISSUE TITLE
Automatically switches back to drawing mode when you minimize everything

### ISSUE THREAD

**Issue by IcyFrogs** [pubpub-zz/ppInk#175]
When you are in mouse mode and minimize all of the windows you have open, when the desktop shows, it opens ppink panel and automatically switches back to drawing mode

**Comment by pubpub-zz** [comment]
Hi @IcyFrogs 
My guess : When you are minimizing all windows, ppink seem to get the focus which unfolds the toolbar and exits pointer mode.
Can you try to uncheck behavior on alt tab
![image](https://user-images.githubusercontent.com/4083478/150527762-632e712f-e038-4829-b26f-5f451229b20d.png)
