### ISSUE TITLE
Saving and loading text boxes

### ISSUE THREAD

**Issue by smirich** [pubpub-zz/ppInk#176]
Hi!  So, let me start by saying that I love this program!!  I use it to annotate when teaching Computer Science.  Thanks so much for this!  I do, however, have one small problem.  If I create a text with the following:

"Test
++++++++
helloworld"

and then save it, when I load it back in, it displays correctly but, when I go into the edit window, it displays as Test++++++++helloworld without any line breaks.  The actual display is still correct but the edit window has no line breaks which makes it tough to edit.  If I do go into the edit window and hit return to make the edit window display correctly, it adds a line break to the displayed text.  

It's a small thing but it actually has big consequences for me as I like to use your product to draw class diagrams on the fly and they require horizontal separator lines.

Thanks again for building such a great product!
Rich.

**Comment by pubpub-zz** [comment]
Hi @smirich,
thanks for your comments.
I think I've found a fix : 
[ppInk64_fixMLedt.zip](https://github.com/pubpub-zz/ppInk/files/7920185/ppInk64_fixMLedt.zip)
Give me the results of your tests, and do no hesitate to star the project

**Comment by pubpub-zz** [comment]
@smirich 
is it ok for you?

**Comment by pubpub-zz** [comment]
@smirich 
+1

**Comment by smirich** [comment]
Hi!  So sorry for the delay responding.  This fix works perfectly!!!!  I have been using it for the past 2 days straight as I build video lessons and it is flawless.

Thank you so much!
Rich.

**Comment by pubpub-zz** [comment]
happy you enjoy. do not hesitate to star the project 😊
