### ISSUE TITLE
Allow binding global hotkeys without modifier

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#177]
from @fullzero87  in https://github.com/geovens/gInk/issues/152
> I want to use usles but handy F1 key without any modifiers to enable/disable glnk.

**Comment by pubpub-zz** [comment]
Here a beta test version removing limitation on global hotkey.
[ppInk64_Hk24a.zip](https://github.com/pubpub-zz/ppInk/files/7929391/ppInk64_Hk24a.zip)
note that hotkeys using prtscr or win can not be used (early captured by windows)

waiting for test reports

**Comment by fullzero87** [comment]
> Here a beta test version removing limitation on global hotkey. [ppInk64_Hk24a.zip](https://github.com/pubpub-zz/ppInk/files/7929391/ppInk64_Hk24a.zip) note that hotkeys using prtscr or win can not be used (early captured by windows)
> 
> waiting for test reports

Tested this version. Hotkeys without modifiers working as expected. Can be assigned and used.

But there are some issues in program behavior and settings. I personally prefer behavior of glink where I can use same key for toggle drawing without need to exit with different key binding.
Best experience of using hotkeys I had with gromit-mpx linux program. Very simple, useful, can configure multiple global hotkeys (F1 for toggle drawing, shift + F1 for clear). Also gromit-mpx supports wacom pen pressure value for line width and eraser.

**Comment by pubpub-zz** [comment]
hi @fullzero87 

> But there are some issues in program behavior and settings. I personally prefer behavior of glink where I can use same key for toggle drawing without need to exit with different key binding.

Can you please clarify with an example

> Best experience of using hotkeys I had with gromit-mpx linux program. Very simple, useful, can configure multiple global hotkeys (F1 for toggle drawing, shift + F1 for clear). 

With the mod proposed You can set up something quite similiar. F1 to start inking then it will enter/exit cursor mode
and set shift+F1 to clear.

> Also gromit-mpx supports wacom pen pressure value for line width and eraser.
I have done some test  (have a look on https://github.com/pubpub-zz/ppInk  , there is some demonstration)  and all works for me. so far from I remember, wacom should be correctly set up (sorry I do not have my tablet with me to capture the setup)
