### ISSUE TITLE
Width parameter is API PenDef is integer, not float (wrong in docs?)

### ISSUE THREAD

**Issue by LucaBoschetto** [pubpub-zz/ppInk#180]
From the API docs I read:

`https://localhost:7999/PenDef?P=n[&Browse][&R=nnn&G=nnn&B=nnn][&T=nnn]**[&W=nnn.n]**[&F=True|False|nnn.n][&L=aaaaa]`

with:

> W = Width **(float)**

but when I GET, for example:

`GET http://localhost:7999/PenDef?P=0&R=0&G=0&B=0&T=0&W=10.0`

I get:

`!!!! Error in Query (GET) - http://localhost:7999/PenDef?P=0&R=0&G=0&B=0&T=0&W=10.0`

If I replace W with an integer, it works:

`GET http://localhost:7999/PenDef?P=0&R=0&G=0&B=0&T=0&W=10`

```
// 20220303143413
// http://localhost:7999/PenDef?P=0&R=0&G=0&B=0&T=0&W=10

{
  "Pen": 0,
  "Red": 0,
  "Green": 0,
  "Blue": 0,
  "Transparency": 0,
  "Width": 10,
  "Fading": false,
  "Enabled": true
}
```

**Comment by LucaBoschetto** [comment]
Also, it seems that the call works if the value is an integer, but the actual pen width does not change.

I am using [ppInk_ApiRest28a.zip](https://github.com/pubpub-zz/ppInk/files/7614511/ppInk_ApiRest28a.zip) because I was having the problem with the Stroke as well. It has not been integrated in the current release, right?

**Comment by pubpub-zz** [comment]
Hi @LucaBoschetto,
the width in microsoft.ink library is a float/single (unit HiMetric if I'm right) therefore I prefer to fix the code
[ppInk64_RestWidth03a.zip](https://github.com/pubpub-zz/ppInk/files/8181375/ppInk64_RestWidth03a.zip)
can you tell me if it's OK for you ?
PS . can you tell how you plan to use the REST API, I'm curious.... 😊

**Comment by LucaBoschetto** [comment]
Hi @pubpub-zz, thank you for the quick reply and tentative fix!

First of all: I am using the REST API to integrate ppInk with Touch Portal. This is my (still unfinished!) interface to ppInk from my phone:

![Screenshot (Mar 4, 2022 09 14 34)](https://user-images.githubusercontent.com/61137723/156725924-cd382c2a-145f-4803-91a0-82d33aeaf83c.png)

As I said, it's unfinished. The intent is to have a stripped-down interface with respect to yours in the app, with just the most basic features, for quick interaction during online lessons. I am still trying to complete the synchronization of Touch Portal with the app when a status gets changed through keyboard shortcuts, and I still want to add a few buttons (solid/dashed, for sure), and then it should be done.

If I finish it and it works fine, I would gladly contribute it to you and in the Touch Portal plugins page.

Second: unfortunately, your fix does not work. It does not return an error anymore, but it sets the Width parameters wrong (it ignores the decimal point) and, what's more, it doesn't actually set the width of the pen (it remains unchanged), but that was already a problem before this fix.

```
// 20220304090929
// http://localhost:7999/PenDef?P=0&R=0&G=0&B=0&T=0&W=20.0&F=false&L=Stroke

{
  "Pen": 0,
  "Red": 0,
  "Green": 0,
  "Blue": 0,
  "Transparency": 0,
  "Width": 200,
  "Style": "Stroke",
  "Fading": false,
  "Enabled": true
}
```

I am really interested in completing this little project of mine, so please consider me available to test all your future fixes related to this problem!

**Comment by pubpub-zz** [comment]
@LucaBoschetto,
Love your project.😍 Once you will have finished I will refer it in readme.md
Thanks for your support. The query was working for me, this pushed me into an issue linked with culture. I've forced the invariant culture on the conversion. Working perfectly with 20.0 and 20.1
Try this new beta:
[ppInk64_RestWidth05a.zip](https://github.com/pubpub-zz/ppInk/files/8190382/ppInk64_RestWidth05a.zip)

**Comment by LucaBoschetto** [comment]
I tried your new beta.

I think that it was the Italian locale that threw your code off, right? Yes, unfortunately we use a decimal _comma,_ not a decimal dot.

Your beta works better now, but there are still two issues:

1) The JSON now uses the locale-specific decimal separator, whereas I think it should always be a decimal period regardless of the locale:

```
{"Pen":0,
"Red":0, "Green":0, "Blue":0, "Transparency":0,
"Width":20,1,   // <-- See the comma between "20" and "1" here? It should be a period.
"Style":"Stroke",
"Fading":false,
"Enabled":true
}
```

2) The API still does not set the actual width of the pen: even after this call, it remains set to whatever the previous width was.

**Comment by pubpub-zz** [comment]
@LucaBoschetto 
I've forced the dot for conversion, can you confirm it is ok

The pen width not being updated was due to the fact that the current pen was the modified one. It should be fixed also
[ppInk64_RestWidth06a.zip](https://github.com/pubpub-zz/ppInk/files/8193038/ppInk64_RestWidth06a.zip)

**Comment by LucaBoschetto** [comment]
Confirmed! Both the dot in the JSON output and the width work perfectly now! 🥳🎉 Thank you! 😊
