### ISSUE TITLE
Start with toolbar/dock minimized (space)?

### ISSUE THREAD

**Issue by Heart1010** [pubpub-zz/ppInk#183]
I can't find an option to start the drawing with a minimized toolbar - is this possible?

So I click the ppInk Icon to start my drawing - the toolbar appears (opened) - when I press space now the toolbar gets minimized.
Is there a way I can have the toolbar minimized by default when I start drawing?

Thanks for this amazing program 👍

**Comment by pubpub-zz** [comment]
Hi @Heart1010,
there is an old option only accessible that always hide the toolbar (not tried for a while):
Always_Hide_Toolbar = False
You will have to use only shortcuts
tell me if it's ok for you

**Comment by Heart1010** [comment]
Thanks @pubpub-zz  - found that one and tested it but as you said I'm left with totally no toolbar then.
I still want to use the toolbar whenever I have to change a color etc - but in 90% I only need the default color to draw something on the screen so a default minimized toolbar (only the arrow) would be perfect.

**Comment by pubpub-zz** [comment]
@Heart1010 
This feature may be of interrest and of use. I've currenly implented the function where the parameter is only acceptable in the file config.ini (Toolbar_Docked_at_Open set to true for you in this beta below)
[ppInk64_kpDockOpen04a.zip](https://github.com/pubpub-zz/ppInk/files/8411687/ppInk64_kpDockOpen04a.zip)
If you want to remove buttons, uncheck them in the option dialog

**Comment by Heart1010** [comment]
Great! Thanks a lot... this pp icon is always visible now - can't find a way to deacitve it. It is also not the secondary toolbar (have not activated that option)
![image](https://user-images.githubusercontent.com/1481680/161606667-30dddcdf-8065-4af4-8ccb-8f7eaf147277.png)
