### ISSUE TITLE
I get an error when I try to draw a circle or a box

### ISSUE THREAD

**Issue by S-Captain** [pubpub-zz/ppInk#184]
![image](https://user-images.githubusercontent.com/58456995/161998585-4c253220-6f97-4b8e-821f-a4bd9b0ca652.png)
I get an error when I try to draw a circle or a box

**Comment by pubpub-zz** [comment]
@S-Captain,
I think the fix is in the pipe (allready commited but not yet integrated in an official release)
Can you try this beta version
[ppInk64_kpDockOpen04a.zip](https://github.com/pubpub-zz/ppInk/files/8411687/ppInk64_kpDockOpen04a.zip)

**Comment by S-Captain** [comment]
@pubpub-zz 
Yes, thank you very much. That solves my problem for the time being
