### ISSUE TITLE
crash when start in surface x

### ISSUE THREAD

**Issue by zjh3029** [pubpub-zz/ppInk#186]
hellow,  when I download the latest version ppink(version 1.8.2) to start , it always crashes down. 
The log is:
05 / 08 / 2022 19:26UnhandledException

version 1.8.1.24635 built on 28/08/2021 13:41
Oops, ppInk crashed! Please include the following information if you plan to contact the developers:

未能加载文件或程序集“Microsoft.Ink, Version=6.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”或它的某一个依赖项。系统找不到指定的文件。

Stack Trace:
   在 gInk.Root..ctor()
   在 gInk.Program.Main() 位置 D:\gink.git\ppInk\src\Program.cs:行号 76

sys info :

surface x 
ARM windows 11
help plz.

**Comment by pubpub-zz** [comment]
ppInk uses some DLL including microsoft.ink.dll which are in the same folder. the version provided is for x64 not for arm64. I currently have not been able to find a version compatible with. If you can try to find microsoft.ink.dll for arm64, it would be apreciated.

**Comment by zjh3029** [comment]
OK, thanks.
