### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by sonichy** [pubpub-zz/ppInk#187]
https://s1.ax1x.com/2022/05/22/OxuwDO.jpg

**Comment by pubpub-zz** [comment]
@sonichy,
can you please provide the crash.txt file, and provide mode detail about circumstances (actions engaged, tools selected, ...)

**Comment by sonichy** [comment]
When I run the app the second day the crash disapear !
Maybe It caused by gInk, I test them in ten minute !

**Comment by pubpub-zz** [comment]
ok. I hope you will like it
