### ISSUE TITLE
3x Z (hotkey) and ppinkS crashes

### ISSUE THREAD

**Issue by Heart1010** [pubpub-zz/ppInk#199]
When I activate ppinkS and press 3 times key 'Z' (zoom) - with the 3rd press of the Z key ppinkS crashes with this message. What I'm wondering is the E:\... in there (I don't have hard drive E:\ here)

![image](https://user-images.githubusercontent.com/1481680/188269451-d52b7e25-40fa-4d5b-afaf-17be1c48b460.png)

_(I'm using v.1.8.3 ppinkS version)_

P.S.: And btw. can I change the zoomed area (when I pressed 1 time key Z)?
I find it strange that the zoomed area (marked with a red rectangle) shows that region when my mouse pointer is in the red circled marked spot :raised_eyebrow:

![image](https://user-images.githubusercontent.com/1481680/188269700-677d56e9-d5f5-4823-a64e-38927eb87919.png)

**Comment by pubpub-zz** [comment]
a) the e:\ppink.src is the top folder where I'm building ppInk. Because of that the log uses this path
   I will see if I can find the issue, but I need a few more details : can you reproduce the problem with ppInk.exe? Are you using multiple screens (if yes have you applied the recommanded tip:

>     There is a known issue for multiple displays of unmatched DPI settings (100%, 125%, 150%, etc.). If you use ppInk on a computer with multiple displays of unmatched DPI settings, or you encounter problems such as incorrect snapshot position, unable to drag toolbar to locations etc., please do the following as a workaround (in Windows 10 version 1903 as an example): right-click ppInk.exe, Properties, Compatibility, Change high DPI settings, Enable override high DPI scaling behavior scaling performed by: Application.

   Can you reproduce the problem when clicking on icon in the toolbar? Is the problem occuring everytime you are pressing Z 3times ? Pressing 3 times Z engages spot mode(see below), as an alternative you can enter this mode temporalily pressing Alt

b) depressing Z multiple times allows you to select between the 3 tools behind the Zoom button: 
no zoom -> dynamic zoom (as you have shown 2nd snapshot) -> 'static' zoom (where you select the area you want to anonate in enlarged mode ; when in enlarged pressing Z will exit the enlarged is return to no zoom ) -> spot mode -> no zoom

c) the dynamic zoom window parameters are defined in the option dialog / first page but you can also use the mousewheel dynamically

d) the issue of the offset between the mouse and the center of the zoomed area is most certainly due to the non application of the tip for multiple screen

**Comment by Heart1010** [comment]
I extracted the ppInk version also here and compared the default ppInk config with my ppinkS config file and found that strange value in there. I changed it to '10' - this fixed the crash mentioned above 👍 

![image](https://user-images.githubusercontent.com/1481680/188282716-6912ff5f-8622-4c1e-84a2-ad17beee6bd9.png)

About the dynamic zoom: I started ppInk and there this zoom is perfect - mouse pointer is the middle of the zoom.
But not with ppinkS - here I still have that problem mentioned above. What I also saw is the behaviour is different wheter the dynamic zoom is shown above or below mouse pointer. (red circle = mouse pointer position)

![image](https://user-images.githubusercontent.com/1481680/188282789-0c90de5e-e56a-4d5c-8b16-dcac923b649e.png)

![image](https://user-images.githubusercontent.com/1481680/188282793-ff6f1333-5cf0-42ab-b4f0-fb062bc70546.png)

**Comment by Heart1010** [comment]
Ok - I found the issue! I don't have multiple monitors but a laptop (which have 125% as dpi setting) - and after I did your mentioned workaround - everything works now! 👍 

_(I must have done that already on the ppInk.exe shortcut and missed it on the ppinkS shortcut)_

```right-click ppInk.exe, Properties, Compatibility, Change high DPI settings, Enable override high DPI scaling behavior scaling
performed by: Application.```

**Comment by Heart1010** [comment]
I reopen this one because I did some changes in the options dialog a few times and then I had this crash with zoom again.
I checked the config.ini and now it was `Spot_Radius= 99609375.9765625` in it!? I can't change that radius in the option dialog UI, can I?! So something else must be changing this value all the time.... hmm..

**Comment by pubpub-zz** [comment]
can you try with this version:
[spotIssue.zip](https://github.com/pubpub-zz/ppInk/files/9483215/spotIssue.zip)

**Comment by pubpub-zz** [comment]
Also a question : Why do you prefer ppInkS to ppInk ?

**Comment by Heart1010** [comment]
> Also a question : Why do you prefer ppInkS to ppInk ?

ppInkS is without Rest API, correct? I thought I don't need that API and so I take 'the smaller/thinner' version. Not correct ;) ?

**Comment by pubpub-zz** [comment]
ppInkS was built to ease to get through some IT firewalls/security rules. that's all. Apparently in your case you can use both 😊

**Comment by Heart1010** [comment]
Did some option changes and save to files... until now the spot radius stays at ~10 

What I see in some other numbers, e.g. this one... default is `2171.4375422747` but this always goes to `21714375422747`
![image](https://user-images.githubusercontent.com/1481680/188285399-27bb2d06-ce93-4bb4-a8f5-413883d8dfff.png)

Or the spot radius - when I set 10 in the config.ini file and start ppInk and then go into options and save to files this becomes
![image](https://user-images.githubusercontent.com/1481680/188285440-47d4618e-60ba-4f99-b653-256817846930.png)

**Comment by pubpub-zz** [comment]
> What I see with some other numbers, e.g. this one... default is `2171.4375422747` but this always goes to `21714375422747` ![image](https://user-images.githubusercontent.com/1481680/188285399-27bb2d06-ce93-4bb4-a8f5-413883d8dfff.png)

did you get this with the new version ? how ?

**Comment by pubpub-zz** [comment]
FYI, the rounding to 9.96 is normal : it is due to some "internal rounding"

**Comment by Heart1010** [comment]
> > What I see with some other numbers, e.g. this one... default is `2171.4375422747` but this always goes to `21714375422747` ![image](https://user-images.githubusercontent.com/1481680/188285399-27bb2d06-ce93-4bb4-a8f5-413883d8dfff.png)
> 
> did you get this with the new version ? how ?

with the test version the `2171.4375422747` in the config.ini goes to `2171,4375422747` 
![image](https://user-images.githubusercontent.com/1481680/188287771-aafddab6-eb59-4f06-b9d4-a6d0a642efb9.png)

and now it happened again... spot radius became
![image](https://user-images.githubusercontent.com/1481680/188287802-548a283c-f9a4-450d-9e52-bf1d3d98cdae.png)

**Comment by pubpub-zz** [comment]
I've added a messagebox showing the elements of the calculation when you are "saving to files";
![image](https://user-images.githubusercontent.com/4083478/188304027-4de64a26-8b03-4063-acc7-f8c74b6129c9.png)
(capture to clipboard the dialog with alt+printscreen)
the calculation (of the written data) consists in computing the ratio in % of spot radius / primary_screen_width.

I'm expecting the spot radius is only modified at parameters loading at init, and through the option dialog.
Saving regularly the params can you try to identify what is leading to incorrect value ( I did not managed on my side)

new test version
[spotIssue2.zip](https://github.com/pubpub-zz/ppInk/files/9484318/spotIssue2.zip)

**Comment by Heart1010** [comment]
Did a few saves and got always this until now
![image](https://user-images.githubusercontent.com/1481680/188309620-e8364334-f3f4-471c-bdf6-e36cd43f1ce5.png)

P.S.:  `2171.4375422747` goes to to `21714375422747` after the first save to files click.

**Comment by pubpub-zz** [comment]
Sorry, I missed something about the writing of parameters for the imagestamps. This version is fixing this.
[spotIssue3.zip](https://github.com/pubpub-zz/ppInk/files/9484528/spotIssue3.zip)

I'm really focused on your issue with the spot mode...

**Comment by Heart1010** [comment]
Another few saves later... (with new test version) Spot_Radius stays at 9.9609375 - which is good when I'm right? ;-)
P.S.: imagestamps value also stays at 2171.4375... now!

**Comment by pubpub-zz** [comment]
> Another few saves later... (with new test version) Spot_Radius stays at 9.9609375 - which is good when I'm right? ;-)

Yes this is normal. numbers greater than 100 are abnormals

**Comment by pubpub-zz** [comment]
@Heart1010, Have you been able to reproduce the crash ? can I consider the fixes of the beta version OK ?

**Comment by pubpub-zz** [comment]
+1 ?

**Comment by Heart1010** [comment]
> @Heart1010, Have you been able to reproduce the crash ? can I consider the fixes of the beta version OK ?

sorry was on vacation.... spotIssue3.zip is still the latest? I just got this after I clicked 'save to file' (ppInkS) and also the exception error like shown in first post above
![image](https://user-images.githubusercontent.com/1481680/192059862-86e03e65-c424-44bf-ac03-74d352e352b7.png)

But after that I exited ppInkS (changed Spot_Radius in config.ini manually to 10 again), started ppInkS again and now it works again.... save to file is ok and also pressing 3 times 'Z' don't produce the exception.

So because the first test showed all the problems again I can not say it's fixed 100%, hmm

**Comment by pubpub-zz** [comment]
Hi @Heart1010,
I may have found the problem. The instrumentation is the same, can you tell me if it is better:

[spotIssue4.zip](https://github.com/pubpub-zz/ppInk/files/9741899/spotIssue4.zip)

**Comment by Heart1010** [comment]
Hi @pubpub-zz,

- I did several attemps pressing 3x 'Z' => no crash 👍 
- also several 'save to file' clicks - always got this (which also looks good)

![image](https://user-images.githubusercontent.com/1481680/195717331-37059d64-54ad-4bd0-bb63-fc84b9b13e93.png)
