### ISSUE TITLE
Toolbar height not saved on different decimal delimitor: 1,23 vs 1.23

### ISSUE THREAD

**Issue by AntonyGarand** [pubpub-zz/ppInk#20]
On a machine with a different decimal notation, `1.23` instead of `1,23`, the localized notation is used when saving the value to the config file, making the value invalid when the program attempts using it.

![image](https://user-images.githubusercontent.com/9059487/95684971-f3655f00-0bc2-11eb-9d7a-80cba8736ad5.png)
![image](https://user-images.githubusercontent.com/9059487/95684987-17c13b80-0bc3-11eb-8987-b75a656770c9.png)

As `0,03` isn't a valid when loading the config, ppInk will revert to the default value of `0.06`, making this unusable via the GUI.
Even if it's modified via the config file manually, every time you persist the changes from the GUI, it will be overwritten.

I would recommend either ensuring both formats are properly saved regardless of the entered text (Aka. converting `1,23` to `1.23`), or supporting loading both formats when loading the config (Replacing `,` with `.`? Not sure if there are other conversions to be done)

**Comment by pubpub-zz** [comment]
thanks for this report,
commas are used to separate some data so I can not simultaneously , and . as decimal separator
I did my best using 'NumberStyles.AllowDecimalPoint' on all loadings and  '.ToString(CultureInfo.InvariantCulture)' but I did missed the one for toolbar_height.tell me if it is better with this later commit.

**Comment by AntonyGarand** [comment]
Can you send me a compiled version, or release one of them?
I can't compile the project on my PC at the moment, so I can't test it out :/

**Comment by AntonyGarand** [comment]
Fixed with https://github.com/pubpub-zz/ppInk/issues/21#issuecomment-707508019
