### ISSUE TITLE
Toolbar position in dual screen setup

### ISSUE THREAD

**Issue by CfKu** [pubpub-zz/ppInk#201]
Hi

I usually work with two monitors. If I switch from two to one monitors vice verse, ppInk does not store its position relative to the main screen, so it shows up somewhere on the screen (new main screen). It would be nice, if ppInk would store its position relative to the taskbar (e.g. bottom right corner) of the main screen (btw gInk does that)

Regards
CfK

**Comment by pubpub-zz** [comment]
have you apply the tip below (extracted from the readme.md)?:

>    There is a known issue for multiple displays of unmatched DPI settings (100%, 125%, 150%, etc.). If you use ppInk on a computer with multiple displays of unmatched DPI settings, or you encounter problems such as incorrect snapshot position, unable to drag toolbar to locations etc., please do the following as a workaround (in Windows 10 version 1903 as an example): right-click ppInk.exe, Properties, Compatibility, Change high DPI settings, Enable override high DPI scaling behavior scaling performed by: Application.

**Comment by CfKu** [comment]
Hi, I did not see the Section in the Readme. This fixed my problem. Thanks!
