### ISSUE TITLE
Error while using Arrows

### ISSUE THREAD

**Issue by mmc-terraform** [pubpub-zz/ppInk#203]
There was this error when I tired to use the arrow tool. It came once and when I restarted, the issue wasn't there. 

![image](https://user-images.githubusercontent.com/79689065/189516250-978b3e6c-3f64-4f1c-8519-3130b9465a6f.png)

**Comment by pubpub-zz** [comment]
Can you provide more details:
* are you using multiple screen. If so, can you confirm you applied the tip/fix at the bottom of the page https://github.com/pubpub-zz/ppInk 
* Have you been been able to identify which ends is inducing the problem. Is it a modified one?

**Comment by mmc-terraform** [comment]
Yeah, using multiple monitors. The fix was applied. I haven't modified any arrows. And this issue hadn't shown up after that. Guess it's a one-off situation.

**Comment by pubpub-zz** [comment]
I will close it for now then but thanks for noticing

**Comment by mmc-terraform** [comment]
Hi Pubpub-zz, 

Thanks for all the hard work. 

I could recreate this issue. This error appears if I create multiple arrows in quick succession. If I do so slowly, then there is no issue.

**Comment by pubpub-zz** [comment]
I did a change to prevent the exception: 
[ppInkArw.zip](https://github.com/pubpub-zz/ppInk/files/9584598/ppInkArw.zip)

Should be OK now. 
note : this version includes a popup when you save change in the options. Do not worry about it

**Comment by pubpub-zz** [comment]
@mmc-terraform,
any feedback ?

**Comment by pubpub-zz** [comment]
@mmc-terraform
any feedback ?

**Comment by pubpub-zz** [comment]
@mmc-terraform 
+1 ?

**Comment by pubpub-zz** [comment]
without feedback I close this issue as solved. feel free to add a new comment to reopen it
