### ISSUE TITLE
Text tool should allow immediatly input text

### ISSUE THREAD

**Issue by garawaa** [pubpub-zz/ppInk#208]
Only text tool is very annoying. just allow enter some text. why it shows every time certain dialog???

**Comment by pubpub-zz** [comment]
The development of an inline editor with text selection cursor display,... is a hudge work. this was a subject already addressed in #192.
I don't have enough time to work on this. If you want to propose a PR, it will be welcomed
I will close this issue as duplicate you can carry on the other issue
