### ISSUE TITLE
Add option to not auto-collapse toolbar when selecting cursor

### ISSUE THREAD

**Issue by dcorks** [pubpub-zz/ppInk#209]
I'd like to request an option to not have the tool auto-collapse when selecting the cursor.

My use case: Giving lectures using Powerpoint, Google Slides, etc.
I write on one slide, then need to select the cursor so I can click to advance to the next slide, then go back to writing.
With the auto-collapse behaviour, I have to do an extra action to un-collapse the toolbar before I can click on the pen to begin writing again.

Not auto-collapsing is the default behaviour in Epic Pen, gInk, the Zoom annotation toolbar, etc. Auto-collapsing is a nice feature to have for many people, I'm sure, but it'd also be nice to have to option to disable it.

**Comment by pubpub-zz** [comment]
sounds not too complex and quite generic. will try to implement that. 
However you may have a more useful feature alreay embedded : If you select Window mode you can limit ppInk to one screen, or also leave a small band/area that will not be covered by ppInk and just clicking there you will be able to change slide without going into pointer mode.
Try this second option and give me your feedback

**Comment by dcorks** [comment]
I had no idea about the window mode. It's another useful feature, but it doesn't seem to address the core problem. When I click outside the window I've created (to advance to the next slide), the toolbar automatically collapses. I guess it does that whenever the program loses focus, not just when the cursor is selected.

A related issue for people who use this while presenting slides:
When clicking on the ppInk toolbar and giving ppInk focus, in Windows 10 the taskbar appears on top of the slides (despite the slides staying in fullscreen).
This is a bit unusual. Normally:
- If I alt-tab to another program while I have a presentation (or YouTube) running in fullscreen, then the toolbar appears over the slides / video.
- If I click on another program (on a second monitor, for instance) while I have a presentation running in fullscreen, then the taskbar doesn't appear.
It would be amazing if clicking on the toolbar didn't make the taskbar appear over fullscreen applications. gInk has the same behaviour.
Interestingly, with Epic Pen clicking on the inking toolbar doesn't make the taskbar appear over the slides. I wish I knew more about their implementation to know why there's a difference.
I dislike almost everything about Epic Pen, but this one feature of theirs is key for people like me who need a way to write on top of slides. Having the taskbar often or always visible reduces usable screenspace and looks quite unprofessional when giving formal presentations.

**Comment by pubpub-zz** [comment]
> I had no idea about the window mode. It's another useful feature, but it doesn't seem to address the core problem. When I click outside the window I've created (to advance to the next slide), the toolbar automatically collapses. I guess it does that whenever the program loses focus, not just when the cursor is selected.

This is most probably because you left the checkbox to engage point with alt+tab/loosing focus

Any way can you try this version:
[ppInk PointerUnfolded.zip](https://github.com/pubpub-zz/ppInk/files/9592490/ppInk.PointerUnfolded.zip)

**Comment by dcorks** [comment]
> Any way can you try this version:
> [ppInk PointerUnfolded.zip](https://github.com/pubpub-zz/ppInk/files/9592490/ppInk.PointerUnfolded.zip)

That works really well, thanks!

Do you mind if I make a few other suggestions? I might try to make pull requests directly, but I find GitHub a bit confusing still and I've never worked with C# before.

**Comment by pubpub-zz** [comment]
Happy you are enjoying ppInk and would like to contribute.
Do no hesitate to star the project 😊

**Comment by pubpub-zz** [comment]
BTW, the version of visual studio used to development is Visual Studio 2017.

**Comment by pubpub-zz** [comment]
I close this issue. Feel free to come back if you have some questions
