### ISSUE TITLE
Insallation unsuccessful

### ISSUE THREAD

**Issue by BlackBaron3** [pubpub-zz/ppInk#210]
Hi all,
I am not a programmer and I have been trying to install the tool.
I downloaded the ppInk zip and started to run the ppInk.exe but I got this error.
ow to solve it_ Also, could you create a README file so is clearer on what must be done_

Thanks

---------------------------
UnhandledException
---------------------------
UnhandledException

version 1.8.3.19170 built on 15/08/2022 10:38

Oops, ppInk crashed! Please include the following information if you plan to contact the developers:

Object reference not set to an instance of an object.

Stack Trace:

   at gInk.ImageLister.Initialize()

   at gInk.ImageLister..ctor(Root rt)

   at gInk.FormCollection..ctor(Root root)

   at gInk.Root..ctor()

   at gInk.Program.Main()

!!! Do you want to Quit ?
---------------------------
Yes   No   
---------------------------

**Comment by pubpub-zz** [comment]
you need to unzip the full folder and then run ppink

**Comment by BlackBaron3** [comment]
Thanks, solved!
