### ISSUE TITLE
Error when using the screenshot/photo icon

### ISSUE THREAD

**Issue by BlackBaron3** [pubpub-zz/ppInk#211]
Hi all,

I tried using the screenshot/photo icon, I get the below error.

I have extracted the exe folder in this path D:\Users\solam\Desktop\Download 2\ppInk
so I am not sure why it is looking for a file in 'C:\Users\stefa/Pictures/gInk/' with also these wrong slashes

Any help?

---------------------------
UIThreadException
---------------------------
UIThreadException

version 1.8.3.19170 built on 15/08/2022 10:38

Oops, ppInk crashed! Please include the following information if you plan to contact the developers (a copy of the following information is stored in crash.txt in the application folder):

Could not find file 'C:\Users\stefa/Pictures/gInk/'.

Stack Trace:

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)

   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)

   at gInk.FormDisplay.SnapShot(Rectangle rect, String dest) in E:\ppink.src\ppInk\src\FormDisplay.cs:line 823

   at gInk.FormDisplay.timer1_Tick(Object sender, EventArgs e) in E:\ppink.src\ppInk\src\FormDisplay.cs:line 1240

   at System.Windows.Forms.Timer.OnTick(EventArgs e)

   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

!!! Do you want to Quit ?
---------------------------
Yes   No   
---------------------------

**Comment by pubpub-zz** [comment]
Your destination folder does not exist and can not be created.
2 options: 
* create the folder c:\Users\Stefa\Pictures\gInk
* Else right click on the ppink **in the taskbar on right next to the clock** open "options...", and select the folder where the images will be saved using this button 
![image](https://user-images.githubusercontent.com/4083478/193470399-9481f0c8-faee-47b0-85cc-01088cc068af.png)

**Comment by pubpub-zz** [comment]
@BlackBaron3 
is it OK ?

**Comment by BlackBaron3** [comment]
Hi,

I tried right clicking the icon near the clock that opens after I click the exe shortcut, but when I do no window opens

![image](https://user-images.githubusercontent.com/109722443/193809684-efa7ec63-62c7-4924-95a8-61a2e5bfd69c.png)

I also tried right clicking the shortcut but no 'propoerties' appeared

**Comment by pubpub-zz** [comment]
The properties is in the icon within the  task bar:
![image](https://user-images.githubusercontent.com/4083478/193874998-531ff743-791a-40d7-b8ca-d664507fed96.png)

What you are showing is the floating bar (which can be moved with a right-click drag to move)  and which is opening the toolbar when clicking on it

**Comment by BlackBaron3** [comment]
Thanks, solved!

**Comment by pubpub-zz** [comment]
Good
