### ISSUE TITLE
Is pplink  compatible with Wacom CTL-6100 device?

### ISSUE THREAD

**Issue by jmc-123** [pubpub-zz/ppInk#212]
Great work !  

I have now one Wacom CTL-6100 touchpad at hand , but its driver file size  is too big and I hesitate to install it. 

I  have one idiot idea.   

Could I enjoy painting just with  the ppInk application and Wacom device without its driver?

**Comment by pubpub-zz** [comment]
Try it!
Using native drivers, you may not have the pen pressure capabilities but have the standard window capabilities

**Comment by jmc-123** [comment]
> Try it! Using native drivers, you may not have the pen pressure capabilities but have the standard window capabilities

Thanks. the ppink toolbar locates in the center of screen when launched.  I can not drag it to the bottom-right side even if check the dragging option in the setting.

**Comment by pubpub-zz** [comment]
> Thanks. the ppink toolbar locates in the center of screen when launched. I can not drag it to the bottom-right side even if check the dragging option in the setting.

If you mean the single icon "floating" window, you can drag it with the right click. Do not forget to save it (in the options,  on  the left column ) when the position will please you.

Do not hesitate to star the project if you like it 😊

**Comment by jmc-123** [comment]
> Try it! Using native drivers, you may not have the pen pressure capabilities but have the standard window capabilities

It is a pity. No magic.  I suspect  it has to install Wacom driver to make the ppink application working.

**Comment by pubpub-zz** [comment]
to erase the whole drawings, use the bin. But I do not understand "scrolling to the next page"?

**Comment by pubpub-zz** [comment]
@jmc-123 any update ?

**Comment by pubpub-zz** [comment]
without feedback I close this issue as solved. feel free to add a new comment to reopen it
