### ISSUE TITLE
Crash : UnhandledExpection

### ISSUE THREAD

**Issue by iincitr** [pubpub-zz/ppInk#216]
![image](https://user-images.githubusercontent.com/58163198/197529963-07be067c-5cb7-49b2-a8f7-9c61c42458ab.png)

**Comment by pubpub-zz** [comment]
can you please check that you've unzip the whole provided folder

**Comment by iincitr** [comment]
I tried 
PS C:\Users\Hp\Downloads> & 'C:\Program Files\7-Zip\7z' x .\ppInk.zip
but again same error

**Comment by pubpub-zz** [comment]
Can you : 
* indicate which windows you are using, 
* which CPU familly do you running on, 
* confirm that the lang subfolder is present in ppink and complete
* send back the config.ini from ppink folder

**Comment by iincitr** [comment]
I found pplnk v1.2.1
this version is running.
ppInk v1.2.1
Forked from gInk   (c) 2016-2020 Weizhi Nai
changes (c) 2002-2020 Pubpub-ZZ
Licensed under MIT
https://github.com/pubpub-zz/ppInk

Credits:
Some button icons are designed by Freepik.com.






But 1.8.3.0 not running

---------------------------
UnhandledException
---------------------------
UnhandledException



version 1.8.3.19170 built on 15/08/2022 10:38

Oops, ppInk crashed! Please include the following information if you plan to contact the developers:


Object reference not set to an instance of an object.



Stack Trace:

   at gInk.ImageLister.Initialize() in E:\ppink.src\ppInk\src\ImageLister.cs:line 48

   at gInk.ImageLister..ctor(Root rt) in E:\ppink.src\ppInk\src\ImageLister.cs:line 34

   at gInk.FormCollection..ctor(Root root) in E:\ppink.src\ppInk\src\FormCollection.cs:line 432

   at gInk.Root..ctor() in E:\ppink.src\ppInk\src\Root.cs:line 515

   at gInk.Program.Main() in E:\ppink.src\ppInk\src\Program.cs:line 76


indicate which windows you are using,   **** windows 11 

which CPU familly do you running on, **** Processor	Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz, 2400 Mhz, 2 Core(s), 4 Logical Processor(s)

confirm that the lang subfolder is present in ppink and complete

![image](https://user-images.githubusercontent.com/58163198/199326953-48d50518-1c3c-40e2-95b1-b94616330894.png)

send back the config.ini from ppink folder


[config.ini.txt](https://github.com/pubpub-zz/ppInk/files/9913635/config.ini.txt)

**Comment by pubpub-zz** [comment]
which exact version of windows are you using ?

**Comment by iincitr** [comment]
windows 11 pro Version	10.0.22000 Build 22000

**Comment by pubpub-zz** [comment]
Very odd...
Can you try with this version of config.ini
[config.ini.txt](https://github.com/pubpub-zz/ppInk/files/9913772/config.ini.txt)

**Comment by iincitr** [comment]
Nothing changed. :(

**Comment by pubpub-zz** [comment]
**working for me....** 😕
![image](https://user-images.githubusercontent.com/4083478/200036091-97c04c0e-2972-4712-be99-e777ad8a9d92.png)

is version 1.2.1 sufficient for you ?

**Comment by iincitr** [comment]
Ok
I am using 1.2.1 already
Thank you

4 Kas 2022 Cum, saat 20:18 tarihinde pubpub-zz ***@***.***>
şunu yazdı:
