### ISSUE TITLE
How to draw perfect horizontal or vertical lines with FREEHAND tool (H)?

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#223]
### Discussed in https://github.com/pubpub-zz/ppInk/discussions/221

<div type='discussions-op-text'>

<sup>Originally posted by **iberck** November 16, 2022</sup>
I am aware that using the line tool and pressing shift draws perfect horizontal/vertical lines.

Are there any way to draw perfect horizontal or vertical lines with freehand tool (H) ? 

</div>

**Comment by pubpub-zz** [comment]
@iberck , @Heart1010 
This should  be provide you with the new feature.
[ppink_Shift_fixClipboard.zip](https://github.com/pubpub-zz/ppInk/files/10034801/ppink_Shift_fixClipboard.zip)


I've also fixe the issue reported in #222. However I'm no more able to check that the issue reported is fixed have no regression in W10. Can you test it and report your result in #222  ?

**Comment by Heart1010** [comment]
I like 👍

**Comment by pubpub-zz** [comment]
@Heart1010 
have you been able to check the test displayed in the video in #222 ?

**Comment by iberck** [comment]
thank you very much, this improvement does the job !

**Comment by iberck** [comment]
> @iberck , @Heart1010 This should be provide you with the new feature. [ppink_Shift_fixClipboard.zip](https://github.com/pubpub-zz/ppInk/files/10034801/ppink_Shift_fixClipboard.zip)
> 
> I've also fixe the issue reported in #222. However I'm no more able to check that the issue reported is fixed have no regression in W10. Can you test it and report your result in #222 ?


thank you very much, this improvement does the job !

**Comment by iberck** [comment]
thank you very much, this improvement does the job !

**Comment by pubpub-zz** [comment]
> thank you very much, this improvement does the job !
@iberck 
have you been able to test #222 ?

**Comment by iberck** [comment]
I'm sorry, I have windows 10

**Comment by pubpub-zz** [comment]
> I'm sorry, I have windows 10
@iberck 
That's exactly What I'm looking for : can you run the test as shown on the video and confirm you have no error with this beta version?
