### ISSUE TITLE
Perfect horizontal(magnet to 0°,180°) and vertical (magnet to 90°,360°) lines with pplnk?

### ISSUE THREAD

**Issue by iberck** [pubpub-zz/ppInk#226]
One of the most useful tools I know to draw on the screen (in fact the one I currently use) is [demohelper](https://github.com/stefankueng/demohelper) because it allows you to draw/trace extremely quickly on the screen (in the style of another microsoft tool called [zoomit](https://learn.microsoft.com/en-us/sysinternals/downloads/zoomit).

In my day to day as a trader it is very important to combine freehand drawings with _perfect_ horizontal/vertical lines and straight lines. Demohelper helps me a lot to accomplish this task because:

1. By default (without pressing any keys) it allows you to draw freehand.
2. Holding shift allows you to draw perfect horizontal/vertical lines, i.e. if you draw a line and hold shift, the line sticks like a magnet to the nearest angle: 0°, 90°, 180 °, 360° in such a way that you don't have to worry about drawing the horizontal/vertical line exactly. For example, if you hold down the shift key and draw a straight line with an angle close to 0° the line will become a perfect horizontal line (0°), and if the line you draw has an angle close to 90 then it will become in a perfect vertical line (90°).
3. Pressing the ctrl key allows me to draw straight lines (without magnet as it happens with the shift key).

I attach [a video](https://www.evernote.com/shard/s258/sh/8c7d72cd-58b3-2c12-9853-e13980475b05/9d71c1772d586bc612ace7ea70c54f00) where I graphically show how demohelper works by keeping the different keys pressed. At the end of the video I add an example of the drawings I make every day (in black).

demohelper has some limitations that pplnk does not and it would be great to have this behavior. Is there a way to have this behavior in pplnk? It is the most important piece I need to fully migrate from drawing tool.

Thank you

**Comment by pubpub-zz** [comment]
@iberck 
can you check this version:
[ppInk_Shift_Ctrl_hand.zip](https://github.com/pubpub-zz/ppInk/files/10127529/ppInk_Shift_Ctrl_hand.zip)
the latest changes:
* Both ctrl and shift will activate line tool
* the magnetic effect is completely off if both ctrl and shift are pressed ; shift only will "magnet" angle; ctrl will "magnet" to strokes
* I've fixed a very specific angle calculation, the margin for the angles have been slightly increased

You should have the same behavion as the one you've demonstrated in your video

**Comment by pubpub-zz** [comment]
small bug found when the cursor was on the trigonometric side of the angle

**Comment by pubpub-zz** [comment]
> * Disable magnet mode:
>   It would be very useful disable magnetic mode, or change "ctrl+shift" key combination to just "ctrl". Another interesting option would be to change the behavior when the "ctrl" key is held down depending on whether the magnet effect (magnet icon on the bar) is active or not.
Ctrl has a behavior, and I dislike to change the behavior because of other setttings. What you can notice is that once the line has been started you can release ctrl and/or shift to use the magnet

> 
> * Stick to 45° or 90°:
>   Is there a possibility to change the "shift" mode for stick the line only to angles that are multiples of 45°? similar to how it works in evernote: https://www.evernote.com/l/AQLgUJ0lcixIpJMT9b_rStAxPOOmRjf4IfI/

You can change the angles in the options to adjust the angles to your will 😊

**Comment by iberck** [comment]
> 

Thank you, the angle inside options works perfectly.

Are there any way to change "ctrl+shift" keys for only "ctrl"?
thank you !!

**Comment by pubpub-zz** [comment]
No:Ctrl will activate magnetic to strokes and will have to many consequences in the rest of the program

**Comment by iberck** [comment]
> No:Ctrl will activate magnetic to strokes and will have to many consequences in the rest of the program
That is perfectly understandable.


However, it seems to me that there is a bug with the new change:
When you write freehand (H) and hold down the "ctrl" key, the lines continue to behave as if the magnet is active (even though it isn't), which it doesn't when using the line tool.

I attached a video with the behavior:
https://www.evernote.com/l/AQLgFOPhpkhGArcwb3D7uVurUryyp5mvnp4/

**Comment by pubpub-zz** [comment]
The  behavior seems normal for me: if you press ctrl in hand the line tool is engaged. When you click and drag, as the ctrl is hold down, you draw line with the magnet to stroke activated (this is overriding the magnet from the tool bar). If you want to prevent that, press ctrl+shift, which allow to enter line, but disable the magnet. as an alternative to use ctrl+shift, if you want to draw without magnet, as an alternative, you can press shift, click down, this will start drawing without magnet to stroke, release shift keeping mouse button down : magnet will not be active

**Comment by iberck** [comment]
> The behavior seems normal for me: if you press ctrl in hand the line tool is engaged. When you click and drag, as the ctrl is hold down, you draw line with the magnet to stroke activated (this is overriding the magnet from the tool bar). If you want to prevent that, press ctrl+shift, which allow to enter line, but disable the magnet. as an alternative to use ctrl+shift, if you want to draw without magnet, as an alternative, you can press shift, click down, this will start drawing without magnet to stroke, release shift keeping mouse button down : magnet will not be active

I understand your point and it is perfectly valid.

**Comment by iberck** [comment]
One question, is this feature planned to be integrated into the next version of pplnk? I would like to know to receive all the updates of the application?

**Comment by pubpub-zz** [comment]
The change has been committed and will be part of next official release.meanwhile you can use the latest beta

**Comment by iberck** [comment]
> The change has been committed and will be part of next official release.meanwhile you can use the latest beta

Thank you
