### ISSUE TITLE
The toolbar is not displayed when using the expansion screen

### ISSUE THREAD

**Issue by JlU-YOU** [pubpub-zz/ppInk#227]
As the title says, **the toolbar is not displayed when using the expansion screen**, but it can be used normally when switching to a screen. What is the reason?

**Comment by pubpub-zz** [comment]
Can you clarify what you mean about "expansion screen" and "switching to a screen", and also which toolbar you mean.
Without those information, what I could recommand is to go to options, toggle off and the on the checkbox "show floating window" : the floating icon will be reset to upper left corner. Also, you should unset  the "allow draggin toolbar"

**Comment by JlU-YOU** [comment]
The toolbar disappears when the laptop is connected to the portable monitor.However, when the portable monitor is disconnected from the computer, the toolbar can be found again.
![Snipaste_2022-11-21_22-15-51](https://user-images.githubusercontent.com/102222347/203078241-b5420305-e200-4103-8d3c-629e889c28a0.png)

**Comment by pubpub-zz** [comment]
The point is most likely due to the fact that the desktop area is changed when you are connecting the external screen. I would recommend you to uncheck "allow dragging toolbar" in the options, that way the toolbar position will be recomputed to stick to the primary screen border

**Comment by PeteCrowe** [comment]
I had this issue, and simply went into Display -> advanced display properties, turned on duplicate screens, then turned it off again. If you have issues with the toolbar not working on the extended display, there is a reference to this bug (Windows 10) in the readme file. Following that recommendation fixed the multi-display problems I was having.

**Comment by pubpub-zz** [comment]
without feedback I close this issue as solved. feel free to add a new comment to reopen it
