### ISSUE TITLE
Discrepancies with icons on toolbar

### ISSUE THREAD

**Issue by PeteCrowe** [pubpub-zz/ppInk#229]
Sorry to add to your workload...but maybe I'm just not understanding the Move | Copy | Scale | Rotate | Pan tool. The title of the tool seem to have nothing to do with what I can achieve with them. 

First, the MCSRP tool. 
![MCSRP graphic](https://user-images.githubusercontent.com/32828222/204676035-9283d4b7-caf2-40d9-b4f7-5b6951f7006f.gif)

While the tooltip lists 5 different actions, only 3 icons appear, all of which deal with moving items. There is no apparent Scale, Rotate or Pan functions.

The "ScaleRot" tool actually functions, allowing one to Scale and Rotate a graphic, but the tooltips read "Move one Stroke/Group" and "Copy one Stroke/Group"...the tooltips accidentally taken from the Move tool? Copy and paste can be our friend, until it isn't. :-)
![SR graphic](https://user-images.githubusercontent.com/32828222/204676914-0caadb21-5632-4b9b-944c-4ddad17dbe7c.gif)

**Comment by pubpub-zz** [comment]
Thanks for the report. 
the tools are (Move | Copy | Pan)  and  (Scale | Rotate).
This version fixes this (also includes the other fixes already committed)
[ppInk_hints.zip](https://github.com/pubpub-zz/ppInk/files/10149103/ppInk_hints.zip)

**Comment by pubpub-zz** [comment]
@PeteCrowe 
Can we consider this as closed ?

**Comment by PeteCrowe** [comment]
My apologies for not responding sooner. There are still issues, some related to the tooltips, others that I've newly discovered, but still relevant to the Move | Copy | Pan (**P**) and Scale | Rotate (**S**) tools.

When in the Scale | Rotate tool, with the two tool fly-out displayed, the ToolTips over the Scale and Rotate tool are incorrect, displaying the tool tips from the P tool instead of the S tool (see image). In addition, if I have that tool fly-out displayed from the S tool, and I want to change tools, say doing a mouse click on the P tool, the tool pop-out does not change to reflect the change of tool. Clicking the P tool still displays the S tool pop-out. This only applies to the P and S tools. If I have the S tool fly-out displayed, and I attempt to click on the Rectangle (R) tool, the fly-out NOW updates and displays all the variations of the R tool.

Thank you! Happy Holidays.

![screencap](https://user-images.githubusercontent.com/32828222/208967881-e0d5ba51-51eb-4917-9434-0e80fcfeefa1.jpg)

**Comment by pubpub-zz** [comment]
a copy/paste error : should be good
[ppInk fix ScaleRot Hint.zip](https://github.com/pubpub-zz/ppInk/files/10280368/ppInk.fix.ScaleRot.Hint.zip)

Note : this beta also includes a new feature "Extra Pens"

**Comment by PeteCrowe** [comment]
All of the tool tip and flyout issues have been resolved. But now, there is a blank space under the custom pens (I use my menu vertically). Also, I can't access the options dialog anymore. Right clicking brings up a drawing tool and results in pen marks.
![ppInk new toolbar](https://user-images.githubusercontent.com/32828222/209573903-0bc32805-163e-4465-b4c5-74c838074c36.png)

**Comment by pubpub-zz** [comment]
The extrapens option was not implemented correctly with vertical toolbar
[ppInk extraPens Vert.zip](https://github.com/pubpub-zz/ppInk/files/10309639/ppInk.extraPens.Vert.zip)

**Comment by PeteCrowe** [comment]
This now works and the original bug can be closed. Many thanks for your diligence and hard work.
