### ISSUE TITLE
Can we customize the size of the pen-tip mouse cursor?

### ISSUE THREAD

**Issue by captainshan** [pubpub-zz/ppInk#23]
Can we customize the size of the pen-tip mouse cursor? The default arrow is too large. Can I scale this icon, or customize the icon?

**Comment by pubpub-zz** [comment]
this feature is not yet implemented. I will finish some development and will implement that just after

**Comment by captainshan** [comment]
I'm very glad to hear that and look forward to this feature. Thank you very much.

**Comment by pubpub-zz** [comment]
Find this version for evaluation. You just have to change the cursor icon(cursor.ico) but also you can customize the floating window image (FloatingCall.png)
the file image size is taken into account to resize the cursor.ico. for the floating window size, you have to modify it in config.ini

[ppInk cursor custom.zip](https://github.com/pubpub-zz/ppInk/files/5475045/ppInk.cursor.custom.zip)

**Comment by captainshan** [comment]
In this version, if you set the CLEAR shortcut to ALT+D, pressing the shortcut will crash the software.

**Comment by pubpub-zz** [comment]
Hi,
I'm still working in this version on a new feature which may have some side effects. I've fixed the bug you've raised.
[ppInk cursor custom2.zip](https://github.com/pubpub-zz/ppInk/files/5481245/ppInk.cursor.custom2.zip)

**Comment by captainshan** [comment]
That's very kind of you. Thank you very much!

**Comment by pubpub-zz** [comment]
can you give me your feed back. is it usable that way?

**Comment by captainshan** [comment]
This version works. However, there were some problems running the software today on another computer (OS: windows7).
![1](https://user-images.githubusercontent.com/73658570/98261517-82497980-1fbf-11eb-8051-5541db109be2.PNG)
![2](https://user-images.githubusercontent.com/73658570/98261560-8c6b7800-1fbf-11eb-8062-d54983c6b04c.PNG)

**Comment by pubpub-zz** [comment]
can you provide the crash file and more details on context and actions when the exceptions were raised

**Comment by captainshan** [comment]
Sorry, I only use that computer twice a week, so I can't provide crash files now.
On that computer, after double-clicking the PPLNK, just click the g icon in the lower right corner and the dialog box mentioned above will appear.

**Comment by pubpub-zz** [comment]
I've tried the zipped program I've sent you in a microsoft win7 test VM. no error were reported.
