### ISSUE TITLE
[Feature] A Light Version

### ISSUE THREAD

**Issue by earthjasonlin** [pubpub-zz/ppInk#230]
Hi, I'm changing from gInk to ppInk. However, the settings are a bit too complicated. Could you please release a light version which removes something like OBS, or maybe just make the default config contains less functions such as magnet and clip images

**Comment by iberck** [comment]
It would be an interesting option if the default application had a reduced toolbar (similar to epicpen), and that the application settings were divided into basic and advanced options.

**Comment by earthjasonlin** [comment]
[config.ini.txt](https://github.com/pubpub-zz/ppInk/files/10159104/config.ini.txt)
For me, I think this will work.

**Comment by iberck** [comment]
I hadn't thought about it, but it would probably be an excellent alternative to have a light version or for the same default application to have advanced features that are inactive.

It would be interesting if by default the toolbar only showed the basic drawing tools (similar to the one in epicpen).

**Comment by pubpub-zz** [comment]
I've reviewed the config.ini provided by @earthjasonlin  and this config may not be convenient to everyone.

First I've produced a mod that allow to complete the inifile from one release to another:
[ppInk Disable Magnet.zip](https://github.com/pubpub-zz/ppInk/files/10178991/ppInk.Disable.Magnet.zip)
you just replace the config.ini with your file and the new entries will be loaded from the defaults.ini

Second, I've prepared a folder for extra_doc where we can put: https://github.com/pubpub-zz/ppInk/tree/master/extra_doc
can you create a PR with an md file describing your configuration with some pictures, and a link to your config.ini

Users will have full capability to select the inifile they would prefer

**Comment by pubpub-zz** [comment]
final merge/publication through #242
