### ISSUE TITLE
can we have the "load as" and "save as" as actual shortcuts? the holding is a little clunky

### ISSUE THREAD

**Issue by waerdrwsreadgtfserdfyghb** [pubpub-zz/ppInk#233]

**Comment by pubpub-zz** [comment]
Adding new shortcut in the toolbar is too specific for to be proposed as a change. However, you may use the REST API which will allow you to map a keyboard shortkey to it (build a program shortcut (eg: `curl https://localhost:7999/LoadStrokes?F=- ` ), and then add a keyboard shortcut)
Do not hesitate to start the project to support it

**Comment by pubpub-zz** [comment]
can we close it ?

**Comment by pubpub-zz** [comment]
I've just thought : there is another solution : the long click can be replaced with a right click.
