### ISSUE TITLE
[REQUEST] Ability to change/disable outline color for selection/panning

### ISSUE THREAD

**Issue by NOVAinc** [pubpub-zz/ppInk#236]
I'm back! It's been a while, but I've been slowly integrating a lot of the very extensive functionality from the tool into my workflow! One thing I've noticed which I'd like to have some more control over is the color of the dashed outline when using the select/pan tools. When I color key the black background within OBS this is always left out, and the drop shadow filter I use for making the stickers separate from the rest of the screen looks funky when combined with this outline.

Would it be possible to make it so we can change the outline color or disable it outright? If we had the option to disable the outline, perhaps we could instead "highlight" the affected item instead.

![image](https://user-images.githubusercontent.com/19545604/208005584-9b3f667d-66e2-4105-bbdd-40cb7034efe7.png)
Example of outline

**Comment by pubpub-zz** [comment]
Welcome back, can you provide the original file to see what I can do ?

**Comment by NOVAinc** [comment]
You should see it with any clipart.
1. Insert a clipart
2. Select the panning tool (P)
3. Hover with the cursor close to the clipart's corner
4. The red outline is displayed

[orange face example.strokes.txt](https://github.com/pubpub-zz/ppInk/files/10247615/orange.face.example.strokes.txt)
Here's an example regardless, using the orange smiley which is the only generic one I have.

**Comment by pubpub-zz** [comment]
I read too quickly, and I did not under your request 🤭😳
adding an entry  "Selection_Color" for this is easy in the configuration file. However, I will not add it to config dialog (use too limited)
In this beta release I've set alpha to 0 (invisible) but in official release I will configure it back to full red
[ppInk custom selection color.zip](https://github.com/pubpub-zz/ppInk/files/10258646/ppInk.custom.selection.color.zip)

**Comment by NOVAinc** [comment]
It works really well, thanks! It is fine to have it as a config option only, as well. So long as it's possible to configure it's amazing!

**Comment by pubpub-zz** [comment]
> It works really well, thanks! It is fine to have it as a config option only, as well. So long as it's possible to configure it's amazing!
> 
> Edit: It worked well on the first try, but I've noticed a few more issues with more testing.
> 
>     1. The UI seems to be drawing further to the right than it should
>        ![image](https://user-images.githubusercontent.com/19545604/208550256-66882774-847f-4a1c-b2de-385f0abda9f3.png)

This is a side effect due to the mod I'm working on (adding extra pens)

> 
>     2. I tried migrating my config/hotkeys/pen files from the previous version I was using, and I started getting UI exceptions. Here are the logs
>        [crash.txt](https://github.com/pubpub-zz/ppInk/files/10263559/crash.txt)

at first sight. I would say it is a side effect of the same mod. The beta I've delivered was still quite unstable. Try this new release (see below)

> I understand the new config file has a new option in it, so my guess is that it doesn't update an older config file version, right? If this is the case, then I have to check the fields and values for the new version and match them to the older version by hand. I should probably wait for a new release before migrating those things perhaps, in special if there will be more testing

A new capability allow you to save your legacy config.ini file : the extra inputs will be captured from the default.ini. And when you will use the save buttons the  new entries will be added at the end of your config.ini ; I've just added also the same for pens.ini (defaults in pensdef.ini)

[ppInk extraPens.zip](https://github.com/pubpub-zz/ppInk/files/10267236/ppInk.extraPens.zip)

**Comment by NOVAinc** [comment]
@pubpub-zz this is now working as expected! Changing the selection color at the end of the config file works, even after importing my previous configs!
