### ISSUE TITLE
[BUG] Http server prompting for pattern specs even when providing them through urlencoded params

### ISSUE THREAD

**Issue by NOVAinc** [pubpub-zz/ppInk#237]
The following request should prompt ppink to summon the image "palisade-blue" with height and width of 50, and have it repeat on a stroke with a distance of 5 between instances.
![image](https://user-images.githubusercontent.com/19545604/207996978-47e48e6a-16b6-4fba-8b3c-bba8c7b4cc6d.png)

Instead, when receiving that request, I am presented with the yellow target icon and I need to manually set the size by dragging the cursor, as well as the distance by clicking a second time after the size has been established.

**Comment by pubpub-zz** [comment]
Your parameters w,h,d are in lower case. The URL decoding is case sensitive (use of standard function without case sensitivity flag). Can you confirm and close the PR. I will add a note in the readme page

**Comment by NOVAinc** [comment]
@pubpub-zz that did the trick, you were right. I had set up all my other requests with upper case, not sure why I used lowercase. Is there a particular reason why it's case-sensitive? Regardless, I've fixed my implementations and now everything works great

**Comment by pubpub-zz** [comment]
as said, the analysis relies on `TryGetValue` function which is case sensisive.
