### ISSUE TITLE
[FIX] httpRequest documentation typo

### ISSUE THREAD

**Issue by NOVAinc** [pubpub-zz/ppInk#239]
The httpRequests.rtf file has a typo in it whereby many times https is used instead of http. Thus, if you copy and paste the examples provided, they won't work. This version has that fixed

[httpRequests.zip](https://github.com/pubpub-zz/ppInk/files/10242067/httpRequests.zip)

**Comment by pubpub-zz** [comment]
+1?

**Comment by NOVAinc** [comment]
Hey pubpub-zz, sorry for the delayed response. I haven't used github on windows since my main OS is Linux, so I wouldn't want to delay any potential releases just for attribution. You had fixed it already, and I don't really mind the credit so it's all good for me if you just mark it as fixed :)
