### ISSUE TITLE
Toolbar height not loaded from config.ini

### ISSUE THREAD

**Issue by calfranca** [pubpub-zz/ppInk#24]
When changing toolbar height in options it is correctly saved to config.ini and applied but after restarting ppink it retakes its 6.0 points height default setting

**Comment by pubpub-zz** [comment]
this problem has been reported in #20, and fixed. a test version is available in https://github.com/pubpub-zz/ppInk/issues/21#issuecomment-707508019
I should release a new version soon

**Comment by calfranca** [comment]
ups, sorry.

Thank you very much for your work

**Comment by pubpub-zz** [comment]
version 1.3  is now issued
