### ISSUE TITLE
NEW : Add Extra Pens

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#240]
### Discussed in https://github.com/pubpub-zz/ppInk/discussions/235

<div type='discussions-op-text'>

<sup>Originally posted by **iberck** December 13, 2022</sup>
Similar to toggle Fading:

It would be very useful for my workflow to have "Toggle Alpha": a key combination that applies an alpha level to the current pen color (the alpha level would have to be predefined in the settings).

</div>

**Comment by pubpub-zz** [comment]
I've created a more generic feature where 10 extra pens are available. These can be activated through ctrl or shift pressed.
this works also for the selection ('1' = select pen 1, 'ctrl+1' or 'shift+1' selects
[ppInk extraPens.zip](https://github.com/pubpub-zz/ppInk/files/10267236/ppInk.extraPens.zip)

**Comment by iberck** [comment]
> 

Your idea is creative and very useful. With this change, for example, we could have a second color palette for a darkmode.

Unfortunately #226 no longer works because the same keys are used.
I think that another solution could be to use a key to activate or deactivate the second color palette. For example, pressing the P key would activate palette 2, and pressing the P key again would activate palette 1.

**Comment by pubpub-zz** [comment]
> Unfortunately #226 no longer works because the same keys are used. I think that another solution could be to use a key to activate or deactivate the second color palette. For example, pressing the P key would activate palette 2, and pressing the P key again would activate palette 1.

I do not see what you mean : It works for me : when you depress shift, the extra pens are displayed but you have to use the hotkeys or click on the pen to select, then you can release the shift key and the magnet works standard. similarly, you can use the 'direct' palette of pens and then use the shift key as before.

Can you provide a video with what you have observed.

**Comment by pubpub-zz** [comment]
extra Pens added in release 1.9
