### ISSUE TITLE
make it for ubuntu

### ISSUE THREAD

**Issue by iyagicom** [pubpub-zz/ppInk#243]
Ubuntu is the most used Linux on the desktop.
No need to create another Linux.
Please use Ubuntu only

If you make another Linux version, you can give up.

**Comment by pubpub-zz** [comment]
gInk / ppInk relies on windows API (some DLL are Microsoft directly copied (for configuration managment) and the code is not avaible)
However, you should be able to run it using wine. Can you you have a a try and give feed backs.

**Comment by pubpub-zz** [comment]
@iyagicom 
have you been able to test with wine ?

**Comment by iyagicom** [comment]
와인에서 전혀 작동하지 않는다
실행자체가 안된다.
인스톨러가 필요할수 있다

**Comment by pubpub-zz** [comment]
@iyagicom 
in english please ☺️

**Comment by pubpub-zz** [comment]
+1

**Comment by pubpub-zz** [comment]
I close this issue as no
