### ISSUE TITLE
no visible toolbar on Windows with multiple monitors

### ISSUE THREAD

**Issue by jianhuayang** [pubpub-zz/ppInk#244]
hi, 

I'm running the latest  release i.e. 1.8.3  both standard and S versions, and it doesn't seem to give the toolbar. The tray icon and the little logo icon (in the middle of the screen) are there. Any help is much appreciated.

**Comment by jianhuayang** [comment]
sorry, didn't read the last bit.

**Comment by pubpub-zz** [comment]
Do not hesitate to star it if you like it ☺️
