### ISSUE TITLE
Resizing cursor

### ISSUE THREAD

**Issue by cmhdream** [pubpub-zz/ppInk#248]
Why are there two zips and what's the difference?

Tip size can adjust size.
Arraw Need adjust size.

Because so big arraw.

**Comment by pubpub-zz** [comment]
ppinkS only removes from building the listening port for remote control (used for desk pads) in order to allow use when some ITSec rules block running

For the arrows, size adjustment was originally planned through resizing of the bitmaps.

**Comment by cmhdream** [comment]
> ppinkS only removes from building the listening port for remote control (used for desk pads) in order to allow use when some ITSec rules block running
> 
> For the arrows, size adjustment was originally planned through resizing of the bitmaps.

If you set TIPS to draw a small line setting, it is really not obvious.
If you set the arrow, it's a big one.

**Comment by pubpub-zz** [comment]
Sorry hard to guess as your cursor is not captured.
From my understanding what you can try:
If you are using a tool tip, you can quickly change to the arrow mode pressing down the alt key.
also if you want to change the "arrow" cursor( as said in https://github.com/pubpub-zz/ppInk/discussions/194)
you can replace the cursorarrow.ico with whatever you want. Some proposal where sent if #146

**Comment by cmhdream** [comment]
> Sorry hard to guess as your cursor is not captured. From my understanding what you can try: If you are using a tool tip, you can quickly change to the arrow mode pressing down the alt key. also if you want to change the "arrow" cursor( as said in #194) you can replace the cursorarrow.ico with whatever you want. Some proposal where sent if #146

Thanks. Already downloaded another .ico.

**Comment by pubpub-zz** [comment]
Is it ok?

**Comment by cmhdream** [comment]
> Is it ok?

OK. I like it.

**Comment by pubpub-zz** [comment]
nice, I've cleaned it up with gimp...
[cursorarrow.zip](https://github.com/pubpub-zz/ppInk/files/11070099/cursorarrow.zip)

**Comment by cmhdream** [comment]
Brush display of other drawing software
![expresii01](https://user-images.githubusercontent.com/24859526/227748906-dafe520e-4944-4812-8018-36c18412b971.jpg)
![expresii02](https://user-images.githubusercontent.com/24859526/227748907-15e8a3c4-2ed7-47c1-bc27-942b07282f62.jpg)
![expresii03](https://user-images.githubusercontent.com/24859526/227748908-42a2777e-5933-4602-a4b0-fd623c4bb384.jpg)
![FireAlpaca](https://user-images.githubusercontent.com/24859526/227748910-0b4f7426-dfb6-43ee-8c99-5fc29460c1a8.jpg)
![MediBangPaintPro](https://user-images.githubusercontent.com/24859526/227748911-9ac84f3b-c98d-42f6-a5b2-fc46e5cecfdc.jpg)

**Comment by cmhdream** [comment]
I made a version myself with size differences.
[AndyMaker.zip](https://github.com/pubpub-zz/ppInk/files/11073507/AndyMaker.zip)
![cursorarrow01](https://user-images.githubusercontent.com/24859526/227814549-168f3c78-ce32-4c9b-ba1e-ec1bffabb5cf.jpg)
![cursorarrow02](https://user-images.githubusercontent.com/24859526/227814551-ad1fa51d-4ece-49c4-8075-0be504b8e055.jpg)

**Comment by pubpub-zz** [comment]
released in 1.9
