### ISSUE TITLE
missing scale on width panel

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#251]
@cmhdream wrote:
> ![Form103-30_193300](https://user-images.githubusercontent.com/24859526/228831805-dcc9d55a-4f83-4b27-8f7f-dd45f87ead50.jpg)
> 
> The line thickness adjustment screen sometimes does not appear black.

I did no change around this panel and I'm not able to reproduce it.  I'm opening to track it
b) can you provide more details:
- is this new or was existing  before ?
- on your image, it looks like the bar is over 2 screens. Am I Correct ?
- When this occurs, does closing / reopening  fixes this ?
- can the width cursor moves as expected?
- normally the sub toolbar opens above the main toolbar : can you provide more details on the sequence of actions to come to your situation

_Originally posted by @pubpub-zz in https://github.com/pubpub-zz/ppInk/issues/249#issuecomment-1490690629_

**Comment by pubpub-zz** [comment]
I close this issue: the trouble about pen#0 has been solve

**Comment by cmhdream** [comment]
> @cmhdream wrote:
> 
> > ![Form103-30_193300](https://user-images.githubusercontent.com/24859526/228831805-dcc9d55a-4f83-4b27-8f7f-dd45f87ead50.jpg)
> > The line thickness adjustment screen sometimes does not appear black.
> 
> I did no change around this panel and I'm not able to reproduce it. I'm opening to track it b) can you provide more details:
> 
> * is this new or was existing  before ?
> * on your image, it looks like the bar is over 2 screens. Am I Correct ?
> * When this occurs, does closing / reopening  fixes this ?
> * can the width cursor moves as expected?
> * normally the sub toolbar opens above the main toolbar : can you provide more details on the sequence of actions to come to your situation

After saving the settings again, it is OK.
![Form103-31_064418](https://user-images.githubusercontent.com/24859526/228982509-dc1dd361-7255-4da8-9a63-de63937c8a03.jpg)

I found that the width panel did not follow the main panel after moving the main tool.
[mp4 video.zip](https://github.com/pubpub-zz/ppInk/files/11116820/mp4.video.zip)
