### ISSUE TITLE
scoop installation

### ISSUE THREAD

**Issue by andrearicci** [pubpub-zz/ppInk#254]
Ìd like to have it on a [scoop](https://scoop.sh/#/apps?s=0&d=1&o=true) or winget repository for easy upgrade

**Comment by pubpub-zz** [comment]
I'm not used to scoop. Feel free to propose the elements to build it

**Comment by andrearicci** [comment]
Hi, I'm not a programmer so I cannot really explain.  Looks just to create a json manifest?  
Here (under _Creating Packages_) are the instructions [https://scoop.sh/](https://scoop.sh/), to create a package but then I donnow how to put it on the repositories.
Thank you

**Comment by pubpub-zz** [comment]
I'm sorry but I don't have time to look at this.

Is any interested into developping this

**Comment by andrearicci** [comment]
ok thanks anyway

**Comment by pubpub-zz** [comment]
Nobody proposed a fix. I close this as not planned

**Comment by aliesbelik** [comment]
ScoopInstaller/Extras#17438

**Comment by pubpub-zz** [comment]
thanks for your work. I will add link  in the readme if some one needs reference

**Comment by andrearicci** [comment]
@aliesbelik thank you very much!
