### ISSUE TITLE
[enhancement ] stick annotations to underlaying view changes (scroll, pan and zoom)

### ISSUE THREAD

**Issue by andrearicci** [pubpub-zz/ppInk#255]
I guess this is not a simple one: 
it would be great to have the annotations move and scale sticking to the underlaying monitor's view changes as scrolling a web page, zooming and panning of a pdf/photoshop/autocad etcetera. Eventually disappearing when changing the window, and come back when activating the original window again. Eg I made my annotations on a pdf, then if I switch to the email they disappear, and when I go back to the pdf they're there again.
Thank you for the software.

**Comment by pubpub-zz** [comment]
ppInk has no information on information below : what you are asking is not possible. However, you can select all/part of your drawings and then move/rotate/rescale them as you wish
