### ISSUE TITLE
UIThreadException

### ISSUE THREAD

**Issue by iceloX** [pubpub-zz/ppInk#26]
UIThreadException
Oops, glnk crashed! Please include the following information if you planto contact the developers (a copy of the following information is storedin crash.txt in the application folder):
未将对象引用设置到对象的实例。
Stack Trace:
在glnk.FormDisplay.timer1_Tick(Object sender, EventArgs e)位置D:\gink.gitipplnkisrc\FormDisplay.cs:行号668
在System.Windows.Forms.Timer.OnTick(EventArgs e)在
System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message&m)
在System.Windows.Forms.Nativewindow.Callback(IntPtr hWnd, Int32msg, IntPtr wparam, IntPtr lparam)
!!! PLEASE PRESS ESC KEY TO EXIT IF YOU FEEL YOUR MOUSE CLICK ISBLOCKED BY SOMETHING

![image](https://user-images.githubusercontent.com/48974840/99177837-2c579d00-2748-11eb-837b-6ac7ef0db9b1.png)

**Comment by pubpub-zz** [comment]
Hi can you tell me which version you are using and what were the previous actions before the report

**Comment by iceloX** [comment]
I downloaded the latest version and when minimizing the app there is a problem like the one described in GitHub, I think that's all I know, hopefully that will help you solve the problem!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pubpub-zz/ppInk"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月15日(星期天) 晚上7:51
收件人:&nbsp;"pubpub-zz/ppInk"<ppInk@noreply.github.com&gt;;
抄送:&nbsp;"START"<2568450165@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pubpub-zz/ppInk] UIThreadException (#26)





 
Hi can you tell me which version you are using and what were the previous actions before the report

**Comment by pubpub-zz** [comment]
by minimizing you mean closing the toolbar? If yes, can you tell me if the window appeared when the toolbar was closing or closed?

Thx

**Comment by iceloX** [comment]
I remember the last time I used it, the software minimized to stay in the taskbar, and the main window is no longer open (opening it would appear on UIException) so I can't use it! (The one you see here uses a Chinese translation, my English is not very good, so there may be ambiguity) I hope you are doing well and await your good news!

**Comment by pubpub-zz** [comment]
This could be due to asynchronous tasks.
try this beta version;
[ppInk test.zip](https://github.com/pubpub-zz/ppInk/files/5548948/ppInk.test.zip)

**Comment by iceloX** [comment]
Okay, I'll give it a shot.

**Comment by pubpub-zz** [comment]
You've closed the issue. It means you're testing is positive?

**Comment by iceloX** [comment]
Yes, you have done a good job, and I hope to improve the Chinese translation of the software
