### ISSUE TITLE
Set x,y offset on clipart

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#269]
### Discussed in https://github.com/pubpub-zz/ppInk/discussions/268

<div type='discussions-op-text'>

<sup>Originally posted by **barathi-k** July 11, 2023</sup>
Is there a way we could set x,y offset (in percentage or in pixels) when creating clipart? What I see is the image's top left corner appears at the point where I click. 

If there is an offset parameter (on API) We could create something like a pointer clipart and make sure it points to the exact place where we click. 

(I could do something like this 😂)

![Comp 1_2](https://github.com/pubpub-zz/ppInk/assets/55287040/bd4f5535-5bb8-4430-af47-8ab4b1c05bd3)

</div>

**Comment by pubpub-zz** [comment]
I know ppInk is good for painting, but not sufficient to paint the sixtine ceiling🤣🤣🤣🤣
Here is my proposal :
[ppInk_offsetCliparts.zip](https://github.com/pubpub-zz/ppInk/files/12018083/ppInk_offsetCliparts.zip)

You just have to add at the end of the file name: @x.y 
eg. sixtine@2.124.png
![sixtine@2 124](https://github.com/pubpub-zz/ppInk/assets/4083478/8cde43c0-82f9-4fce-a1d8-e10267d7c24f)

Your png is better than mine and the idea wonderfull : can you share it?

**Comment by pubpub-zz** [comment]
new beta : this one allows rescaling (with drag and drop)
[ppInk_offsetCliparts2.zip](https://github.com/pubpub-zz/ppInk/files/12021266/ppInk_offsetCliparts2.zip)

**Comment by barathi-k** [comment]
I just took that image out of the internet. :) 

![Layer 2](https://github.com/pubpub-zz/ppInk/assets/55287040/4c1b29c9-8594-4090-955c-0c9329bf6c6b)

Can't thank you enough for this feature. Appreciate it.

**Comment by barathi-k** [comment]
[images.zip](https://github.com/pubpub-zz/ppInk/files/12027125/images.zip)
More images. :)

**Comment by pubpub-zz** [comment]
example added in 1.9 cliparts
