### ISSUE TITLE
Cannot save the settings, the previous settings cannot be saved after the second start of the software, which is very inconvenient.

### ISSUE THREAD

**Issue by iceloX** [pubpub-zz/ppInk#27]
Cannot save the settings, the previous settings cannot be saved after the second start of the software, which is very inconvenient.

**Comment by pubpub-zz** [comment]
Settings are saved through the button in option dialog box, 1st tab.
Can you please clarify which setting you've identified that is not respecting this rule

**Comment by pubpub-zz** [comment]
Hi @iceloX,
 just to reactive

**Comment by iceloX** [comment]
oh I’m sorry, I forgot about it. You’re right. It may be because of the incomplete translation. I didn’t find the save button. I want to apologize.

**Comment by pubpub-zz** [comment]
No problem
