### ISSUE TITLE
ppink is crashing on start giving error message 

### ISSUE THREAD

**Issue by ispyridis** [pubpub-zz/ppInk#280]
l work with two computers one DII precision and one Wacom mobile studio .
l can use ppink with the laptop having the pen computer connected as a secondary screen .

But when I want to use my pen computer alone ppink is not running giving the following error. While l can run gink

![image](https://github.com/pubpub-zz/ppInk/assets/123330714/7ff65914-1eba-4c2c-bf75-9cc395c19a5e)

![image](https://github.com/pubpub-zz/ppInk/assets/123330714/ce4cf51c-96cc-4197-b548-bf7296d1cd54)

**Comment by ozbayseckin** [comment]
yes, iam haveing same issue.

**Comment by pubpub-zz** [comment]
@ozbayseckin Parsing issues are fixed in 1.9 (under release)
