### ISSUE TITLE
Add ability to paste text and images 

### ISSUE THREAD

**Issue by ispyridis** [pubpub-zz/ppInk#281]
Hi it occured to me that I wanted to copy some text and some images while in mouse pointer mode and paste them as artifacts to the pen mode.
Can we have this feature ?

**Comment by pubpub-zz** [comment]
both paste images and text works : for text, the paste into the dialog area after creating text is working. The same you can create a new clipart directly from an image stored in the clipart.

**Comment by ispyridis** [comment]
Hi ι meant directly also drag and drop. I work with two monitors one is windowed to ppink. I'd like to be able just to paste clipboard on page or drag and drop. It is much faster and the workflow is much more fluid. Also this would work by switching to pointer mode copy something,  switch mode paste on page.  I really hope you take some time to complete this project. You have put so much detail in it.

**Comment by pubpub-zz** [comment]
This feature is complex and is not compatible with touchscreen. I will not spend time on this
