### ISSUE TITLE
Wrap text? 

### ISSUE THREAD

**Issue by ispyridis** [pubpub-zz/ppInk#282]
Hi is it possible to wrap text?
And if not could we get this option?

**Comment by pubpub-zz** [comment]
currently wrapping is not implemented. The text tool just looks for an insertion point. This will require to change it into a box selection and will make complex manual line return handling.

feel free to propose a PR

**Comment by ispyridis** [comment]
Recently l was looking at Mathomir 
There you click at the insertion point and paste text the text gets pasted unwrapped.
Then you select the text and on the right side of the bounding window, if you place the pointer over the right side of the selection box, the side becomes green . Dragging the side of the selection box wraps the text . so there is no option to select you just do it after placement .

**Comment by pubpub-zz** [comment]
I close this issue: I will personnally won't implement it  and there is no PR to do it
