### ISSUE TITLE
issue running ppInk from "C:\Program Files"

### ISSUE THREAD

**Issue by MichelReims** [pubpub-zz/ppInk#285]
When I create a Shortcut for pplnk on the desktop, pplnk fails

**Comment by pubpub-zz** [comment]
can you please provide the error message

**Comment by MichelReims** [comment]
I put "ppInk 1.8.3" in "C:\Program Files\" (Windows 11)
I create a shortcut on desktop. 
When I click on shortcut, I have the followed widows
![image](https://github.com/pubpub-zz/ppInk/assets/66552896/eefa25bd-12f9-4792-8a3d-391cc1def970)

**Comment by pubpub-zz** [comment]
The reason seems to be in the title : can you try to get the full text flying over the icon in the task bar at the bottom of the screen ?
Also can you confirm the program runs fine when you are running it straight from the folder ?

**Comment by MichelReims** [comment]
Yes, the program runs fine when you are running it straight from the folder.
The message in the box is : "Fatal non UI-Error. Coud not write the error to the event Log. Reason : L'accès au chemiin "C:\Program Files\pplink 1.8.3\crash.txt" est refusé"

**Comment by pubpub-zz** [comment]
First can you check that the working folder of the shortcut is c:\program files\ppink
if still not good, 
Changes the folder authorisations to allow to get more details

**Comment by MichelReims** [comment]
I find why this error : I can't put the "pplnk 1.8.3" directory in "c:\program files".
I put the "pplnk 1.8.3" directory at the root of C:\ and then the shortcut runs fine.
Thank very much for your help.

**Comment by pubpub-zz** [comment]
I've added a fix to cope with having ppInk in c:\program files
in this case configuration files, translations, and images are stored in%APPDATA%\ppInk
The command line now accepts also -c *config_folder* argument to allow multiple configurations

beta version
[ppInk1.8.4pre0420.zip](https://github.com/pubpub-zz/ppInk/files/15047941/ppInk1.8.4pre0420.zip)

**Comment by MichelReims** [comment]
Thank you.

**Comment by pubpub-zz** [comment]
fixed in 1.9
