### ISSUE TITLE
IMG MAX ClipArt Gallery

### ISSUE THREAD

**Issue by LoveAffaire** [pubpub-zz/ppInk#286]
I want the ClipArt gallery to have around 150 images. I am getting out of the Int 32 array. Does anyone know how to solve it?

[crash.txt](https://github.com/pubpub-zz/ppInk/files/14982554/crash.txt)

**Comment by pubpub-zz** [comment]
can you please provide a portable ppink folder with test images and configuration files for test?

**Comment by LoveAffaire** [comment]
I am attaching the config.ini file and a sample image. As it appears in the file, there is no error with the line of images that I have in comments (#), it is just the limit, if any more images are added the program crashes

[ppinkS.zip](https://github.com/pubpub-zz/ppInk/files/14982839/ppinkS.zip)

**Comment by LoveAffaire** [comment]
> can you please provide a portable ppink folder with test images and configuration files for test?

Do you need me to share the entire ppinkS folder?

**Comment by pubpub-zz** [comment]
yes please : It will ease to have the whole set of imagestamps

**Comment by LoveAffaire** [comment]
> yes please : It will ease to have the whole set of imagestamps

I share the entire folder. I have left the rest of the images in comments so that there is no error when opening. As soon as you remove the # it gives an error when opening and if you try to load an image that has given an error, the error you have above in the crash.txt appears. I know it's because of the array limit but I don't know where I can modify or solve it. I would like to expand the limit to 200 or 300 images.

[ppinkS.zip](https://github.com/pubpub-zz/ppInk/files/14994135/ppinkS.zip)

**Comment by pubpub-zz** [comment]
the fix is very simple:
you just have to change in ImageLister.cs line 20 to:
```
        public Point[] ImgSizes = new Point[1000]; // I wanted to use the tag, but for an unknown reason it affects image display in dialogbox....
```

I take opportunity to ask you : you seem to have been able to build and run ppInk in macOS environment. Am I right? is it working fine ? have you done lots of change to get it work ?

**Comment by LoveAffaire** [comment]
> the fix is very simple: you just have to change in ImageLister.cs line 20 to:
> 
> ```
>         public Point[] ImgSizes = new Point[1000]; // I wanted to use the tag, but for an unknown reason it affects image display in dialogbox....
> ```
> 
> I take opportunity to ask you : you seem to have been able to build and run ppInk in macOS environment. Am I right? is it working fine ? have you done lots of change to get it work ?

Thanks a lot! Today I'm trying the solution and I'll let you know how it went. For now I am not trying to compile the tool on macOS, I simply work/edit with visual studio on macOS and later compile in Wine or run the application on Windows machines. When I finish I will try to port or see how to use the tool in macOS and I will tell you my experience so that you can adapt or modify it if you want.

Again, thank you so much!

**Comment by pubpub-zz** [comment]
I tried it successfully.
PpInk/gInk uses one old library to handle the drawings where there is no sources:porting may be very difficult.
Do not hesitate to star the project 😊

**Comment by pubpub-zz** [comment]
do not forget to star the project 😊
