### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [pubpub-zz/ppInk#291]
Does this work with Win 7?

Thanks

**Comment by pubpub-zz** [comment]
I can't test W7 is deprecated since a while. In any case ppInk is x64. be sure you are using the good version: have a try and share your experience 😉

**Comment by pubpub-zz** [comment]
@harryray33 

Can you provide update ?

**Comment by pubpub-zz** [comment]
I close it without feedbacks feel free to complete your statement
