### ISSUE TITLE
Ppink not working in Screen sharing through any application

### ISSUE THREAD

**Issue by Rahulm-15** [pubpub-zz/ppInk#295]
I tried to use ppink  while screen sharing in Zoom, Google meet but the annotations are not visible to any participants.. Though they are visible to me. Is there any particular Windows 11 setting I should change? Please help

**Comment by pubpub-zz** [comment]
I do not use zoom but I've tried other solution successfully. I've just noted that some application are not properly capturing the size of the cursor if too big. 

Can you check you are sharing the whole screen and not only one application ?

**Comment by pubpub-zz** [comment]
Any updates? Can we close it?

**Comment by pubpub-zz** [comment]
without feedbacks  I close this thread feel free to provide update
