### ISSUE TITLE
Useful improvements

### ISSUE THREAD

**Issue by 52fisher** [pubpub-zz/ppInk#30]
I have some ideas about the design that can improve the user experience. For example
-  When I press the Eraser button, the cursor can become an Eraser
-  When I press ESC, I want the toolbar to be contracted and disable the drawing mode (enable click-through mode) instead of just turning it off.(Floating Call is not necessary)
-  Provides an option to adjust the size of the cursor, which is too large。

**Comment by pubpub-zz** [comment]
>     * When I press the Eraser button, the cursor can become an Eraser

addressed through commit 9f951fa153463719fc534b56f092b44a5d9e7764

[ppInkTst.zip](https://github.com/pubpub-zz/ppInk/files/5612479/ppInkTst.zip)

**Comment by pubpub-zz** [comment]
>     * Provides an option to adjust the size of the cursor, which is too large。
when cursor.ico and eraser.ico exists next to ppInk.exe, they are used to customize the cursors. The image size are taken into account to adjust the cursor size. When instead of .ico files, .cur or .ani are provided. due to standard windows feature they are automatically resizer to the default sizer (32x32 ?). an entry in config.ini will be quite time consuming whereas adjusting directly the icon file makes the job.

**Comment by 52fisher** [comment]
> when cursor.ico and eraser.ico exists next to ppInk.exe, they are used to customize the cursors. The image size are taken into account to adjust the cursor size. When instead of .ico files, .cur or .ani are provided. due to standard windows feature they are automatically resizer to the default sizer (32x32 ?). an entry in config.ini will be quite time consuming whereas adjusting directly the icon file makes the job.

Ok,I get your point.Thank you again for the great job you did.  Furthermore, can you consider the second suggestion?
This suggestion is made because the floating call icon cannot be dragged (modifying the location requires changing the configuration file), and the text will be blocked sometimes. But I can drag and drop freely to modify the location  by shrinking and expanding the toolbar .

**Comment by pubpub-zz** [comment]
In progress 😉, is the eraser good for you ?

**Comment by 52fisher** [comment]
> 
> 
> In progress 😉, is the eraser good for you ?

Of course.  It's exactly practical.

**Comment by pubpub-zz** [comment]
Finally, I've finished a test version with customizable shortcuts (lots of trouble with spacebar). also this version includes automatic engaging pointer mode when switching application with Alt+Tab. shortcuts Customization is available throught options.
[ppInkTst.zip](https://github.com/pubpub-zz/ppInk/files/5648625/ppInkTst.zip)

waiting for your feed-backs.

**Comment by 52fisher** [comment]
> 
> 
> Finally, I've finished a test version with customizable shortcuts (lots of trouble with spacebar). also this version includes automatic engaging pointer mode when switching application with Alt+Tab. shortcuts Customization is available throught options.
> [ppInkTst.zip](https://github.com/pubpub-zz/ppInk/files/5648625/ppInkTst.zip)
> 
> waiting for your feed-backs.

Great! I tried it again,and it's so good. 
But when the toolbar is retracted, it's better to add an option to enable cursor mode.I think that when I retract the toolbar, it may be because the screen is blocked, or I don't need to use the toolbar. Usually we undock it at the bottom or top of the screen. In most cases, it will not block the screen.Frequently, I dock it  because I don't need to use the toolbar.
Enable cursor mode when toolbar is retracted, which will give users more choices.
What's your opinion?

**Comment by pubpub-zz** [comment]
I had many times to fold the toolbar for drawing only. I personnally use very rarely the pointer mode : For me when you draw, the background should not change or so little that the toolbar was not messing me up. 
Engaging systematically pointer mode when docking will prevent drawing 
What I can propose is to dock also when alt+tab is used

**Comment by 52fisher** [comment]
> I had many times to fold the toolbar for drawing only. I personnally use very rarely the pointer mode : For me when you draw, the background should not change or so little that the toolbar was not messing me up.
> Engaging systematically pointer mode when docking will prevent drawing
> What I can propose is to dock also when alt+tab is used

Okay, I get your point. 
In fact, I am a teacher. I use this software in class, so I need to switch pointer mode frequently. There is no external keyboard for the multimedia equipment in the classroom.
That's why I proposed to switch pointer mode by dock or undock.
I think PPInk is able to play a huge role in the education industry,especially during the period of covid-19.

**Comment by 52fisher** [comment]
Another reason is that the logic I proposed is similar to that of Epic Pen. When I fold the toolbar, I can hide the ink and enable the pointer mode. When I unfold the toolbar, I can continue the ink and use the drawing mode.

**Comment by pubpub-zz** [comment]
find attached a test version with alt+tab providing both ways (into and outof drawing)
[ppInkTst.zip](https://github.com/pubpub-zz/ppInk/files/5684630/ppInkTst.zip)

Give me your feedbacks

**Comment by pubpub-zz** [comment]
The new release version should meet your expectations. Can you try it and give me your feed backs:
https://github.com/pubpub-zz/ppInk/releases/tag/1.3alpha3

**Comment by 52fisher** [comment]
> 
> 
> The new release version should meet your expectations. Can you try it and give me your feed backs:
> https://github.com/pubpub-zz/ppInk/releases/tag/1.3alpha3

Thx for what you did. I've been so busy lately that I forgot to reply your messages. 

I tried the latest version and found some problems：
1.  ![图片](https://user-images.githubusercontent.com/32198215/102698482-a4017600-4278-11eb-9e3d-e9bb3cf5a053.png)
Part of the toolbar will change to other color when the toolbar is unfolding , and it will return to normal when unfolded.
2. The ALT + Tab shortcut key conflicts with the shortcut key of win10 system's own switch window.(I can't provide a screenshot due to a shortcut key conflict) Can I customize this shortcut key?
BTW,I use the software on the school's electronic screen. It's inconvenient to use shortcut keys for touch screen electronic devices. Can you provide another option to switch pointer mode, such as click the dock icon and undock icon

**Comment by 52fisher** [comment]
[zh-cn.txt](https://github.com/pubpub-zz/ppInk/files/5720132/zh-cn.txt)

**Comment by pubpub-zz** [comment]
1 is known. I've already raised an issue about it
2 Actually pointer is engaged when an other application is selected (through alt+tab most of the time). therefore this shortcut (alt+tab_can not be customised.How ever try to use the global short cut. Else you can just click on the arrow button.

PS. thanks for translation 😊

**Comment by pubpub-zz** [comment]
about the color : set the alpha to 255 in the ini file

**Comment by pubpub-zz** [comment]
I've normally have fixed the issue with drawing during toolbar unfolding. also this allow to apply transparency. give me your feedbacks. is the behavior with the pointer button good for you ?
[ppInkTst.zip](https://github.com/pubpub-zz/ppInk/files/5720753/ppInkTst.zip)

**Comment by pubpub-zz** [comment]
Hi @52fisher,
Have you been able to test this test version?

**Comment by 52fisher** [comment]
> Hi @52fisher,
> Have you been able to test this test version?

The first issue has been solved.
The second issue can also be automatically folded by clicking the pointer mode. At present, It's very practical.
