### ISSUE TITLE
auto set the text edit option to "transparent background'

### ISSUE THREAD

**Issue by Ventilo23** [pubpub-zz/ppInk#313]
Hello, 
Thank you very much for your very very nice app. 
I often use the 'text' tool (T icon). 
I understand that we can edit the text size by going to the application options. 

One thing I don't know how to do, is change the background of the written text so that it appears transparent, by default.
The default setting is set to "frame+ transparent  background", and I'd love it to be set by default to 'transparent' mode (first option proposed).

Another remarq that would be also very very nice, is the ability to write the text directly on screen, not using the pop up menu. But this is secondary, in my opinion.

Thanks again, 
Regards,
Ventilo

**Comment by Ventilo23** [comment]
ok, i installed this version: 
https://github.com/pubpub-zz/ppInk/issues/226
and the problem i mentionned in my later message seems to have been corrected!
All the best
Ventilo

**Comment by pubpub-zz** [comment]
Good
Do not hesitate to star the project
