### ISSUE TITLE
Snapshot problem

### ISSUE THREAD

**Issue by GL-Doses** [pubpub-zz/ppInk#33]
Hi, when I use the snapshot with the background board set to transparent it saves the screen perfectly. But if I use a background board set to white or black the snapshot saves only a white/black screen without any of the drawings that I made. Thanks.

**Comment by pubpub-zz** [comment]
Problem confirmed. under investigation

**Comment by pubpub-zz** [comment]
I have normally fixed the problem. this is a test version
[ppInkTst.zip](https://github.com/pubpub-zz/ppInk/files/5639371/ppInkTst.zip)

be aware that this version is including some inprogress development (introducing short cut customization for toolbar docking and closing

**Comment by GL-Doses** [comment]
Hi, I tested it and it worked flawless, everything that I need in such program is already present here.

But if you would like suggestions I have two:
- Would be possible to save my drawings without the transparent background? Because I make a lot of annotations on screen as I change it (on transparent mode) and I would like to save only that and not the screen background that is present when I take the snapshot. For example: long click on snapshot icon opens a choose a background only for the saved image (like the clear icon does).
- I didn't find an option to change the toolbar color (only white color). If that was possible it would be nice. 

Thanks.

**Comment by pubpub-zz** [comment]
Happy you are enjoying it.
about your suggestions, they sounds good (I may propose an other way to do things to change background but in the same idea): can you open another issue with your suggestions ?

**Comment by GL-Doses** [comment]
Done.
