### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by GL-Doses** [pubpub-zz/ppInk#34]
Would be possible to save my drawings without the transparent background? Because I make a lot of annotations on screen as I change it (on transparent mode) and I would like to save only that and not the screen background that is present when I take the snapshot. For example: long click on snapshot icon opens a choose a background only for the saved image (like the clear icon does).

I didn't find an option to change the toolbar color (only white color). If that was possible it would be nice.

Thanks.

**Comment by pubpub-zz** [comment]
find attached a first test version for toolbar color change. Currently it is only modifiable through direct access to the config.ini
Also this version include buttons customization : the images have to be placed in the ppink folder (the original images are available in the src folder)
Waiting for your feedbacks

**Comment by GL-Doses** [comment]
Hi, I have done some tests and took some screenshots. I uploaded it to imgur and commented under each one there to make it easier to analyze. https://imgur.com/a/VgiUEIW

**Comment by pubpub-zz** [comment]
I've normally have fixed the issue with drawing during toolbar unfolding. also this allow to apply transparency. give me your feedbacks.
[ppInkTst.zip](https://github.com/pubpub-zz/ppInk/files/5720753/ppInkTst.zip)

**Comment by pubpub-zz** [comment]
fixes released
