### ISSUE TITLE
ppInk Crash

### ISSUE THREAD

**Issue by kethan1** [pubpub-zz/ppInk#35]
Hi, love the program, but every once in a while, ppInk crashes. 

Here is the info from `crash.txt`:

```
12 / 09 / 2020 22:02UIThreadException

Oops, gInk crashed! Please include the following information if you plan to contact the developers (a copy of the following information is stored in crash.txt in the application folder):

Object reference not set to an instance of an object.

Stack Trace:
   at System.Windows.Forms.NotifyIcon.ShowContextMenu()
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by pubpub-zz** [comment]
Can you please provide more information about context : were you clicking on some button ? 
can you indicate also which version you are using ?

Thanks

**Comment by pubpub-zz** [comment]
i have some concern to analyze your problem : your report is not reporting any line code... Can you confirm you are working with latest version. which windows are you running ?

**Comment by kethan1** [comment]
I downloaded the program a few days ago. I am on Windows 10 H2H2.

**Comment by pubpub-zz** [comment]
Can you try this test version:
[ppInkTst.zip](https://github.com/pubpub-zz/ppInk/files/5682955/ppInkTst.zip)
It is an in progress version. I've checked that lines are reported. can you tell me if the issue is present and try to define the except scenario that leads to the problem. Thks

**Comment by kethan1** [comment]
Couldn't reproduce the problems. Either a fluke or the new version solves it. Thanks!
