### ISSUE TITLE
一些問題

### ISSUE THREAD

**Issue by chofersplay** [pubpub-zz/ppInk#36]
1.請問可以做到，把兩次不同的圖合成一個嗎?因為需要常常移動原本畫好的圖，但是如果滑鼠不是同一次點擊的話，會只移動到某一個
2.可以編輯原本的圖嗎？例如：我畫了綠色直線，想把它編輯改成紅色。例如：原本畫了5cm 但後來想編輯把它改成10cm
3.現在這個版本按垃圾桶(clear)會出現問題

謝謝

**Comment by pubpub-zz** [comment]
pls translate in english

**Comment by chofersplay** [comment]
1. Can I make it possible to combine two different pictures into one? Because I need to move the original picture often, but if the mouse is not clicked at the same time, it will only move to a certain one. 

2. You can edit the original picture ? For example: I drew a green line and want to edit it to red. For example: I originally drew 5cm but later I wanted to edit it and change it to 10cm 

3. Now this version will cause problems when pressing the trash can (clear). 

Thank you

**Comment by pubpub-zz** [comment]
>     1. Can I make it possible to combine two different pictures into one? Because I need to move the original picture often, but if the mouse is not clicked at the same time, it will only move to a certain one.

I understand that you would like to group 2 drawn strokes : unfortunately those are strokes that need to to be one line : It is therefore not possible to gather them easily

>     2. You can edit the original picture ? For example: I drew a green line and want to edit it to red. For example: I originally drew 5cm but later I wanted to edit it and change it to 10cm

I do not know yet if stroke selection is possible and or easy. I will put this idea in the feature request list

>     3\. Now this version will cause problems when pressing the trash can (clear).

Can you please provide crash report for analysis


> 4.Copy and paste an already drawn picture

If stroke selection is working this could be also a new feature idea

**Comment by chofersplay** [comment]
![1607668779262](https://user-images.githubusercontent.com/75788305/101871927-64bf8f00-3bbf-11eb-9c6c-f0d56ef3f915.jpg)

When I press the eraser, this error message pops up.

Thanks for your reply.

**Comment by pubpub-zz** [comment]
This error looks like an internal error within microsoft ink when asserting the cursor and is be random. I've been able to find to find a workaround. can you confirm this evaluation version solves the problem
[ppInkTst.zip](https://github.com/pubpub-zz/ppInk/files/5682915/ppInkTst.zip)
Note that this an interim version with some work in progress.

**Comment by chofersplay** [comment]
> This error looks like an internal error within microsoft ink when asserting the cursor and is be random. I've been able to find to find a workaround. can you confirm this evaluation version solves the problem
> [ppInkTst.zip](https://github.com/pubpub-zz/ppInk/files/5682955/ppInkTst.zip)
> 
> Note that this an interim version with some work in progress.
> Updated test version

1.I solved it in other ways
3.Solved. 

Thanks.

**Comment by pubpub-zz** [comment]
can you raise a new issue with point 2 and 4, that way you will be noticed when I will be ready to work on those new features

**Comment by pubpub-zz** [comment]
Hi @chofersplay,
I'm reopening this issue to exchange on point 2 : edit an object and copy.
I've built this new version test version:
a) when you click many times on pan button, you now get pan all/move one/copy one :  you can that way duplicate an existing stroke
b) the edit button(where I'm trying to change the image), allow you to edit also existing stroke to modify color and width. I' also introduced a new button in the input dialog box to change color of a text
[ppInkTst2.zip](https://github.com/pubpub-zz/ppInk/files/5742189/ppInkTst2.zip)
waiting for your feedbacks

**Comment by pubpub-zz** [comment]
Official release has been issued
