### ISSUE TITLE
New Feature : polyline/polygone

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#38]
I've just developped a new feature : polylines and polygones. the function is available under the line button. Draw edges by click or mouse down. To finish, click next to the last vertex.
Undo will remove the last segment and will allow to resume from there.
[ppInkTst.zip](https://github.com/pubpub-zz/ppInk/files/5721434/ppInkTst.zip)
Waiting for your feed before introducing this commit into main branch.

**Comment by cmhdream** [comment]
It can only be a quadrilateral, including the lines inside.
Cannot draw lines inside triangles.

https://user-images.githubusercontent.com/24859526/102861844-323d4e00-446b-11eb-98a7-5f9408f17130.mp4

**Comment by pubpub-zz** [comment]
you are only on line tool : to activate polyline and then polygone(filled), click many times on line button to engage

**Comment by pubpub-zz** [comment]
Features released in 1.4 alpha1
