### ISSUE TITLE
Feature request: Pen Tip configurable & Beta-testing

### ISSUE THREAD

**Issue by mrvainv2** [pubpub-zz/ppInk#39]
Hi, 

I'm impressed by the enhancements made to the ppInk utility. Also the use of the ALT key popping-up the Arrow is appreciated. 

**[Q1]**	 Would it be possible to implement a similar customization as you did for the Arrow (canvas cursor) but now for the Pen-tip? On my 4K monitor I continoulsy "loose" the pen tip and although I can use the ALT key to pop-up the Arrow, I would not always like the ALT key for the Arrow during a presentation.

I also downloaded the Beta-test version. 

**[Q2]** For the moment, no issues found. Do you require something special to be tested?

With kind regards,

MrVain II

**Comment by pubpub-zz** [comment]
Hi @mrvainv2,
Happy you're enjoying ppInk,
[Q1] : can you please clarify what type of customization you are thinking about? The current implementation coming from gink shows a disk of the size of the drawing.
[Q2] : have you tested the polyline/polygone tool ? do you think they are operable with this implementation ? No side effect on the different functions ?

                                             Thanks

**Comment by pubpub-zz** [comment]
+1 about Q1.

**Comment by mrvainv2** [comment]
Hi,

Sorry for the delay (holidays)

To elaborate on Q1. In case of the "Cursor arrrow", I can take the icon file (**cursorarrow.ico**) and change it to my own needs. Although the arrow is quite handy during explanation, the "pen tip" laser pointer is sometimes more appropriate. Would it be possible to have a similar solution for the "pen tip", an icon file I can change or an extra cursor arrow?

**Comment by pubpub-zz** [comment]
the pen tip cursor is build as a disk which size is the requested pen width size. When the pen is too small it is surrounded by a black circle. I can not see how to customize this. However remember that the pen tip can be temporarily changed to the arrow depressing alt. Isn't this sufficient ?

**Comment by mrvainv2** [comment]
Hi,

I'm aware that my question is "nice to have" The proposed workaround is definitely a good workaround.
