### ISSUE TITLE
Suggestion : To add images (e.g. "happy.png", "sad.png") as icons in the toolbar

### ISSUE THREAD

**Issue by JamesZing** [pubpub-zz/ppInk#44]

**Comment by pubpub-zz** [comment]
implented in 44c5a42b57606c92131a0768890bc05b0b96e39b

**Comment by JamesZing** [comment]
Update: New function made available since "ppInk (3)" version.

Suggested improvement: 
Follow the newly updated Number Chip (N) function by having a default size for Clipart with user customization in Options.
