### ISSUE TITLE
There are difference between original screen pointer and mirroring screen pointer.

### ISSUE THREAD

**Issue by niekine** [pubpub-zz/ppInk#45]
@pubpub-zz  Also have the same problem as at glnk app.
![IMG_20210123_133935](https://user-images.githubusercontent.com/77881343/105633793-c6844180-5e6b-11eb-916d-c4fa195acae7.jpg)

**Comment by niekine** [comment]
![IMG_20210123_133856](https://user-images.githubusercontent.com/77881343/105633820-e87dc400-5e6b-11eb-9155-c9995c94577c.jpg)

**Comment by pubpub-zz** [comment]
can you  provide screenshots activating the arrow cursor and also with the 'hinted' sized cursor.
 Can you confirm that you have used cursor files in ppink folder and provide them thks

**Comment by niekine** [comment]
![IMG_20210124_181557](https://user-images.githubusercontent.com/77881343/105634661-3dbbd480-5e70-11eb-81c3-558ee02882b8.jpg)

**Comment by niekine** [comment]
![Uploading 16115014487814099213424741846594.jpg…]()

**Comment by niekine** [comment]
if you use original cursor size 64*64 the issue is to be small. if you should set the pen tip, the issue partially is solved. But if you change  pen size the difference is again increasing.

**Comment by niekine** [comment]
![IMG_20210124_180421](https://user-images.githubusercontent.com/77881343/105634881-3a751880-5e71-11eb-8fc2-0cc11ab8b93e.jpg)

**Comment by niekine** [comment]
![IMG_20210124_180401](https://user-images.githubusercontent.com/77881343/105634884-43fe8080-5e71-11eb-87ec-a54456c1785e.jpg)

**Comment by niekine** [comment]
![IMG_20210124_181020](https://user-images.githubusercontent.com/77881343/105634906-65f80300-5e71-11eb-988c-5ef2903a4cae.jpg)

**Comment by niekine** [comment]
![IMG_20210124_180900](https://user-images.githubusercontent.com/77881343/105634912-6ee8d480-5e71-11eb-8ec3-e94c21737b9b.jpg)

**Comment by niekine** [comment]
![IMG_20210124_181106](https://user-images.githubusercontent.com/77881343/105634936-8aec7600-5e71-11eb-8880-543d08e37f10.jpg)

**Comment by niekine** [comment]
OS Original screen, MS mirroring screen

**Comment by pubpub-zz** [comment]
There are 3 possible files to customizer the cursor : cursorarrow.cur, cursorarrow.ani, cursor.ico : can you tell which file you have added/modified and provide it please

**Comment by niekine** [comment]
![1611502162040100678195458023730](https://user-images.githubusercontent.com/77881343/105635066-21b93280-5e72-11eb-8c40-024cf9e6752e.jpg)

**Comment by niekine** [comment]
Cursorarrow.ico is used for changes.
I have used the webex app.

**Comment by pubpub-zz** [comment]
I've just made a test with the default cursor I'm providing:
![image](https://user-images.githubusercontent.com/4083478/105636429-aacb6c00-5e68-11eb-9078-448ef6c46108.png)
I've connected a meeting using 2 session (one in FF,one in Chrome)
and the cursor is not offset on both (sorry not captured on main screen but it was good)

 Can you run the same test to confirm we have the same results with my cursor and then with yours

**Comment by niekine** [comment]
I see , if it possible to check together we will connect same time to webex and confirm the fault at tomorrow. Can you send a number of meeting ?

**Comment by niekine** [comment]
And can you open your curser.ico with paint app, you will see actual size is different.

**Comment by pubpub-zz** [comment]
find the cursorarrow.ico (which is actually part of all distribution).
[cursorarrow.zip](https://github.com/pubpub-zz/ppInk/files/5863205/cursorarrow.zip)
it is a 128x128 icon file where the arrow head is in the middle of the drawing area (the arrow is actually only 64x64, the rest is empty)
Can you first try a loop back connection using 2 browser as I did : you should be able to do that quite easily

**Comment by niekine** [comment]
@pubpub-zz Can i change bar rotation from horizontal to vertical?

**Comment by pubpub-zz** [comment]
> @pubpub-zz Can i change bar rotation from horizontal to vertical?

This feature was not part of gink and is not in my fork neither.

**Comment by pubpub-zz** [comment]
> it is a 128x128 icon file where the arrow head is in the middle of the drawing area (the arrow is actually only 64x64, the rest is empty)
> Can you first try a loop back connection using 2 browser as I did : you should be able to do that quite easily

Have you been able to progress in the test with the cursor and the loopback ?

**Comment by niekine** [comment]
Actually i could not test, i will in actual lesson at tomorrow.

**Comment by pubpub-zz** [comment]
looking forward to get your results 😃

**Comment by pubpub-zz** [comment]
Have you been able to retest?

**Comment by niekine** [comment]
@pubpub-zz i have been test and i could not see problem. Solution is work fine which cursor is turn to original dimension.

**Comment by niekine** [comment]
@pubpub-zz also i have seen problem related to crash with window mouse during switch each other.

**Comment by pubpub-zz** [comment]
> 
> 
> @pubpub-zz also i have seen problem related to crash with window mouse during switch each other.

Do you still have the issue with the latest version where Zoom is included ?

**Comment by pubpub-zz** [comment]
Can I consider that no more crash have been observed ?

**Comment by pubpub-zz** [comment]
No more issue reported since a month : issue closed
