### ISSUE TITLE
Move & Copy Functions should be separated.

### ISSUE THREAD

**Issue by JamesZing** [pubpub-zz/ppInk#48]
Currently, both functions are merged together and toggled via hotkey "P".

Suggestions:
(a) Move Function should only have 2 toggles ("One" or "All"). 
(b) Copy Function should be separated from the Moving Function and it should have its own hotkey and toggles ("One" or "All").
(bi) In Copying mode, when the mouse hovers over drawings, there should be a highlight (or box-up) indicator to show the user which drawing is to be copied.
(bii) A "Paste Function" should be included as well. One way to achieve this is to change the button from "Copy" to "Paste" once the user has selected one/all drawing(s) to be copied.

**Comment by pubpub-zz** [comment]
I would not like add too many buttons,and the paste function is quite tricky to implement. I will leave this issue open awaiting other used to give their opinion

**Comment by pubpub-zz** [comment]
one extra point : keyboard shortcut multiple press allow to rotate the the different features available in a same button

**Comment by JamesZing** [comment]
Version tested: "ppInk Beta"
OS: Win7
Verdict: Still cannot move or copy a drawing.

**Comment by pubpub-zz** [comment]
I've done this recording through the ffmpeg option in ppInk:

https://user-images.githubusercontent.com/4083478/106356178-ebf6cc80-62fd-11eb-9f77-30ebe3be4820.mp4

Can you reproduce it?

note: I've found some random issues running FFMPEG. recording. (cf new issue)

**Comment by JamesZing** [comment]
I tried to replicate what you did but to no avail.

Here are the details of my experience and observations:
(a) The "Move One" or "Copy One" modes would not function as intended.
(b) The only mode which worked for me was the "Pan All" function.
(c) There were no Selection Borders when my mouse hovered over the drawings or when I left-clicked on them (Note: Selection Borders do appeared offset to the bottom right of the screen in Eraser mode (E) but unfortunately, they do not even appear anywhere in Move/Copy/Pan Mode (P))

Attached is a recording of my attempt to reproduce what you did:
https://user-images.githubusercontent.com/77811611/106363327-cfd94680-6362-11eb-962b-8fc8abbacdc5.mp4

**Comment by pubpub-zz** [comment]
I close the issue as copy of https://github.com/pubpub-zz/ppInk/issues/47#issuecomment-778801127
