### ISSUE TITLE
Text Function - To allow users to type directly on screen without a separate text box.

### ISSUE THREAD

**Issue by JamesZing** [pubpub-zz/ppInk#50]
I invited one of my friends to test out "ppInk Beta" and one of his feedback was that the Text Function (T) would be more intuitive if it allows the user to type directly on screen without the need for a separate text box.

He demonstrated this concept to me using another application known as ZoomIt. 
Having tried it myself, it is true that the ability to type directly on the screen does improve the user experience.

If this feature becomes available in a future release, that would be really cool.

**Comment by pubpub-zz** [comment]
Implementation of direct typing is quite complexe. There is an immediate rendering which is very similar and also there is the font,color,and  framing button available that would then need to be added in other way. I will not implement the improvement before a while
