### ISSUE TITLE
Question: Is the low graphic of pasting ClipArts from the clipboard a permanent issue?

### ISSUE THREAD

**Issue by WhirlyZaph** [pubpub-zz/ppInk#53]
Exactly like the title. If it isn't, do you have a temporary/planned fix?

**Comment by pubpub-zz** [comment]
can you please clarify your comment or provide an example. For me it is good: the default size (short-click to paste) uses the original image size. ex
![image](https://user-images.githubusercontent.com/4083478/106711861-6ecaa080-65f8-11eb-84d4-1df1143e07dd.png)
on left the image as opened by mspaint on right the pasted image

**Comment by pubpub-zz** [comment]
just seen what you mean. under analysis

**Comment by pubpub-zz** [comment]
problem understood and fixed. can you test it:
[ppInk beta.zip](https://github.com/pubpub-zz/ppInk/files/5920727/ppInk.5.zip)

**Comment by pubpub-zz** [comment]
Have you been able to test it ?

**Comment by WhirlyZaph** [comment]
After testing it, the results are as good as expected and I've noticed the size of the clip pasted is a little bit bigger than the original but I don't think it'll be a problem. Other than that, it caused a crash. I'll post it here just in case.
[crash.txt](https://github.com/pubpub-zz/ppInk/files/5940633/crash.txt)
Also if you don't mind a little request... this has bugged me for a while
![image](https://user-images.githubusercontent.com/40259033/107165313-1410ba80-69e5-11eb-9152-cd71176a7b74.png)

**Comment by pubpub-zz** [comment]
I'm expecting the crash you have experienced to be fxed in the latest release.
Version:
[ppInk beta.zip](https://github.com/pubpub-zz/ppInk/files/5940208/ppInk.beta.zip)

about the HMI issue : it is a problem in the translation file \n missing.  I will update it for next official release

**Comment by WhirlyZaph** [comment]
Yep.. no more crashes. Seriously, thanks!
