### ISSUE TITLE
change bar rotation from horizontal to vertical

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#54]
@pubpub-zz Can i change bar rotation from horizontal to vertical?

_Originally posted by @niekine in https://github.com/pubpub-zz/ppInk/issues/45#issuecomment-767702087_

**Comment by pubpub-zz** [comment]
Beta version with the adjustable orientation through the option dialog
![image](https://user-images.githubusercontent.com/4083478/107161741-0f291800-699f-11eb-8068-9007ba9ad616.png)

Version:
[ppInk beta.zip](https://github.com/pubpub-zz/ppInk/files/5940208/ppInk.beta.zip)

**Comment by niekine** [comment]
@pubpub-zz thank you so much for new feature.
