### ISSUE TITLE
Free zoom function

### ISSUE THREAD

**Issue by niekine** [pubpub-zz/ppInk#55]
@pubpub-zz if it possible to add free hand zoom function wherever i want to zoom?

**Comment by pubpub-zz** [comment]
Hi this is a very very first version of the zoom.
I need to improve zoom window position in order to stay in the screen.
[ppInkZoom.zip](https://github.com/pubpub-zz/ppInk/files/5976632/ppInkZoom.zip)
Your opinion

**Comment by niekine** [comment]
@pubpub-zz your idea is so good but need improvement as zoom function (ctrl+scroll in or out) adobe pdf reader . If you add this tool pplink will be awesome. Zoom function should be initiated by taking real mouse cursor coordinate. Also hotkey assignment is required.

**Comment by pubpub-zz** [comment]
I think all features / configuration are included in this version. Ctrl+Mousewheel is also implemented.
[ppInkZoom.zip](https://github.com/pubpub-zz/ppInk/files/5978019/ppInkZoom.zip)

**Comment by pubpub-zz** [comment]
options implementation was incomplete
new beta version
[ppInk Beta.zip](https://github.com/pubpub-zz/ppInk/files/5981582/ppInk.Beta.zip)

**Comment by niekine** [comment]
@pubpub-zz thanks for extension but it doesn't mean actually zoom properties. Maybe you should check the zoomlt zoom function, if it is possible  to perform actual screen zooming and note taking it will be awesome.

**Comment by pubpub-zz** [comment]
I've just checked ZoomIt and it just actually do a screen capture, and magnifies it. My current proposal is more dynamic and from my proposal is more dynamic/"real time". I can propose a secondary zoom where you will select that area that will be full screen magnified and displayed as a background to draw on but no zoom nor panning will be available on this image.

**Comment by pubpub-zz** [comment]
I've implemented the zoom function as described. To activate, click twice on the zoom button, and once more to return.
[ppInk Zoom2.zip](https://github.com/pubpub-zz/ppInk/files/5992176/ppInk.Zoom2.zip)

**Comment by niekine** [comment]
@pubpub-zz it is so good but can you remove the magnifier function.and also cursor dot (which is not visible) switch to normal cursor for selecting at same time.

**Comment by pubpub-zz** [comment]
I've introduced customization, but for the moment you have to directly modify Zoom_Icon in the config.ini file ; not sure yet to allow modification through option dialog (extra work...)
about the cursor I prefer to leave it that. If you want to get the arrow, just depress the alt key (for temporary cursor) or set arrow as default cursor
[ppInkZoom3.zip](https://github.com/pubpub-zz/ppInk/files/5995501/ppInkZoom3.zip)

**Comment by pubpub-zz** [comment]
Zoom(s) and Customization are implemented I will close the issue

**Comment by niekine** [comment]
@pubpub-zz I don't have enough time to check it these days, but i will check it.
