### ISSUE TITLE
Auto Fade - after you draw  - feature please

### ISSUE THREAD

**Issue by lucacuccu3x8** [pubpub-zz/ppInk#56]
Hi!
I love your work.
I'm a teacher doing remote lecturer. 
While reading to students, having a tool that could draw the lines you're reading and auto fading for you could be really helpful for either screencast, presentations, and video tutorials.
Do you think is it possible to add such a feature?
An example of it:
I found a tool for presentations only, that has a similar feature when in presentation mode, see here please:  https://www.simplediagrams.com/docs/presentation-mode.html
I think it could be an awesome addition to ppInk

**Comment by pubpub-zz** [comment]
I have introduced a new property - fading - for color:
![image](https://user-images.githubusercontent.com/4083478/107854329-74f02680-6e1b-11eb-9cf8-0cfac1009b7d.png)

You can adjust the time before fading with the value (default 5 sec). This works for all drawings but images - for unknown reason.

[ppInkFading.zip](https://github.com/pubpub-zz/ppInk/files/5975943/ppInkFading.zip)

Is it good for you?

**Comment by lucacuccu3x8** [comment]
Dear pubpub-zz

I’m stunned!
This is great!
Thank you so much!
Are the units in seconds and are float decimal allowed?
Are artefacts after fading’s my end problem? (they are very hard to see anyway, see screenshot please.
What is the right step to get the configuration file saved and not reverting to default each time launching the application?
Thank you so much for this. Your work is awesome. My colleagues are all using your app now 😊

Kindest Regards

L[cid:image001.jpg@01D70223.8AA24440][cid:image002.jpg@01D70223.8AA24440]


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by lucacuccu3x8** [comment]
Dear pubpub-zz

I’m stunned!
This is great!
Thank you so much!
Are the units in seconds and are float decimal allowed?
Are artifacts after fading’s my end problem? (they are very hard to see anyway, see screenshot, please.
What is the right step to get the configuration file saved and not reverting to default each time launching the application?
Thank you so much for this. Your work is awesome. My colleagues are all using your app now 😊

Kindest Regards

![Screenshot 2021-02-13 160639](https://user-images.githubusercontent.com/9900115/107855211-e8446900-6e18-11eb-8b21-b16039398af1.jpg)
![Screenshot 2021-02-13 161229](https://user-images.githubusercontent.com/9900115/107855212-e8dcff80-6e18-11eb-91c6-ce0b53d77ad8.jpg)

**Comment by pubpub-zz** [comment]
the best solution is to activate fading in the options / Pen tab. The time before fading can be also modified there. The fading time is about half a second, and is not customizable. Once you have set what you want you save the changes on the general tab.

The value in the pens.ini file can be Y/N/number; Y = general value ; N = No Fading ; number = number of seconds (float) straight typed
I have difficulties to understand about what you mean about artifacts : can you clarify?

**Comment by lucacuccu3x8** [comment]
Hi pubpub-zz

thank you very much for the reply.
Regarding the Artifacts, I meant about the lines faded are still a tiny visible like "ghosting"  - please see  screenshot - 
It seems to appear only when using the pen as a pencil.
this ghosting disappears when you invoke the "clear" with the hotkey. 
but, don't worry about it! - I think it's the transparent background applied, or just me.

Also, when selecting the OK in the "Pen Adjustment" I get this error - please see screenshot -
- it seems to happen only when adjusting pen  6 7 8; - the first 5 pens are ok. 
- I've changed the colors from the pen.ini file anyway. so it is all good for me;

thank you very much again

Kindest Regards 

**Before fading:**
![before fading](https://user-images.githubusercontent.com/9900115/107857868-f7cbae00-6e28-11eb-8814-86aca8ec4814.jpg)

**After Fading:**
![after fadings](https://user-images.githubusercontent.com/9900115/107857876-0914ba80-6e29-11eb-9f9c-68e1c8d291af.jpg)

**Error after confirming the "Pen Adjustment" colors and alpha settings:**
![selecting color for pen 6 7 8 9](https://user-images.githubusercontent.com/9900115/107857927-2cd80080-6e29-11eb-95e8-08b000b146b9.jpg)

**Comment by pubpub-zz** [comment]
The ghosting effect seems to be due to the fact that the last drawing does not have a full transparency : this is odd as after this last drawing, the stroke is deleted and should not induce this ghost 
I've also fixed the crash :
[ppInkZoom.zip](https://github.com/pubpub-zz/ppInk/files/5976632/ppInkZoom.zip)
I've also included a first version for zoom tool (your opinion)

**Comment by lucacuccu3x8** [comment]
thanks pubpub
btw the file is flagged with a trojan ;)

**Comment by pubpub-zz** [comment]
> btw the file is flagged with a trojan ;)

Thanks for reporting, I've rescanned with trendmicro and microsoft essential without any warning. which solution are you using?

**Comment by pubpub-zz** [comment]
issue to be closed : the feature is implemented

**Comment by lucacuccu3x8** [comment]
Thank you pubpub-zz.
 It is working great and it is very useful in live presentations.
Perhaps, If I may and If you'd like the idea, I took the default icon and changed the color from red to blue, just to distinguish your featured one ppInk from the original one gInk. see attachments, please.
[Blue ppInk Icons.zip](https://github.com/pubpub-zz/ppInk/files/6032245/Blue.ppInk.Icons.zip)

**Comment by lucacuccu3x8** [comment]
![Screenshot 2021-02-23 230151](https://user-images.githubusercontent.com/9900115/108919575-2452a780-762b-11eb-95d9-9ebf0bea74e8.jpg)
![Screenshot 2021-02-23 230230](https://user-images.githubusercontent.com/9900115/108919625-392f3b00-762b-11eb-99b6-117a19728697.jpg)
