### ISSUE TITLE
Break Time Counter

### ISSUE THREAD

**Issue by niekine** [pubpub-zz/ppInk#57]
@pubpub-zz can you add the blank screen and counter button.

**Comment by pubpub-zz** [comment]
please clarify "counter button"

**Comment by niekine** [comment]
@pubpub-zz same as zoomlt. Can you check.

**Comment by pubpub-zz** [comment]
ppInk is a program to annotate on screen, which can also be used to support demonstrations annotating your presentation. I do not see any usecase for the counter button and my objective is not to duplicate zoomit. if you disagree please provide use-cases

**Comment by niekine** [comment]
@pubpub-zz you are right but i need to control break time at online lesson so i need a  reminder screen is useful.

**Comment by pubpub-zz** [comment]
you should more likely use in addition a dedicated timer to display on top.
eg.
https://www.microsoft.com/fr-fr/p/rebours-de-cours-magistraux/9p4npswtx7lk?activetab=pivot:overviewtab
