### ISSUE TITLE
Auto Fade Settings ( <1sec or 0.5) and mouse wheel release for scrolling doc pages while drawing - feature please

### ISSUE THREAD

**Issue by lucacuccu3x8** [pubpub-zz/ppInk#59]
Hi pubpub-zz
Thank you again for your amazing work.

- Is there any chances please, that you could give the **Auto-Fade a more granular setting (for faster fades)** in the order of <1sec please?(or better decimal numbers like 0.5 sec)
 for e.g. 
 When doing live presentations and reading through documents, sometimes a fast reader would need the highlights to fade sooner, please?

- Auto fade user-settings amended from the ppInk "Options", seems to roll back to default 5sec each time I re-launch the application. Only If I modify the configuration file, the custom-settings are remembered after re-launch.

- Also, the mouse wheel seems to be tightened with the width of the drawings..
is there any chances please to add a setting for **releasing the mouse wheel** from the grasp of ppInk, 
so that it behaves as it intended, **for scrolling** e.g. web pages or documents, please? 
(so that it avoids the need to Alt+F4 ppInk each time someone needs to get the mouse wheel back for scrolling please?) 
Again, the latter could be useful when doing live presentations and reading through long documents in a class. 

Thank you so much!

**Comment by pubpub-zz** [comment]
> * Is there any chances please, that you could give the **Auto-Fade a more granular setting (for faster fades)** in the order of <1sec please?(or better decimal numbers like 0.5 sec)
You can set decimal figures. I've tried .1s successfully. the only current "bug" is that the types time applies to pens ticked after. currently,if a pen is already ticked, You have to untick/ tick it in order to be taken into account. 
>   for e.g.
>   When doing live presentations and reading through documents, sometimes a fast reader would need the highlights to fade sooner, please?
> 
> * Auto fade user-settings amended from the ppInk "Options", seems to roll back to default 5sec each time I re-launch the application. Only If I modify the configuration file, the custom-settings are remembered after re-launch.
I've forgot to add the entry in config.ini : add **Fading_Time=.1** in the file (where you want) and it will save. 
> 
> * Also, the mouse wheel seems to be tightened with the width of the drawings..
>   is there any chances please to add a setting for **releasing the mouse wheel** from the grasp of ppInk,
>   so that it behaves as it intended, **for scrolling** e.g. web pages or documents, please?
Currently mouse events are globally captured by the application or ppInk is click through ( when in pointer mode) I do not know if it is possible to just let some events to get through. will check
>   (so that it avoids the need to Alt+F4 ppInk each time someone needs to get the mouse wheel back for scrolling please?)
>   Again, the latter could be useful when doing live presentations and reading through long documents in a class.
Instead of alt+F4, you may prefer Esc(which is doing the same) or alt+tab(which will start/end the pointer mode)

**Comment by pubpub-zz** [comment]
I confirm that there is no easy solution to transfer only some events to underlying window but I've though about your problem to get scrolling : my proposal is to put ppInk in "window" mode : in this mode not the whole surface will be covered with the window and you will be able to scroll moving the mouse out of ppink window
[ppInkWindow.zip](https://github.com/pubpub-zz/ppInk/files/6052978/ppInkWindow.zip)

To start window mode, you have to long click or right click on snap tool and then mark the new window. Note that this a alpha version

**Comment by lucacuccu3x8** [comment]
Hi pubpub. 
Hey, ain't got any issue/problem with your app. It is great already as it is.
I only thought to make a suggestion. 
When I need the scrolling of the wheel, I use hotkeys to get out from pink with Esc - it gets messy, but it only takes practice. 
And, btw the faster fading is great. That's all that we needed!
Thank you for your time.

**Comment by pubpub-zz** [comment]
I've finalized this version.
[ppInkWindow2.zip](https://github.com/pubpub-zz/ppInk/files/6055097/ppInkWindow2.zip)

For your usage, I would recommend this following use approach:
start ppInk
open options dialog
desactivate engage on alt+tab and allow moving toolbar
![image](https://user-images.githubusercontent.com/4083478/109396553-7a2c9580-7932-11eb-8629-0ecee1cdc98d.png)
display your browser / text / application on foreground
start inking
right click or long click on snapshot
draw the inking surface that will cover the required text but leaving access to the scrollbars or any are that you may need direct access to : ppInk will reduce to a window over the designated area:
![image](https://user-images.githubusercontent.com/4083478/109388993-aaf8d480-790a-11eb-86a2-08b704242c64.png)
The area directly accessible to mouse clicks and wheels

**Comment by lucacuccu3x8** [comment]
Great thanks.

I've noticed that the settings for the AutoFading are not persisting after either Closing the application(not minimizing) and relaunch, or after reboot of the system.
all other settings seems to persist, yet the auto fading goes back to 5 sec default.
my settings are autofading @ 0.7sec
Do you know a way around this please? 
thank you!

**Comment by pubpub-zz** [comment]
Oops,
   Got it :  pens.ini was loaded before config.ini, therefore the default fading was applied on pen before loading the value from config.ini. It is now fixed :
[ppInk2.zip](https://github.com/pubpub-zz/ppInk/files/6068375/ppInk2.zip)

**Comment by lucacuccu3x8** [comment]
ha! Great! thank you !
If I may suggest please:
Perhaps a multi-functional use of the mouse wheel, please?
other than scale up and down the width of the pen, 
is it possible to add an optional setting to select the Pen (pen 1, pen 2, pen3, ..) with the wheel of the mouse instead, please?
- it will avoid going up and down in the screen everytime you need to select a different pen. (I know hotkeys are an option, but messy alright!)  - I think the mouse wheel is a very convenient and fast selector. 
What do you think?

**Comment by pubpub-zz** [comment]
have a look to this issue and its fix : #49

**Comment by lucacuccu3x8** [comment]
sorry pupu. 
I've edited the comment before looking at your reply already.
Please check the first part of my early meassge.
thank you!

**Comment by pubpub-zz** [comment]
> One thing though - I've noticed that now the "switches between mouse and pointer and drawing", doesn't work properly now.
> When recalling the mouse pointer, The drawing stays while the bar minimizes - now the only way to get the mouse back is either

can you pls describe the exact actions you are doing

**Comment by lucacuccu3x8** [comment]
I'm using the GlobalHotkey(starts drawing, switches between the mouse pointer and drawing) -
 it doesn't give you back the mouse now, it only minimizes the ppink toolbar yet still drawing.
While before, it uses to minimize the toolbar and giving you back the mouse? 
------
regarding the fix #49 
sorry for the ignorance but what key is a D1? 
do I need that pink.zip you posted in there, for it to work? or is the feature included in your latest zips?
thanks

**Comment by lucacuccu3x8** [comment]
sorry for the caps

**Comment by pubpub-zz** [comment]
> regarding the fix #49
> sorry for the ignorance but what key is a D1?
> do I need that pink.zip you posted in there, for it to work? or is the feature included in your latest zips?
> thanks
D1 used to be the name for numeric key 1 on top line. It can be any key just , put the same hotkey for both pen 0 and pen 1

**Comment by lucacuccu3x8** [comment]
Thanks pubpub-zz
the mouse wheel doesn't work with me - nevermind
Have you noticed the Global Key issue please?

**Comment by pubpub-zz** [comment]
> I'm using the GlobalHotkey(starts drawing, switches between the mouse pointer and drawing) -
> it doesn't give you back the mouse now, it only minimizes the ppink toolbar yet still drawing.
> While before, it uses to minimize the toolbar and giving you back the mouse?

I've detected some bugs in version 1.4 that were fixed and released in 1.5. It is also in the evaluation version I've sent earlier on this post. Can you check with both ?

Thx

**Comment by lucacuccu3x8** [comment]
The 1.5.0.0 doesn't have it. ( but with the autofade settings no persisting)
The zip you sent me here with the autofade persisting fix, has this bug of the global key now.

**Comment by pubpub-zz** [comment]
> the mouse wheel doesn't work with me - nevermind

What do you mean not working ?

> The 1.5.0.0 doesn't have it. ( but with the autofade settings no persisting)
> The zip you sent me here with the autofade persisting fix, has this bug of the global key now.

OK  will review the code

**Comment by pubpub-zz** [comment]
Can you send me your ini files from the version which has the issue pls

**Comment by lucacuccu3x8** [comment]
![Annotation 2021-03-03 152217](https://user-images.githubusercontent.com/9900115/109828141-456f5580-7c34-11eb-94ed-c9c39eba819e.png)

**Comment by lucacuccu3x8** [comment]
that's the version where a trojan is flagged and where the Global Key doesn't work as before
![Annotation 2021-03-03 152341](https://user-images.githubusercontent.com/9900115/109828449-8a938780-7c34-11eb-90bd-4237826e9c26.png)

**Comment by pubpub-zz** [comment]
about detection, I've reported the issue to microsoft and it is confirmed to be a false detection
![image](https://user-images.githubusercontent.com/4083478/109881438-9739cf00-7c78-11eb-99d9-68ed8af76bff.png)

**Comment by pubpub-zz** [comment]
about the hotkey problem, I can not reproduce the problem. 😞 
here is a video where I'm using carnac( https://github.com/Code52/carnac/releases/tag/2.3.13 ) to display my keyboard actions:

https://user-images.githubusercontent.com/4083478/109882909-e1bc4b00-7c7a-11eb-9252-ef44f21469e8.mp4

(I've used the FFMPEG option to manage the recording, and I've just seen that it hides the close button - oops to be fixed)


I've tried the shortcut and also with the mouse (click on pointer button and undock)

Can you confirm you have the same behavior, else can you provide your ini files

**Comment by lucacuccu3x8** [comment]
Hi ppInk - 
I got so many version of ppInk now,  that I'm overwhelmed and confused - 
anyway, your version sent here earlier (ppInk28.zip) seems to respond well.
But... (sorry!)
The mouse wheel pen-selection setting (same value for each pen) seems to not respond to me.
Here's my whole zip copy(with all my settings) back to you 
[ppInk myini files.zip](https://github.com/pubpub-zz/ppInk/files/6083604/ppInk.myini.files.zip)

**Comment by lucacuccu3x8** [comment]
Regarding the mouse wheel settings for scrolling up and down the pen
the hotkey works(in my case D1)
but how to use the Wheel of the mouse for it? (not the Mouse3 button, but the actual wheel up&down)
thanks

**Comment by pubpub-zz** [comment]
> 
> 
> Regarding the mouse wheel settings for scrolling up and down the pen
> the hotkey works(in my case D1)
> but how to use the Wheel of the mouse for it? (not the Mouse3 button, but the actual wheel up&down)
> thanks

My answer/proposal was not to say that you can use the mouse wheel to rotate between pens but to use one key to rotate through.

**Comment by lucacuccu3x8** [comment]
> > Regarding the mouse wheel settings for scrolling up and down the pen
> > the hotkey works(in my case D1)
> > but how to use the Wheel of the mouse for it? (not the Mouse3 button, but the actual wheel up&down)
> > thanks
> 
> My answer/proposal was not to say that you can use the mouse wheel to rotate between pens but to use one key to rotate through.

And I'm thankful for that as it works great.
I was only wondering if a feature for the mouse wheel could be implemented please?
Anyway, thanks for your amazing work and great support

**Comment by pubpub-zz** [comment]
This is a version with shift+mouse wheel to rotate pen:
[ppInk5a.zip](https://github.com/pubpub-zz/ppInk/files/6090606/ppInk5a.zip)

I've fixed also the issue with the cursor not being refreshed until you move

By the way any progress on the tests I've assked you for hotkey issue ?

**Comment by lucacuccu3x8** [comment]
Hi pp.
Although some hotkeys like the (clear, redo) are not immediately executed after pressing whatever key assigned(seems to be a delay), maybe it's only me. but Yes, the previous issue of the hotkey seems to be gone in the zip you posted here. 

regarding the mouse the pen selection with the mouse wheel.
Is it possible to have this feature without the use of shift+ , in exchange for the Width increase/decrease of the pen? please?
or intruding a setting in the "Options" that will dictate the use of the mouse wheel in such a way please?
thanks

**Comment by lucacuccu3x8** [comment]
Hi pp.
actually, my issue with the hotkey is back
please find here my zip with all my configurations:
[ppInk-5a.zip](https://github.com/pubpub-zz/ppInk/files/6097078/ppInk-5a.zip)
I'm using ctrl+alt+b to minimize ppink and get the mouse back to my control - 

https://user-images.githubusercontent.com/9900115/110239840-119c7480-7f41-11eb-9d6a-26ccf92adfb5.mp4

**Comment by lucacuccu3x8** [comment]
as you can see in the clip, the hotkey minimizes ppInk but doesn't release the mouse, it still draws.

**Comment by pubpub-zz** [comment]
can you send your ini files pls

**Comment by lucacuccu3x8** [comment]
[ppInk-5a.zip](https://github.com/pubpub-zz/ppInk/files/6097268/ppInk-5a.zip)

**Comment by pubpub-zz** [comment]
a) Globalhotkey issue:
I  think I've found adn fix the problem 
b) Pen rotating : 
As an alternative to pressing shift, you can use CapsLock : if toggled on, you will rotate through pen (too many will be a mess for me)
[ppInk8.zip](https://github.com/pubpub-zz/ppInk/files/6104676/ppInk8.zip)

Also includes fixes for #60,#62,#63

**Comment by lucacuccu3x8** [comment]
Thank you pubpub

Please allow me a couple of days to test it during live sessions, to check for persistence.
until then, thank you for your great work and patience

**Comment by pubpub-zz** [comment]
take your time
for your information I've issued a new interim version in 
https://github.com/pubpub-zz/ppInk/issues/63#issuecomment-796246634

**Comment by lucacuccu3x8** [comment]
> take your time
> for your information I've issued a new interim version in
> [#63 (comment)](https://github.com/pubpub-zz/ppInk/issues/63#issuecomment-796246634)

Thank you pubpub.
unfortunately CAPsLock on isn't convenient, as I need to type commands in terminals while doing live presentations. CAP on is a bother and it makes the whole thing confusing. Sorry, might be only me and my issue only, so please don't take it on a wrong way.
I though about the NUM lock, yet not convenient for the same reason thatI'm typing and switching off and on ppInk very often during my  live sessions.
Please, Is there any chances to have the PenRotating function as something you could turn on-off for good, 
in the "Options - ppInk", instead of the width(that I never happen to use), for e.g. here: (or whatever you think fit)

![Screenshot 2021-03-13 152231](https://user-images.githubusercontent.com/9900115/111034969-f5507a00-840f-11eb-850c-2bc1b96cddcb.jpg)

**Comment by pubpub-zz** [comment]
Hi @lucacuccu3x8,
    I'm sorry that My proposal which was easy to code does not fit your need. Making the mousewheel to be so customizable is something which will require much more work : the mouse wheel changing the size is something I do not want to loose, therefore coding alternatives will be extra job. I will open a new issue with your request looking for other users opinion

**Comment by lucacuccu3x8** [comment]
Hi pubpub, 
I meant to implement an option to move/change how we control "changing size", not to loose it entirely. 
but no problem at all. I can live with that.
thank you

**Comment by pubpub-zz** [comment]
@lucacuccu3x8 
     The latest exchange were no more about the original point which is now to be closed for me. do you agree ?

**Comment by lucacuccu3x8** [comment]
yes. thank you.
