### ISSUE TITLE
About the oval

### ISSUE THREAD

**Issue by chrisj0192** [pubpub-zz/ppInk#60]
Hello my friend! Excuse me, I'd like to make a request if you don't mind, could you please modify the coordinate system about the oval?, when I start drawing an oval I've noticed that the coordinate system is different when I draw a rectangle. I don't know if you noticed that issue but I'd like you to modify that coordinate with respect to the oval in order to draw in the same way as the rectangle. Thanks in advance. I really like your program!. I would like to modify that issue but my programming knowledge is poor :'(.

**Comment by pubpub-zz** [comment]
The use case I wanted to cover is you click in the middle of an area and then you extend the oval to surround the object/area.based on my experience this is more difficult to do this with open then drawing with 2 corners:
I've used the shift key to match your use case, but keeping the magnetic effect (From my test it looks acceptable)
[ppInk28.zip](https://github.com/pubpub-zz/ppInk/files/6056949/ppInk28.zip)
Your opinion ?

**Comment by pubpub-zz** [comment]
@chrisj0192 
can you provide your opinion and eventually close this issue ?

**Comment by chrisj0192** [comment]
I apologize for not having responded to your comment earlier I've been very busy these last days with my work. I tested the new feature, but I've noticed a new bug with the width pen, it doesn't updated when I set it at the time, later when I move the mouse cursor it updates. it's weird because it didn't happen before this update. About the new oval function I think it's much better to start drawing with the shift key because when I teach geometry (for example) it's easier to inscribe a circumference inside a square. that's the reason why I like that function hehe and thanks for your implementation. A question, do you think I could set that new function with a hotkey? it's a bit difficult to hold shift key with alt key at the same time for me :'(. Thanks in advance

**Comment by pubpub-zz** [comment]
I've implemented right click in order to distinguish the different ref points : this applies to Rect / Oval and Arrow (switching beetwen arrow direction)

[ppInk8.zip](https://github.com/pubpub-zz/ppInk/files/6104676/ppInk8.zip)

Also includes fixes for #59,#62,#63

**Comment by chrisj0192** [comment]
Wow! the left and right clic funcions to change the different ref points of the oval, rectangle and arrow are amazing! Thanks a lot my friend! that's all I needed!. Regarding other functions (#59, #62, #63) are incredible too. I think that if your program could type with an intuitive text function on the screen (I mean without a text box, just right on the screen) I can assure you that your program would be the best program I've seen so far. For now it's enough for me. a million thanks. I'll close this issue.
