### ISSUE TITLE
Exe

### ISSUE THREAD

**Issue by TheVrestin** [pubpub-zz/ppInk#61]
There is no exe file

**Comment by pubpub-zz** [comment]
The program is not installed by an exe in order to be portable: you have to download the ppInk.zip file:
https://github.com/pubpub-zz/ppInk/releases/download/1.5beta1/ppInk.zip
and unzip it where you want. the ppink.exe is inside 😊

**Comment by TheVrestin** [comment]
Where is the exe I only see a exe.config or exe.manifest

**Comment by pubpub-zz** [comment]
![image](https://user-images.githubusercontent.com/4083478/109569665-13051180-7ae9-11eb-8c0c-2e848a36a8d8.png)

**Comment by TheVrestin** [comment]
![image](https://user-images.githubusercontent.com/20113939/109570650-ac80f300-7aea-11eb-85fe-b9cb8d3245e1.png)

**Comment by TheVrestin** [comment]
Not there

**Comment by pubpub-zz** [comment]
I think  I've understood : Are you looking in the releases ? exe is not stored in the repo

**Comment by pubpub-zz** [comment]
have you been able to find the zip package for deployement?
