### ISSUE TITLE
Text tool persistent when selected; not allowing switching to other tools using shortcuts

### ISSUE THREAD

**Issue by eamayreh** [pubpub-zz/ppInk#62]
@pubpub-zz 
Hey there. I just noticed that the text tool stays selected until you manually select another tool with mouse cursor (it does not allow you to change to another tool using shortcuts). 
Here are the steps I took:
1. I select text tool to write something - finished writing
2. I want to switch to another tool using shortcuts, for example (R) to draw rectangle, arrow, etc.
3. Result: it will not switch to anything else in same session; also if you click global hotkey switch (it closes toolbar, then when u press global key again, toolbar opens but is still stuck on text tool) you have to click x or esc key then you can select another tool using shortcuts.

Is this normal or am I missing something? Thanks.

PS. When first opening toolbar, I cannot select text tool using shortcut (T); So if I wanted to use it right away, first I have to use pen, then I can select text tool using shortcut (T); the other option if I want to type text first is to select the text tool by mouse.

**Comment by pubpub-zz** [comment]
You are right  : this is a bug.
Can you this version :
[ppInk5b.zip](https://github.com/pubpub-zz/ppInk/files/6093561/ppInk5b.zip)

I think your post-scriptum should be solved too

**Comment by eamayreh** [comment]
> 
> 
> You are right : this is a bug.
> Can you this version :
> [ppInk5b.zip](https://github.com/pubpub-zz/ppInk/files/6093561/ppInk5b.zip)
> 
> I think your post-scriptum should be solved too

@pubpub-zz 
Pressing **T** when first opening the toolbar selected text input tool (so it seemed fixed, but issue occurred again at end of video). 

Still, after using tool, I can't switch to other tools via shortcuts.

And at end of video, it did not allow selecting text tool at start, so I had to draw anything, then text tool was selected using shortcut (T)



https://user-images.githubusercontent.com/61389799/110180818-267aea00-7e13-11eb-99d5-409468ef2119.mp4

**Comment by eamayreh** [comment]
@pubpub-zz 
Also another idea, what if we could start typing immediately on screen when using text tool, without having to type in text input box then press "ok" to have text drawn on screen? Then if you want to use another tool while text input is active, you can hold shift (for example) and press the shortcut for the other tool you want to use?

**Comment by pubpub-zz** [comment]
> PPink.problem.mp4

thanks for the very well documented test case I will analyse that tomorrow



> Also another idea, what if we could start typing immediately on screen when using text tool, without having to type in text input box then press "ok" to have text drawn on screen? Then if you want to use another tool while text input is active, you can hold shift (for example) and press the shortcut for the other tool you want to use?

It has been already asked to not have the text box, but the implementation is too complex. What I can propose is to validate the text with ctrl+return : this should help typing

**Comment by pubpub-zz** [comment]
Ctrl+return implemented

[ppInk8.zip](https://github.com/pubpub-zz/ppInk/files/6104676/ppInk8.zip)

Also includes fixes for #60,#59,#63

**Comment by eamayreh** [comment]
This issue has been addressed in #63
