### ISSUE TITLE
ppInk crash due to clipart image no longer available

### ISSUE THREAD

**Issue by eamayreh** [pubpub-zz/ppInk#64]
@pubpub-zz 

I ran into this error today after deleting an image I had used to test clipart. After testing, I deleted the image through windows file manager, not from within ppInk clipart which caused it to crash, it wouldn't run again until the error was fixed.

I spotted the problematic string pointing to the deleted image in the config.ini and omitted it. Now it's working again. Demo of how error happens:

https://user-images.githubusercontent.com/61389799/110827595-e6968580-829e-11eb-9feb-347c562927c5.mp4

Maybe ppink can make a copy of the image in a folder it creates (e.g. clipart images) to avoid this error, or if it can check beforehand if the images loaded are available, if not it will remove them from clipart.

**Comment by pubpub-zz** [comment]
I knew this behavior and as the file was clearly readable I considered it was sufficient. As I did some fix/ehancement  covering your latests comments from #46, I've fixed also this. if a file is missing the error will allow you to carry on, remove the image from the clipart dlg and then save the new ini files
[ppInk11.zip](https://github.com/pubpub-zz/ppInk/files/6125711/ppInk11.zip)

**Comment by eamayreh** [comment]
> 
> 
> I knew this behavior and as the file was clearly readable I considered it was sufficient. As I did some fix/ehancement covering your latests comments from #46, I've fixed also this. if a file is missing the error will allow you to carry on, remove the image from the clipart dlg and then save the new ini files
> [ppInk11.zip](https://github.com/pubpub-zz/ppInk/files/6125711/ppInk11.zip)

@pubpub-zz Just tested the "from clipboard" function in Cliparts and it is working very well.
