### ISSUE TITLE
Add multiple snapshots in pointer mode for advanced drawing

### ISSUE THREAD

**Issue by eamayreh** [pubpub-zz/ppInk#65]
**Annotating an item in a menu in MS Word.**

I tend to annotate while recording to avoid having to use an editor afterwards. So I was trying to draw on the screen while I was in a menu in MS Word, and the mouse was over a specific sub-menu item that I wanted to highlight/point to. Here are the steps I took:
1. open MS Word
2. go to **Layout tab**
3. click on **Breaks**
4. hover the mouse over any item you want to annotate, e.g. **Next Page** without clicking
5. try to annotate that item (rectangle, arrow)
6. as soon as you call ppink, the list under "Breaks" rolls back; I tried to use the zoom-freeze but no luck too.

https://user-images.githubusercontent.com/61389799/110970227-3427f680-8362-11eb-8a0a-e1a0ecfb2bec.mp4

@pubpub-zz Any ideas how I can do this? My hope is to be able to avoid having to edit after recording, esp for short how-to videos.

**Comment by pubpub-zz** [comment]
@eamayreh, I like your use case
The issue is that Word closes the menu as soon as it looses focus. However this is my proposal would be as follow:
* enter pointer
* open the word menu
* make a fullscreen snapshot with very neutral keys such (ctrl+shift is a good candidate)
* carry on to next action and press again ctrl+shift again to make a second full screen snapshot and carry on as required
* etc
* when finished, disengage Pointer mode
* all the snapshots will be applied on top of each others (and other previous drawings hiding them) with the oldest on top
* Draw on top of the first drawing
* Make a snapshot with the required area
* with the eraser tool, delete the top image to display next capture
* complete / modify drawing and then do a new snapshot, ...

This will require the following change
* New : perform multiple fulllscreen snapshot in cursor mode with ctrl+shift
* New : draw snapshots on drawings when returning from pointer mode
* Enh : Engage a snapshot without closing when snapshot is long depressed (window mode will be transfer to long click on pointer button)
* Enh/Fix : delete the most ontop drawing and not the bottom one


Your opinion?

**Comment by eamayreh** [comment]
@pubpub-zz 
So this is how I ended up doing it with Snipaste running alongside PPInk... it's interesting doing it like this.
Here's how it looks:

https://user-images.githubusercontent.com/61389799/111016093-9d385a00-83b4-11eb-97f4-b37bdba04c53.mp4

**Comment by pubpub-zz** [comment]
Have a look to my proposal:
[ppInk14.zip](https://github.com/pubpub-zz/ppInk/files/6136642/ppInk14.zip)

    New : perform multiple fulllscreen snapshot in cursor mode with shift(hold) + ctrl(press twice) (you will have a ring to confirm capture)
    New : draw snapshots on drawings when returning from pointer mode
    Enh : Engage a snapshot without closing when snapshot is long depressed (window mode will be transfer to long click on pointer button)
    Enh/Fix : delete the most ontop drawing and not the bottom one

**Comment by eamayreh** [comment]
@pubpub-zz 
Can't complain; look how smooth the process is:

https://user-images.githubusercontent.com/61389799/111090958-1d3bfc80-853a-11eb-91fc-04e85ed18454.mp4

some observations:
- I really think the snapshot shortcut can use some tweaking, how about (_Shift_ or _Ctrl_) + **space**
- the image is a bit blurry (not a deal breaker but something to note)

I've got some other overall improvement ideas that I'll open in a separate issue.

The way this is right now, me likeeeeeeeee :D

**Comment by eamayreh** [comment]
@pubpub-zz 
tiny "undo" bug here :D  - doesn't happen if you use the eraser

https://user-images.githubusercontent.com/61389799/111096711-d0135700-8548-11eb-937c-a43eb3534817.mp4

**Comment by pubpub-zz** [comment]
> @pubpub-zz
> Can't complain; look how smooth the process is:

I love the way your are using it 😍

> I really think the snapshot shortcut can use some tweaking, how about (Shift or Ctrl) + space

I understand it is tricky but I need some 'neutral' keys that will not affect the other program (for example in your case, ctrl+space of shift+space, the menu will close before any capture can be done 😑)

>  the image is a bit blurry (not a deal breaker but something to note)

I have some ideas but still under analysis for the moment.

> if when you take the snapshot and draw ONLY one thing, then decided to press undo and draw another thing, the snapshot will disappear altogether (that occurs when you click undo after the first thing you have drawn on that image), and you will have to do the snapshot thing all over again.

I forgot to save the undo stack after pasting the images😖... beta version available:
[ppInk15.zip](https://github.com/pubpub-zz/ppInk/files/6144926/ppInk15.zip)

**Comment by eamayreh** [comment]
> 
> 
> > @pubpub-zz
> > Can't complain; look how smooth the process is:
> 
> I love the way your are using it 😍
> 
> > I really think the snapshot shortcut can use some tweaking, how about (Shift or Ctrl) + space
> 
> I understand it is tricky but I need some 'neutral' keys that will not affect the other program (for example in your case, ctrl+space of shift+space, the menu will close before any capture can be done 😑)
> 
> > the image is a bit blurry (not a deal breaker but something to note)
> 
> I have some ideas but still under analysis for the moment.
> 
> > if when you take the snapshot and draw ONLY one thing, then decided to press undo and draw another thing, the snapshot will disappear altogether (that occurs when you click undo after the first thing you have drawn on that image), and you will have to do the snapshot thing all over again.
> 
> I forgot to save the undo stack after pasting the images😖... beta version available:
> [ppInk15.zip](https://github.com/pubpub-zz/ppInk/files/6144926/ppInk15.zip)

Thanks for the fix. I completely forgot we needed keys that wouldn't close the menu, 😅. Alright, so how about pressing the (**`**) key twice, which is located to the left of number 1 on keyboard? Or maybe **Ctrl** twice (without shift)?

Is there any way I can save my config because each time I try a new version I adjust settings every time 😶. I have my hotkeys and pens.ini saved, but I don't know if I can do that with config.ini?

**Comment by pubpub-zz** [comment]
> Thanks for the fix. I completely forgot we needed keys that wouldn't close the menu, 😅. Alright, so how about pressing the (**`**) key twice, which is located to the left of number 1 on keyboard? Or maybe **Ctrl** twice (without shift)?

set word in standard page edition,typing text, ` creates a character : it is not neutral... Even Print screen is not working for me(closing context menu)
 
> Is there any way I can save my config because each time I try a new version I adjust settings every time 😶. I have my hotkeys and pens.ini saved, but I don't know if I can do that with config.ini?

Can you please tell me which  setting is not saved : it looks fine for me

**Comment by eamayreh** [comment]
> 
> 
> > Thanks for the fix. I completely forgot we needed keys that wouldn't close the menu, 😅. Alright, so how about pressing the (**`**) key twice, which is located to the left of number 1 on keyboard? Or maybe **Ctrl** twice (without shift)?
> 
> set word in standard page edition,typing text, ` creates a character : it is not neutral... Even Print screen is not working for me(closing context menu)
> 
> > Is there any way I can save my config because each time I try a new version I adjust settings every time 😶. I have my hotkeys and pens.ini saved, but I don't know if I can do that with config.ini?
> 
> Can you please tell me which setting is not saved : it looks fine for me

The settings that I tend to set again when testing a new version are the default font for text and number chips, arrow head aperture, and default arrow head at start; otherwise, there isn't any problem migrating my hotkeys and pens since they are saved in separate files.

**Comment by pubpub-zz** [comment]
about ctrl twice, I'm thinking about some options to configure it

options, I puzzled : It is working fine for me (tested with [ppInk15.zip](https://github.com/pubpub-zz/ppInk/files/6144926/ppInk15.zip) ) both with saving and restarting ppInk.exe

can you check the content of config.ini to confirm if the problem is at saving or at restoring

**Comment by eamayreh** [comment]
> 
> 
> about ctrl twice, I'm thinking about some options to configure it
> 
> options, I puzzled : It is working fine for me (tested with [ppInk15.zip](https://github.com/pubpub-zz/ppInk/files/6144926/ppInk15.zip) ) both with saving and restarting ppInk.exe
> 
> can you check the content of config.ini to confirm if the problem is at saving or at restoring

There isn't any problem with saving options, it's working well and the options are saved **once you configure** them. What I mean is, when you send me for example (ppInk v2) and I have (ppInk v1-which is old), I can copy my pen.ini and hotkeys.ini from old ppInk folder to new (ppink v2) folder and overwrite these files to be able to use my saved pens and hotkeys that I had in v1.

However, I was referring to the options like (font for text and numbering, arrow options); can I just copy old config.ini, which has the font I use and arrow options, and overwrite the new config.ini file? I hope it is clear now.

**Comment by pubpub-zz** [comment]
There is no check about versions. If a parameter is missing the default value is used.also the parameter if modified will not be stored during saving. From code reviews(I have not done any test personally) parameters can be put in any files (same code to load all of them)
Gink was like that and I don't want to change that. Transfering ini files in any cases will not be harmful 😊.

**Comment by pubpub-zz** [comment]
@eamayreh 
I've finally have been able to finish coding:
a few fixes
shortcut for snapshot in pointer mode configurable (saved in hotkeys.ini)
blurry image fixed

Can you test it please

**Comment by eamayreh** [comment]
> 
> 
> @eamayreh
> I've finally have been able to finish coding:
> a few fixes
> shortcut for snapshot in pointer mode configurable (saved in hotkeys.ini)
> blurry image fixed
> 
> [ppInk18.zip](https://github.com/pubpub-zz/ppInk/files/6164036/ppInk18.zip)
> 
> Can you test it please

Of course, can't wait 😍

**Comment by eamayreh** [comment]
@pubpub-zz 
alright, so here's what I found:
- snapshots are now crisp!
- shortcuts to take pointer snapshot work well - I'm now trying (hold Ctrl) & press Shift twice 🙂

Here are a few things I ran into while testing:

1. input field not always highlighted (selected) when switching between pens/drawing and pointer, and when that happens you cannot start typing right away, instead you must select the "text" manually and then type what you want.
2. edit shortcut opens edit dialog (needs fixing like numbered chip shortcut) instead of activating edit tool and allowing you to choose element on canvas to edit (right clicking it should open dialog, but choosing it via shortcut should allow you to select element on drawing canvas to edit).

demo: **Input field not always selecting "text"**

https://user-images.githubusercontent.com/61389799/111691617-2b8a6100-8837-11eb-9c55-3b1000156529.mp4

demo: **Edit shortcut should allow selecting element to edit**

https://user-images.githubusercontent.com/61389799/111691965-8ae87100-8837-11eb-965c-968ed1d75f0f.mp4

**Comment by pubpub-zz** [comment]
[ppInk18b.zip](https://github.com/pubpub-zz/ppInk/files/6167118/ppInk18b.zip)

The two issues should be solved...

**Comment by pubpub-zz** [comment]
what about closing this issue?

**Comment by eamayreh** [comment]
> 
> 
> what about closing this issue?

Sure thing.

**Comment by MathieuCGit** [comment]
Hi guys, 

I know this issue is closed but I can't figure how to do this ! I just want to live draw a rectangle  on a dorp-down menu. What are the steps ? What are your configurations ?

thanks

**Comment by eamayreh** [comment]
@MathieuCGit
Hey there. So I've just tried this and it still does work. Here's how I have it set up, I hold Ctrl and hit Shift twice (make sure the hotkeys are set up accordingly in settings before you try it - you can of course use other hotkeys if you like). So once you're on the menu you want to annotate, use the hotkeys you assigned (you don't get a sound or anything to indicate that you have done so successfully), so all you need to do then is to switch again to drawing mode and select the tool you want and then annotate the part you want in the drop-down menu.

Hope this helps. Let me know if you still have problems getting it to work.

![image](https://user-images.githubusercontent.com/61389799/145613319-f7364dc7-fc32-4f77-8d47-352f24cf526f.png)

**Comment by MathieuCGit** [comment]
Hello @eamayreh 

Thanks for your reply, it helps, but it still doesn't work on my side :-( 

Could you please also post a screenshot of your general tab ?

regrads

**Comment by pubpub-zz** [comment]
@MathieuCGit
Start Inking.
**Engage Pointer Mode**
Open you menu
(with the default setup) press and hold shift ; press and release twice ctrl; a pop-up notification should appear to confirm that a snapshot occured ; release shift
You can repeat this capture as often as you want.
when you undock the snapshots are posted.
Are you sure you are in pointer mode when you are doing your snapshots ?
Can you send your ini files to confirm (you have already downloaded mine with the beta you have tested in #164)

**Comment by MathieuCGit** [comment]
Following your instruction with a totaly new configuration from the zip file you previously sent to me, I got this : 

[https://imgur.com/a/3NqbJwS](https://imgur.com/a/3NqbJwS)

**Comment by eamayreh** [comment]
@MathieuCGit 

https://user-images.githubusercontent.com/61389799/145658307-71bd158d-8e49-46cd-86d0-6d9f901e075d.mp4

Be sure to select the correct mode for the shape you want to use (notice when I click on the rectangle shape more than once), as clicking it or using their shortcut by mistake will cycle between the different modes for that shape.

Side note: which software do you use for displaying keystrokes on the screen?

**Comment by pubpub-zz** [comment]
> Following your instructions with a totaly new configuration from the zip file you previously sent to me, I got this :
> 
> https://imgur.com/a/3NqbJwS
> 
> Regarding pointer engagement, I just uncheck "Engage Pointer and Auto-Fold with Alt+Tab" : https://imgur.com/a/9RXwStA
> 
> I also uncheck show floating window and use the dock bar vertricaly with 4.0%

At first sight, it seems to work : the screen has been captured during the shlft+ctrlx2 and then pasted for edition when disengaging pointer mode. no ?

**Comment by MathieuCGit** [comment]
@eamayreh  

> "Be sure to select the correct mode for the shape you want to use (notice when I click on the rectangle shape more than once), as clicking it or using its shortcut by mistake will cycle between the different modes for that shape."

Okaaayyy I was totaly missing this point. PPink is a very powerfull tool but really complex to learn and as I was using shortcuts without seeing the toolbar, I use "r" shortcut in a wrong way.

> Side note: In your recordings, which software do you use for displaying keystrokes on the screen?

I'm using mousetrack from : [http://www.swordsoft.idv.tw/mousetrack/](http://www.swordsoft.idv.tw/mousetrack/)

@pubpub-zz 

> At first sight, it seems to work : the screen has been captured during the shlft+ctrlx2 and then pasted for edition when disengaging pointer mode. no ?

Yes, I now have a better understanding of ppink behaviours, I have to practice it a bit to be easy with for live use but everything seems to work.
