### ISSUE TITLE
Add sub toolbars to display next buttons

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#66]
I'm not sure where I can make suggestions, but I just wanted to to suggest a slight change to the interface like shown in the image (like grouping icons according to functionality, so when you click on an icon, it opens up the other relevant tools).

If it is possible to implement, I think it would make PPink interface easier to use; and there won't be need for as many shortcuts (short click, long click, etc.). 

This is from my point of view since I teach and rely on using annotation tools a lot. I really appreciate everything PPink is offering and hope it becomes a top choice for annotation.

![image](https://user-images.githubusercontent.com/61389799/109825140-31325500-7c42-11eb-8604-fa9980750c35.png)

_Originally posted by @eamayreh in https://github.com/pubpub-zz/ppInk/issues/17#issuecomment-789780041_

**Comment by pubpub-zz** [comment]
I leave this open, but this will take lot of work. maybe for a next version

**Comment by eamayreh** [comment]
> 
> 
> I leave this open, but this will take lot of work. maybe for a next version

I just noticed that the sub menus in Epicpen will expand when the mouse hovers over them, but in Snipaste when you click them. These are just some suggestions if you find yourself in the mood for an upgrade 😎. I like how ppInk is right now - it's pretty handy and practical and offers so much!

I'm thinking of making a video about ppInk to show the features it packs? Or maybe shorter videos showcasing each set of functions.

**Comment by pubpub-zz** [comment]
Hi @eamayreh,

> I'm thinking of making a video about ppInk to show the features it packs? Or maybe shorter videos showcasing each set of functions.

I love your idea and you are far better than I am. For me posting videos directly on Youtube could be a good idea to give you a good visibility, but it's up to you.

For the next release I'm preparing I would like to use some of your videos for snapshot. Are you OK ?

**Comment by eamayreh** [comment]
> I love your idea and you are far better than I am. For me posting videos directly on Youtube could be a good idea to give you a good visibility, but it's up to you.

haha, I'm still new to all this video recording thing; and I'm not much of a Youtuber ( I just tend to upload when needed), so I thought making video about ppInk would give it more more visibility, which it very much deserves :D

> For the next release I'm preparing I would like to use some of your videos for snapshot. Are you OK ?
Of course, feel free to use any of my content any way you like.

**Comment by eamayreh** [comment]
> I love your idea and you are far better than I am. For me posting videos directly on Youtube could be a good idea to give you a good visibility, but it's up to you.

Thanks for the compliment, I'm still new to all this recording stuff and am not much of a real Youtuber; I just film to explain something.



> For the next release I'm preparing I would like to use some of your videos for snapshot. Are you OK ?

Sure, feel free to use any of my content any way you like.

**Comment by pubpub-zz** [comment]
this is a very first release not yet fully implemented with secondary toolbar. what is your feeling about?
[ppInksbtools1.zip](https://github.com/pubpub-zz/ppInk/files/6258584/ppInksbtools1.zip)

**Comment by eamayreh** [comment]
Aha, this looks interesting! I'll check it out and get you some feedback :D

**Comment by eamayreh** [comment]
@pubpub-zz I hope you're doing well. 

Here's what I got from testing this (actually I've been taking notes even before this and intended to share them with you)

Secondary toolbar notes:
- socondary toolbar persistent when dock auto-fold selected
- what is the function of pin in secondary toolbar (use case)?
- tooltips language on secondary toolbar needs linking relevant translation (empty, color filled, etc.)

Suggestions for secondary toolbar:
- I think the toolbar this way makes it a bit more bulky (I mean it's taking more than is needed since when you select the mode you want on 2nd toolbar it is reflected in the icon on main toolbar, so not sure how I feel about it) 
- maybe if grouping main shapes is possible like this (for example) - as discussed in this issue op:
 group 1:  line - rectangle- circle; group 2: arrow; group 3: cliparts; group 4: text - number chip

As for the other notes, I'll open another issue for suggestions/improvements.

**Comment by pubpub-zz** [comment]
thanks for your feedbacks,
Keep your suggestions in this issue : secondary tool is not yet ready as as reflected in your comments. I agree with you the operability needs improvement/review.

> * secondary toolbar persistent when dock auto-fold selected

Agree : to be fixed
> * what is the function of pin in secondary toolbar (use case)?

I thought about having this function to prevent the toolbar from closing to pickup a new tool without coming back to main toolbar but currently it is useless.
> * tooltips language on secondary toolbar needs linking relevant translation (empty, color filled, etc.)

I'm surprised because it is customizable/ and they are reflecting my first draft.


> * I think the toolbar this way makes it a bit more bulky (I mean it's taking more than is needed since when you select the mode you want on 2nd toolbar it is reflected in the icon on main toolbar, so not sure how I feel about it)

implemented this way it allow direct access to fillings
> * maybe if grouping main shapes is possible like this (for example) - as discussed in this issue op:
>   group 1:  line - rectangle- circle; group 2: arrow; group 3: cliparts; group 4: text - number chip

without expanding the different tools this looks like the main toolbar, but as you are not yet convinced of leaving thr toolbar like that,,, need more reflection...

**Comment by pubpub-zz** [comment]
>     * pen **fade modifier key** when drawing shape such as (ctrl/alt/shift)
>       if you want to draw arrow or any shape that fades, select shape and hold shift/ctrl while drawing so that it disappears afterwards, then pen is back to normal (this way you don't have to select fade for each pen in options and remember which pen has fade enabled and which not - use case: recording /live lesson/presentation.

I'm personnaly use a lot the ctrl/alt/shift (that's why I've developped them 😁)  but I understand that fading is often forgotten : I propose to add a visual(customisable mark) : see beta attached
[ppInkFadingTag.zip](https://github.com/pubpub-zz/ppInk/files/6285881/ppInkFadingTag.zip)



>     * mouse **right click extra functionality**: when mouse hovers over shapes, red dots become visible (like when selecting move on main toolbar) or these dots can appear when holding a modifying key, and you are able to move that shape holding right click and dragging it (no need for move icon in main toolbar); also can be extended for duplicate (copy)/move/ edit - hold (shift/ctrl/alt) while holding right click to copy and drag item. This feature needs some review to make it practical.

despite mouse right click has started to get some functions, I'm personnaly like the alt+ Hotkey(Move or clean...) is quite quick and may just perhaps require a little of time to get used to it.

**Comment by pubpub-zz** [comment]
I think this issue can be closed now, agree?

**Comment by eamayreh** [comment]
Sure.
