### ISSUE TITLE
PPink toolbar self-activates drawing mode

### ISSUE THREAD

**Issue by eamayreh** [pubpub-zz/ppInk#67]
@pubpub-zz 
So this is what happened after a video I recorded. PPink was still in drawing mode, but after I finished recording I hit esc on keyboard to switch to using cursor. Now when I open any folder then close that folder, ppink activates drawing mode by itself:

https://user-images.githubusercontent.com/61389799/111016451-c5c15380-83b6-11eb-8384-d13a97d16d0b.mp4

edit: this behavior is happening even when I open a program and then close it --> toolbar activates itself again

Could it be that another program is doing something to activate it? Or window mode is running somehow? How do I disable window mode for PPink?

**Comment by eamayreh** [comment]
This is driving me crazy (◕︵◕) I've uninstalled any suspect apps (even dexpot) but the issue is still there! Every time I close something I'm back to drawing mode. @pubpub-zz any thoughts or advice on how to debug this?

**Comment by eamayreh** [comment]
@pubpub-zz 
I think I found what's causing this. It seems to be the tiny floating window; I disabled it in options and it's running properly now. I'll be testing it a bit and then will have this closed today if all goes well.

**Comment by pubpub-zz** [comment]
Sorry for late answer : You're right
Find attached this version for evaluation
[ppInk14a.zip](https://github.com/pubpub-zz/ppInk/files/6136796/ppInk14a.zip)

**Comment by eamayreh** [comment]
> 
> 
> Sorry for late answer : You're right
> Find attached this version for evaluation
> [ppInk14a.zip](https://github.com/pubpub-zz/ppInk/files/6136796/ppInk14a.zip)

Np. Yes, this version is working fine.
