### ISSUE TITLE
Mouse Wheel to rotate between pens

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#69]
from @lucacuccu3x8 
-------------------------------------------------------
Also,
If I may suggest please:
Perhaps a multi-functional use of the mouse wheel, please?
other than scale up and down the width of the pen, 
is it possible to add an optional setting to select the Pen (pen 1, pen 2, pen3, ..) with the wheel of the mouse instead, please?
- it will avoid going up and down on the screen every time you need to select a different pen. (I know hotkeys are an option, but messy alright!)  - I think the mouse wheel is a very convenient and fast selector. 
What do you think?

_Originally posted by @lucacuccu3x8 in https://github.com/pubpub-zz/ppInk/issues/59#issuecomment-789651020_

**Comment by pubpub-zz** [comment]
Currently the mousewheel implements:
* mousewheel only : change pen width
* ctrl+mousewheel : change zoom factor in zoom mode
* shift(or caps lock on)+ mousewheel : rotate through pens

also you can use the shortcuts for pen0-9
finally if shortcut for pen0 is identical to pen1, you will be able to rotate through all pens with this unique pen shortcut

**### for every one, can you tell me if the current implentation is sufficient ?**

**Comment by eamayreh** [comment]
At first I thought there were too many hotkeys to memorize, but since we would already be in drawing mode with the shape/tool selected, you kind of get used to selecting pens/colors via their numbers; I think I prefer that over clicking the same shortcut until I get to the pen I want to use.

**Comment by lucacuccu3x8** [comment]
I think the "rotate through pens" is more important than change pen width. once the width is set, I found myself in rare occasion when in need to change the width. yet more often I need to change pen as now every pen could hold different color and fading ..
only thought.

**Comment by eamayreh** [comment]
> 
> 
> I think the "rotate through pens" is more important than change pen width. once the width is set, I found myself rarely in occasion when in need to change the width... especially while doing presentations (messy!)
> yet more often, I need to change pen, considering that now every pen could hold different color and fading
> 
> so I vote for
> **mousewheel only : rotate through pens**
> shift(or caps lock on)+ mousewheel : change pen width

@pubpub-zz @lucacuccu3x8  
How about adding this to the hotkey options if it doesn't need much coding? That way it's up to the users to choose whatever suits their needs.

**Comment by lucacuccu3x8** [comment]
I stick with the **mousewheel only : rotate through pens**  👍🏻

**Comment by pubpub-zz** [comment]
I've finally encode option to swap between mousewheel (That I do need) and shift+mousewheel
[ppInk14.zip](https://github.com/pubpub-zz/ppInk/files/6136642/ppInk14.zip)

@lucacuccu3x8 , you owe me more stars ... 😉 😄

**Comment by lucacuccu3x8** [comment]
ha-ha that's great pubpub. Thank you!
Settings are not persisting, though after either a reboot or a re-launch of the app entirely (after the process was killed)
in particular the width setting for the pen0 (default or last selected?), falls back to default
I normally set pen0 with 300width and 170 alpha (as a marker with fadings)
what do you think?

Try this combination please:

![Screenshot 2021-03-14 171721](https://user-images.githubusercontent.com/9900115/111077543-2f417f00-84e9-11eb-9bff-95263923686b.jpg)
****

1. launch the app -> save the new settings -> test it, working ok!
2. Switch between mouse pointer and drawing back with hot-key : working ok !
3. ESC the app -> re-engage the app with the Global Hotkey(Ctrl+Alt+G) -> Pen0(gets its width shrunk, back to default)
4. 2. Switch between mouse pointer and drawing back with hot-key : same

5. Kill the app entirely ( a system reboot scenario for example..)
6. Re-launch the app from fresh -> some previous user settings are not there or fall back to default - for e.g.  the newly introduced feature of the mouse wheel and fadings.

what do you think?

Thank you

**Comment by pubpub-zz** [comment]
You right : add in config.ini
Inverse_MouseWheel_Control=true

**Comment by pubpub-zz** [comment]
>    3. ESC the app -> re-engage the app with the Global Hotkey(Ctrl+Alt+G) -> Pen0(gets its width shrunk, back to default)

This is an old behavior and I agree it is not nice. 
[ppInk14b.zip](https://github.com/pubpub-zz/ppInk/files/6137659/ppInk14b.zip)

>   4. Switch between mouse pointer and drawing back with hot-key : same

I think it is because the width was reduced before

>   6.Re-launch the app from fresh -> some previous user settings are not there or fall back to default - for e.g. the newly 

introduced feature of the mouse wheel and fadings.
As said Inverse_MouseWheel_Control was missing in config.ini, reintroduced

**Comment by lucacuccu3x8** [comment]
Thank you pubpub,
Seems great now.
Please allow me a few days for test
Thank you again

**Comment by pubpub-zz** [comment]
no prob

**Comment by lucacuccu3x8** [comment]
great one. no probs so far.
thank you pubpub

**Comment by lucacuccu3x8** [comment]
![111077543-2f417f00-84e9-11eb-9bff-95263923686b](https://user-images.githubusercontent.com/9900115/111875389-73bd9680-8991-11eb-81f6-694a149d2c11.jpg)
Going through testing ..
it is great yet very sensitive. Often, I've noticed that when switching between mouse pointer and drawing the pen isn't the last one used.. Maybe it's me doing something wrong. 

Any chances please to have an option to completely deactivate the use of the mouse wheel with ppInk? 
(but keeping "shift+wheel" for "Pen-Selection" or "Pen-Width")

**Comment by lucacuccu3x8** [comment]
![111077543-2f417f00-84e9-11eb-9bff-95263923686b](https://user-images.githubusercontent.com/9900115/111875389-73bd9680-8991-11eb-81f6-694a149d2c11.jpg)
Going through testing ..
it is great yet very sensitive. Often, I've noticed that when switching between mouse pointer and drawing, the drawing pen comes back as not the last one used.. Maybe it's me doing something wrong. 

Any chances please to have an option to completely deactivate the use of the mouse wheel with ppInk? 
(but keeping "shift+wheel" for "Pen-Selection" or "Pen-Width")

**Comment by lucacuccu3x8** [comment]
![111077543-2f417f00-84e9-11eb-9bff-95263923686b](https://user-images.githubusercontent.com/9900115/111875389-73bd9680-8991-11eb-81f6-694a149d2c11.jpg)
Going through testing ..
it is great yet very sensitive. Often, I've noticed that when switching between mouse pointer and drawing the pen isn't the last one used.. Maybe it's me doing something wrong, but I suspect the mouse wheel is still switching the pens even when ppink is minimized in "mouse pointer mode" .. cannot tell yet, as it isn't always happening. 

Any chances please to have an option to completely deactivate the use of the mouse wheel with ppInk?

**Comment by pubpub-zz** [comment]
Your analysis about mouse wheel in pointer mode is correct. fix attached
[ppInk21.zip](https://github.com/pubpub-zz/ppInk/files/6177559/ppInk21.zip)

About desactivating mouse wheel I do not see the use and I never had complain about this function being active since its implementation.

**Comment by lucacuccu3x8** [comment]
yeah, you're right, sorry.

Oh, it would be such a great thing to have the mouse wheel (for scroll up and down pages) free from ppink grasp,  without the need of tricks and boots. Basically a mouse pointer that draws and let you scroll your documents while you reading. I know  you suggested already a solution, and I'm thankful for it.
Anyway, regarding this issue here about "Mouse Wheel to rotate between pens", can be close.
the latest zip you gave me here, seems to have the pens selection sorted.
thank you!
