### ISSUE TITLE
Control ppink programmatically 

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [pubpub-zz/ppInk#71]
Hi,

Firstly, thanks for this great project.

Is there a way to control ppink programmatically including getting some information about the current state (is it active, which color is the pen)?

I a have a elgato streamdeck and want to be able to activate ppink tools by pressing buttons on the streamdeck. I also want to display on the streamdeck wether ppink is active, which color is selected etc.

In powerpoint I can do this using AutoHotKey and the ComObj Prowerpoint provides.

Is there some way to do this with ppink?
Thanks!

**Comment by pubpub-zz** [comment]
Thanks for your comments

> Is there a way to control ppink programmatically including getting some information about the current state (is it active, which color is the pen)?

There is currently no communication channel. With this type of application which relies on operator control, I'm not sure it worth it.



> I a have a elgato streamdeck and want to be able to activate ppink tools by pressing buttons on the streamdeck. I also want to display on the streamdeck wether ppink is active, which color is selected etc.

Yes this is possible.two options:
a) run ppink.exe : if an existing instance is detected, it will start ink mode
b) directly send a "START_INKING" message(actually it is what uses alternative a). here is an example in python:
```
import win32, win32api, win32gui
msg_TaskbarRestart = win32gui.RegisterWindowMessage("START_INKING")
win32api.PostMessage(0xFFFF,msg_TaskbarRestart,None,None)
```

if you want to start inking immediately when running first instance, you can directly add '--StartInking' to the command line.

**Comment by RudolfVonKrugstein** [comment]
Ah, that is already very nice!
Are there other messages I can send? For example "STOP_INKING"?

**Comment by pubpub-zz** [comment]
No I've only implemented START_INKING : stop depends on too much on the user. What you can do quite easily is to send some key press events to create shortcuts to the different functions

**Comment by pubpub-zz** [comment]
Is my proposal OK for you ?

**Comment by RudolfVonKrugstein** [comment]
I am still experimenting with my setup, but I think yes :). Thanks for the support!
