### ISSUE TITLE
eraser accuracy 

### ISSUE THREAD

**Issue by hungrysnake** [pubpub-zz/ppInk#72]
hi, i found that it's a bit hard to accurately erase something with the eraser.
the img below show that the line would only be remove when the mid part of the erase touching the line.
could there be an option to select a more pointy icon or changing the point triggering deletion at the botton the eraser?

![image](https://user-images.githubusercontent.com/42885440/111909559-c33aba00-8a98-11eb-9d5c-36d9ff599948.png)
eric

**Comment by pubpub-zz** [comment]
You can add/replace an file eraser.ani, eraser.cur, or eraser.ico. with ico file, the active point is the center point. With version 1.5+ you the item to be deleted is surrounded by a dashed box

**Comment by pubpub-zz** [comment]
have you been able to test the latest version ?

**Comment by pubpub-zz** [comment]
@hungrysnake,
just a last notification before closing : have you been able to test the latest version ?

**Comment by pubpub-zz** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/18024882/136649615-32a595df-3516-4d43-b10f-77b16feb89d1.png) Hi pubpub-zz. There is confused to select which line I want to erase, when they close to each other. Could you please make an option to change to erase style like pen.

I have some trouble to understand what you mean exactely. If you are looking for another cursor,that would look like a pen, a wand or anything else, you can customize the eraser cursor by drawing your own cursoreraser.ico to match your need

**Comment by xue-blood** [comment]
> > ![image](https://user-images.githubusercontent.com/18024882/136649615-32a595df-3516-4d43-b10f-77b16feb89d1.png) Hi pubpub-zz. There is confused to select which line I want to erase, when they close to each other. Could you please make an option to change to erase style like pen.
> 
> I have some trouble to understand what you mean exactely. If you are looking for another cursor,that would look like a pen, a wand or anything else, you can customize the eraser cursor by drawing your own cursoreraser.ico to match your need

Yes, I had changed `cursoreraser.ico` to 8x8 pixels small image.
And It's work for deleting small line,
However It will also be selected When I not overlay point on some line. Does the eraser has a large detect range?
![image](https://user-images.githubusercontent.com/18024882/136726149-f0aec40c-838a-4df0-bbff-cbfc68461f1b.png)
![image](https://user-images.githubusercontent.com/18024882/136726157-e164bb27-a83f-4ede-81b5-1a125b7a4893.png)
![image](https://user-images.githubusercontent.com/18024882/136726164-3febd753-5656-4908-8243-9964ae9eb968.png)
