### ISSUE TITLE
bizarre pointer switching

### ISSUE THREAD

**Issue by eamayreh** [pubpub-zz/ppInk#73]
@pubpub-zz 
I have no idea what this is: the pointer is in drawing mode, but at certain areas of screen it turns into cursor Oo

https://user-images.githubusercontent.com/61389799/112223840-18123800-8c33-11eb-88e8-bb98f5490b12.mp4

**Comment by pubpub-zz** [comment]
I've got it : this is a side effect of in progress development : I'll fix it for official release : should occur tommorow or the day after
