### ISSUE TITLE
snapshot artifacts

### ISSUE THREAD

**Issue by eamayreh** [pubpub-zz/ppInk#74]
Hello @pubpub-zz 
I was taking a snapshot with ppInk when I noticed this (in the video below you can see some artifacts showing on drawings when I start selecting area for snapshot, and it may end up getting saved in final image when it occurs as shown in bad snapshot, though this doesn't always happen and you often get a good image).

https://user-images.githubusercontent.com/61389799/112559028-1f774400-8de1-11eb-844d-4f888a5279a2.mp4

bad snapshot
![2021-03-26 02-46-11](https://user-images.githubusercontent.com/61389799/112559185-7bda6380-8de1-11eb-9c18-87864f9f342a.png)

good snapshot
![2021-03-26 02-46-47](https://user-images.githubusercontent.com/61389799/112559203-84cb3500-8de1-11eb-9f0b-ff7f0dce4e6b.png)

**Comment by eamayreh** [comment]
update: it seems likely to occur when you type text with a white/black background

**Comment by pubpub-zz** [comment]
This is due to string printing issues in windows API not very reliable with overlay copy in windows mode... I think I have found a fix can you test it. if not working to ease my test can you save the strokes and send me the file. 
                  thanks
[ppInk29a.zip](https://github.com/pubpub-zz/ppInk/files/6221301/ppInk29a.zip)

**Comment by eamayreh** [comment]
> I think I have found a fix can you test it. if not working to ease my test can you save the strokes and send me the file.
> thanks
> [ppInk29a.zip](https://github.com/pubpub-zz/ppInk/files/6221301/ppInk29a.zip)

I don't get the same issue with this; looks good now.

On a side note, the "Window mode" seems to be stuck and always pops up first thing when running ppInk even after resetting it.

https://user-images.githubusercontent.com/61389799/112843394-33ee6180-90ab-11eb-91c0-eefec9acbd2e.mp4

**Comment by eamayreh** [comment]
> In your video, I can not see that you saved the configuration. I did the test and it passed. can you check on your side ?

Aha, okay. Yes it works taking the steps you mentioned. I didn't know that to be honest; I thought it would save the new settings automatically, so this isn't a problem anymore. I'll close this issue now.
