### ISSUE TITLE
UIThreadException when erasing

### ISSUE THREAD

**Issue by calfranca** [pubpub-zz/ppInk#76]
About 99% of times, when using the eraser I get this message:

![Captura](https://user-images.githubusercontent.com/17181115/114016125-d0162680-986a-11eb-9a8e-64153d80b459.JPG)

This is happening only when I use my drawing table (xp-pen branded) and when erasing fast (press and move pen or several quick clicks)

I've tried with new and old tablet driver with the same result.

This is happening since ppink 1.5 Beta 1.  I do have not this problem with 1.4 or early versions.

Can you, please, check if you can fix it?

Thank you for your amazing work.

**Comment by pubpub-zz** [comment]
Hi @calfranca ,
Thanks for report. this is due to fading implementation when erasing all strokes in what looks like to be a quick manner. Can you try this beta version:
[ppInkCrashErase.zip](https://github.com/pubpub-zz/ppInk/files/6281300/ppInkCrashErase.zip)

Do not hesitate to star the project if you like it😉

**Comment by calfranca** [comment]
Exception fixed, Thank you very much.

FYI, I have found another one when clicking the open strokes icon claiming it cannot find the AutoSave.strokes.txt file
It happened in a computer where I didn't run the 1.5 RC2 version before. The one I use to use had the file automatically created so the exception does not show.

In this beta I have found the secondary banner when selecting shapes and move options. Very good idea.

The only thing that bothers me in the app is that everything is erased when pressing the ESC key... I use it so frequently that I clear the screen many more times than desired. Thanks that the undo key works fine ;)


Project starred

Kind Regards

**Comment by pubpub-zz** [comment]
> FYI, I have found another one when clicking the open strokes icon claiming it cannot find the AutoSave.strokes.txt file
> It happened in a computer where I didn't run the 1.5 RC2 version before. The one I use to use had the file automatically created so the exception does not show.

I though this was solved. Il will check
> In this beta I have found the secondary banner when selecting shapes and move options. Very good idea.

Still in progress... 😃 To activate a little more check the secondary toolbar in option dialog. issue #66 tracks exchanges /bugs about. Do not hesitate to review/give your feed  backs...


> The only thing that bothers me in the app is that everything is erased when pressing the ESC key... I use it so frequently that I clear the screen many more times than desired. Thanks that the undo key works fine ;)
two things about this problem : 

a) if it occurs, when you restart inking, just click on the load button : you will reload AutoSave and recover your last status
b) you can customize close shortcut, replacing it with another shortcut : just be aware that currently this shortcut will also be the one use to escape from snapshot mode...

**Comment by calfranca** [comment]
> a) if it occurs, when you restart inking, just click on the load button : you will reload AutoSave and recover your last status

I did it indeed. That was the moment whet I got the exception ;)

Thanks again for your quick fix

**Comment by pubpub-zz** [comment]
new beta:
* no crash/actions if autosave.strokes.txt does not exists
* escape kept to close in addition to customizable hotkey to close snapping

[ppInkEscape.zip](https://github.com/pubpub-zz/ppInk/files/6285602/ppInkEscape.zip)

**Comment by woodwm** [comment]
> new beta:
> 
> * no crash/actions if autosave.strokes.txt does not exists
> * escape kept to close in addition to customizable hotkey to close snapping
> 
> [ppInkEscape.zip](https://github.com/pubpub-zz/ppInk/files/6285602/ppInkEscape.zip)

Hi, I think you need to change the name of file "sad1.png" to "sad.png". Otherwise, when it starts, it will show an error window.

**Comment by calfranca** [comment]
Crash fixed.
Don't worry about Esc key,  I have hotkeys disabled. Using the undo or reloading the autosave file is enough for my needs.


> Hi, I think you need to change the name of the file "sad1.png" to "sad.png". Otherwise, when it starts, it will show an error window.

I was about to tell you this ;)

kind regards

**Comment by pubpub-zz** [comment]
thx : it was a unitary test. already renamed

**Comment by pubpub-zz** [comment]
Issue fixed : Closing this conversation
