### ISSUE TITLE
Visually Identify Fading pens

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#77]
>     * pen **fade modifier key** when drawing shape such as (ctrl/alt/shift)
>       if you want to draw arrow or any shape that fades, select shape and hold shift/ctrl while drawing so that it disappears afterwards, then pen is back to normal (this way you don't have to select fade for each pen in options and remember which pen has fade enabled and which not - use case: recording /live lesson/presentation.

I'm personnaly use a lot the ctrl/alt/shift (that's why I've developped them 😁)  but I understand that fading is often forgotten : I propose to add a visual(customisable mark) : see beta attached
[ppInkFadingTag.zip](https://github.com/pubpub-zz/ppInk/files/6285881/ppInkFadingTag.zip)

>     * mouse **right click extra functionality**: when mouse hovers over shapes, red dots become visible (like when selecting move on main toolbar) or these dots can appear when holding a modifying key, and you are able to move that shape holding right click and dragging it (no need for move icon in main toolbar); also can be extended for duplicate (copy)/move/ edit - hold (shift/ctrl/alt) while holding right click to copy and drag item. This feature needs some review to make it practical.

despite mouse right click has started to get some functions, I'm personnaly like the alt+ Hotkey(Move or clean...) is quite quick and may just perhaps require a little of time to get used to it.

_Originally posted by @pubpub-zz / @eamareh in https://github.com/pubpub-zz/ppInk/issues/66#issuecomment-816665201_

**Comment by eamayreh** [comment]
> I'm personnaly use a lot the ctrl/alt/shift (that's why I've developped them 😁) but I understand that fading is often forgotten : I propose to add a visual(customisable mark) : see beta attached
> [ppInkFadingTag.zip](https://github.com/pubpub-zz/ppInk/files/6285881/ppInkFadingTag.zip)

I went through all options thinking what this could be, but I couldn't find anything. It turned out I didn't set any pen to fade xD and so I didn't see the mark you added to fading pens. I think this a good solution for now : )

**Comment by eamayreh** [comment]
@pubpub-zz the visual mark would be even better with a customizable hotkey in options (namely: F) to turn fade on/off for pens without breaking functionality for anything else 🙌

**Comment by pubpub-zz** [comment]
I've been very surprised by the amount of people using ppInk for presentation. I therefore agree that fading shortcut could be interesting.
[ppInkx64ToggleFad.zip](https://github.com/pubpub-zz/ppInk/files/6346901/ppInkx64ToggleFad.zip)

This version includes the memory leak fix/rework. do not hesitate to extend testing 😃

**Comment by eamayreh** [comment]
> 
> 
> I've been very surprised by the amount of people using ppInk for presentation. I therefore agree that fading shortcut could be interesting.
> [ppInkx64ToggleFad.zip](https://github.com/pubpub-zz/ppInk/files/6346901/ppInkx64ToggleFad.zip)
> 
> This version includes the memory leak fix/rework. do not hesitate to extend testing 😃

Aha, that is awesome!! Testing time :D

**Comment by eamayreh** [comment]
So far, this is what I found:
- The fade hotkey is not saved after you close ppInk. 
- Another strange issue is when you first open ppInk and activate toolbar, sometimes no pen is selected, and trying to close ppInk toolbar before drawing anything through the "X" on the main toolbar doesn't work (you press it, but toolbar doesn't close and stays on screen). Not sure if I'm doing something wrong - you can see it in this video:

https://user-images.githubusercontent.com/61389799/115939056-75550f80-a4a5-11eb-9665-6a1dd2473a94.mp4


Another minor issue regarding language for tooltips on secondary toolbar is they do not show translated when respective language is selected, i.e. Arabic in this case as can be seen in image 
![secondary toolbar language](https://user-images.githubusercontent.com/61389799/115939001-3757eb80-a4a5-11eb-92af-2eec85504331.png)

**Comment by pubpub-zz** [comment]
Hi @eamayreh,
thanks for your test report
>     * The fade hotkey is not saved after you close ppInk.
I did the test and it is successfull. Can you check Hotkey_ToggleFading is updated in your hotkeys.ini
 
>     * Another strange issue is when you first open ppInk and activate toolbar, sometimes no pen is selected, and trying to close ppInk toolbar before drawing anything through the "X" on the main toolbar doesn't work (you press it, but toolbar doesn't close and stays on screen). Not sure if I'm doing something wrong - you can see it in this video:
This sounds like an old issue I had on interim versions. Can you please confirm that your did your tests on ppInkx64ToggleFad.zip ? In any case I will reproduce a new interim version
[ppInk64_25a.zip](https://github.com/pubpub-zz/ppInk/files/6372037/ppInk64_25a.zip)


> Another minor issue regarding language for tooltips on secondary toolbar is they do not show translated when respective language is selected, i.e. Arabic in this case as can be seen in image
The hints on the subpanel are new translation inputs : 

> PanSubToolsHints = "Move one stroke\nPan all strokes\nCopy one stroke"
> HandSubToolsHints = "Handfree drawing\nColor filled drawing\nWhite filled drawing\nBlack filled drawing"
> LineSubToolsHints = "Segment\nPolyLine\nColored Polygon\nWhite Polygon\nBlack Polygon"
> RectSubToolsHints = "Rectangle\nColor filled Rectangle\nWhite filled Rectangle\nBlack filled Rectangle"
> OvalSubToolsHints = "Ellipsis\nColored  Ellipsis\nWhite Ellipsis\nBlack Ellipsis"
> ArrowSubToolsHints = "Arrow starting by head\nArrow starting by tail"
> TextSubToolsHints = "Left Aligned Text\nRight Aligned Text"

**Comment by eamayreh** [comment]
> I did the test and it is successfull. Can you check Hotkey_ToggleFading is updated in your hotkeys.ini

So what I did was I copied the hotkeys.ini over from the previous version of ppInk I was using which didn't have the fade hotkey option; it's working properly now.


> This sounds like an old issue I had on interim versions. Can you please confirm that your did your tests on ppInkx64ToggleFad.zip ? In any case I will reproduce a new interim version
> [ppInk64_25a.zip](https://github.com/pubpub-zz/ppInk/files/6372037/ppInk64_25a.zip)

I believe I was using the fade version (notice the previous video with "F" mark on pens). Now I've done the same test on this "25a" version you attached above. The issue doesn't seem to occur as often with this one. 

So what happens is that sometimes when you call the main toolbar, then close, then call it again it seems to have a pen selected, meaning you should be able to draw, but you can't draw because the drawing point isn't there, and the arrow on toolbar is black (not active, as opposed to being yellow when it's active) and so clicking the "x" button doesn't work in that instance. Calling the toolbar to gain focus again via its shortcut (ctrl+alt+g) allows you to close it without any problem. (I honestly don't know how I came to notice this, but it does seem to happen every now and then). 

This video is from the "25a" version (also notice now when drawing shapes they are black thin lines first then they get colored)

https://user-images.githubusercontent.com/61389799/116009646-92afe800-a623-11eb-9e9a-4e07ac4522fa.mp4






> The hints on the subpanel are new translation inputs :

I'll have these updated in the Arabic language file.

**Comment by pubpub-zz** [comment]
Hi @eamayreh,
Sorry for late update, I've spent some time trying to find to source of the bug in https://github.com/pubpub-zz/ppInk/issues/75#issuecomment-826286473
I've reproduced and fixed the bug you've raised. 
[ppInk64_07a.zip](https://github.com/pubpub-zz/ppInk/files/6439985/ppInk64_07a.zip)
Can you give me your feedbacks aspecially can you check if you are able to reproduce the dissapearing shapes

Thanks

**Comment by pubpub-zz** [comment]
Hi @eamayreh,
any results to share ?

**Comment by eamayreh** [comment]
Hey there @pubpub-zz 
Really sorry for being so late on this; I got buried with things to do. So basically, I couldn't find that shape bug in the 32bit at all. Here's a video with what the x64 version shows in the debug window when a shape disappears:


https://user-images.githubusercontent.com/61389799/118523979-5bc28300-b746-11eb-968f-93421854ddda.mp4

**Comment by pubpub-zz** [comment]
All seems adressed inhere I propose to close this thread

**Comment by eamayreh** [comment]
> 
> 
> All seems adressed inhere I propose to close this thread

Yes, looks good here. 👍
