### ISSUE TITLE
Window mode - how to open it?

### ISSUE THREAD

**Issue by LuNeder** [pubpub-zz/ppInk#78]
Hey!
On the latest ppInk version changelog states a "window mode", however I couldn't find it. Where is it?

**Comment by pubpub-zz** [comment]
(from https://github.com/pubpub-zz/ppInk) : 

Window mode You can now run ppink in window mode (engaged through Long/Right Click on pointer icon) In this mode ppInk is run in a window and you can access clicks or mousewheel applications out of the window:

https://user-images.githubusercontent.com/4083478/112311221-c656c580-8ca5-11eb-895b-2279366c0fc4.mp4

**Comment by LuNeder** [comment]
Ohhh, nice! That worked, thank you so much!

**Comment by pubpub-zz** [comment]
do you think it is useful? Can you tell me how you are using ppInk ? presentation or annotation/image capture ?

**Comment by LuNeder** [comment]
It’s very useful!
I use ppInk to write on top of slides the teacher is sharing on the class, then I screenshot it with Windows native screenshot taker and print it.
I also use it to write things and share with my teacher via OBS virtualcam.

**Comment by pubpub-zz** [comment]
Is there any reason you are not using ppInk screenshot taker?
Also are you using ppInk OBS control ?

**Comment by LuNeder** [comment]
I don’t save the screenshots, just copy them and paste on a document I’ll print, so the obsolete screenshot taker works fine.
And since I use OBS both with ppInk open and closed I control it directly, not via the ppInk controller 

It would benice

**Comment by LuNeder** [comment]
I don’t save the screenshots, just copy them and paste on a document I’ll print, so the obsolete screenshot taker works fine.
And since I use OBS both with ppInk open and closed I control it directly, not via the ppInk controller

It would be nice to be able to put into OBS a ppInk screen with transparent background, so I would be able to write on top of my camera, for example.

(Also, I accidentally pressed the comment button before this comment was done, sorry about that)

**Comment by pubpub-zz** [comment]
> I don’t save the screenshots, just copy them and paste on a document I’ll print

I see... Could a variant of the snapshot button to automatically  append the snapshots be useful from your point of view?

> It would be nice to be able to put into OBS a ppInk screen with transparent background, so I would be able to write on top of my camera, for example.

this is normally working : see #21

**Comment by LuNeder** [comment]
Ohhhh the #21 trick worked, thanks!

I’m not sure about the screenshot button thing, since I usually have many documents open at the same time: how would you know where to append it?

Also, I’ve been using the beta you sent on #76, since I also had the crash on erasing problem, and I realized the move tool doesn’t move cliparts anymore. Is that a bug or intentional?
