### ISSUE TITLE
Background not working well in multi-screen

### ISSUE THREAD

**Issue by CoinAxe** [pubpub-zz/ppInk#79]
The normal behavior is that the BG is showing on both screens at once, is it possible having it show on one screen instead of two ?

**Comment by pubpub-zz** [comment]
It is possible to do that engaging window mode and selecting an area covering the screen you want. this can be then saved (using the save button in option dialog box)

**Comment by CoinAxe** [comment]
Can u tell me where to engage window mode

**Comment by pubpub-zz** [comment]
I've been asked about recently: #78

**Comment by pubpub-zz** [comment]
Is it OK for you? if so can you close the issue

**Comment by CoinAxe** [comment]
Yes thanks I'll close it now
