### ISSUE TITLE
General bug

### ISSUE THREAD

**Issue by CoinAxe** [pubpub-zz/ppInk#80]
I'm having an issue when using this alongside streamdeck

I've assigned a hotkey switch, so when pressed it will open ppInk, when pressed again it will close it.
![image](https://user-images.githubusercontent.com/65632488/115407118-731a5900-a1f8-11eb-9aff-963ff043eb29.png)

After that I can't do anything and it messes up my config file and have to start again

**Comment by TheCoinAxe** [comment]
![image](https://user-images.githubusercontent.com/65632488/115414227-87615480-a1fe-11eb-8c63-2de25b3abbfc.png)

**Comment by pubpub-zz** [comment]
> 
> 
> I'm having an issue when using this alongside streamdeck
> 
> I've assigned a hotkey switch, so when pressed it will open ppInk, when pressed again it will close it.
> ![image](https://user-images.githubusercontent.com/65632488/115407118-731a5900-a1f8-11eb-9aff-963ff043eb29.png)
> 
> After that I can't do anything and it messes up my config file and have to start again

Can you please send the failing config file you have modified ?

Also, Can you describe how you've got a second crash

**Comment by CoinAxe** [comment]
What I meant is that it resets my config file. I'm trying to reproduce this again

**Comment by CoinAxe** [comment]
I got another error, I can confirm that I didn't use streamdeck with it on this time
![image](https://user-images.githubusercontent.com/65632488/115638595-62aecf00-a31b-11eb-9216-e007e9472f90.png)

**Comment by pubpub-zz** [comment]
A memory leak has been found. A beta version has been submitted last post of #75. However I'm not sure it is your issue. Can you please send the config.ini you are using
Thx

**Comment by CoinAxe** [comment]
Here is the config file
[config.txt](https://github.com/pubpub-zz/ppInk/files/6372758/config.txt)

Renamed to txt

**Comment by pubpub-zz** [comment]
Have you been able to test the version from #75 ?

**Comment by CoinAxe** [comment]
Problem is I'm not able to reproduce this bug to confirm, let me use it a bit more with the beta and report back when it happens again

**Comment by CoinAxe** [comment]
Shall I close this issue and reopen again if it happens ?

**Comment by pubpub-zz** [comment]
Agree with your approach
