### ISSUE TITLE
Portuguese translation file

### ISSUE THREAD

**Issue by joaopequeno-git** [pubpub-zz/ppInk#81]
Please find attached new PT (portuguese) language file made by myself.
[pt.txt](https://github.com/pubpub-zz/ppInk/files/6361690/pt.txt)

**Comment by pubpub-zz** [comment]
Obrigado! 🥰 
I will link your translation in #17, can yous subscribe to this issue in order to be notified when new tranlation will be requested

**Comment by pubpub-zz** [comment]
Hi @joaopequeno-git 
I' preparing a new release Can you please send me an update of your proposed translations ?
[ppInk64_22b.zip](https://github.com/pubpub-zz/ppInk/files/6526798/ppInk64_22b.zip)

Can you please post your translation in #17 

Thanks

**Comment by joaopequeno-git** [comment]
> 
> 
> Hi @joaopequeno-git
> I' preparing a new release Can you please send me an update of your proposed translations ?
> [ppInk64_22b.zip](https://github.com/pubpub-zz/ppInk/files/6526798/ppInk64_22b.zip)
> 
> Can you please post your translation in #17
> 
> Thanks

Hello yes of course i can send.
Please see attached.
You must also fix the following positions:
![imagem](https://user-images.githubusercontent.com/56827914/119234514-38248180-bb26-11eb-8b46-d10424bfb06d.png)
![imagem](https://user-images.githubusercontent.com/56827914/119234523-45da0700-bb26-11eb-9806-69ce01036c28.png)
![imagem](https://user-images.githubusercontent.com/56827914/119234763-6787be00-bb27-11eb-95de-484d5e5757f6.png)

Size and Font dont fit in:
![imagem](https://user-images.githubusercontent.com/56827914/119234804-9e5dd400-bb27-11eb-9b21-ca2efbfed8de.png)

box to big:
![imagem](https://user-images.githubusercontent.com/56827914/119235139-e7625800-bb28-11eb-8e22-9e2f2b0073fc.png)


[pt.txt](https://github.com/pubpub-zz/ppInk/files/6526853/pt.txt)

Anything else pelase say.

**Comment by joaopequeno-git** [comment]
> 
> 
> Hi @joaopequeno-git
> I' preparing a new release Can you please send me an update of your proposed translations ?
> [ppInk64_22b.zip](https://github.com/pubpub-zz/ppInk/files/6526798/ppInk64_22b.zip)
> 
> Can you please post your translation in #17
> 
> Thanks

Hello,
Of course i can send.
Tip: next update also include new fields on each translation file, its easier to only update new fields.

Also you need to fix this sizes:
![imagem](https://user-images.githubusercontent.com/56827914/119237039-b38c3000-bb32-11eb-9494-e36cde6c827d.png)
![imagem](https://user-images.githubusercontent.com/56827914/119237050-c0108880-bb32-11eb-9918-949a875b19ac.png)

Text dont fit on window:
![imagem](https://user-images.githubusercontent.com/56827914/119237058-d3235880-bb32-11eb-920e-08d757fbe800.png)

Translation of PT dont apply on this field but present on file, please check:
![imagem](https://user-images.githubusercontent.com/56827914/119237112-21d0f280-bb33-11eb-9330-2d3e2e3025a4.png)


This new function is for what?
![imagem](https://user-images.githubusercontent.com/56827914/119237227-a885cf80-bb33-11eb-9fac-034d006825d8.png)
[pt.txt](https://github.com/pubpub-zz/ppInk/files/6526937/pt.txt)

**Comment by pubpub-zz** [comment]
Thanks for your help. I've slightely ajusted the text to fit in:
![image](https://user-images.githubusercontent.com/4083478/119254856-fe508b00-bbb8-11eb-82da-afb1636e32dd.png)

**Comment by joaopequeno-git** [comment]
> 
> 
> Thanks for your help. I've slightely ajusted the text to fit in:
> ![image](https://user-images.githubusercontent.com/4083478/119254856-fe508b00-bbb8-11eb-82da-afb1636e32dd.png)

Hello,

Also improve this please, its not understandable that we need to save, perhaps with some buttons like this is better:
![imagem](https://user-images.githubusercontent.com/56827914/119255244-9eef7c80-bbb2-11eb-812f-e893a462eead.png)

**Comment by pubpub-zz** [comment]
Actually the two buttons you are proposing are not exactely what is coded : once changes are typed in the dialog, there are immediately applied and introducing a cancel button will be very tough to code.I propose to introduce in a next release just a warning sentence in red

**Comment by joaopequeno-git** [comment]
What is this button for:
![imagem](https://user-images.githubusercontent.com/56827914/119278327-7734fe80-bc1c-11eb-8525-f0875af4dd48.png)
To save the changes?
If yes , just place it at the bottom in the right, where i placed the cancel

**Comment by pubpub-zz** [comment]
agree, will be moved for next version
