### ISSUE TITLE
Streamdeck with ppInk

### ISSUE THREAD

**Issue by CoinAxe** [pubpub-zz/ppInk#82]
I'm using a streamdeck with ppInk.

I have assigned the following buttons:
1. Rectangle (R)
2. Handfree tool (H)
4. Eraser (E)
5. Clear All (X)

I've came into a situation, where the H shortcut is sometimes pressed twice accidentally, and that activates the other hand free tools which I don't need at all.

 Is there a way to disable the extra functions within the H shortcut ? It would be better activating those within the toolbar instead of pressing H to cycle between them

**Comment by pubpub-zz** [comment]
as a quick solution, I would propose you to do first Select another tool : for rectangle, set your button to send H then R : this should do the job.
Waiting for your feedback

**Comment by pubpub-zz** [comment]
Is it ok with my proposal?

**Comment by CoinAxe** [comment]
Sorry for my delay, I'm stuck in trying to make this work with the streamdeck

I'm not able to set up this workflow in StreamDeck in conjunction with the Super Macro Toggle plugin.

I have assigned a button to toggle between the numbers  1 and 2, to cycle between the colors. If I use this toggle in a text editor it will work fine. But with ppInk it won't work.

Do you have an access to a streamdeck ? OR the free app (30-day trial) to test this ?

**Comment by pubpub-zz** [comment]
I've been able to get a streamdeck. Not so easy, will come back.
You are just planning to use one key or you have other ideas in mind ?

**Comment by CoinAxe** [comment]
This is how im using it
![image](https://user-images.githubusercontent.com/65632488/117027162-1abd7e00-ad05-11eb-9b42-db66edf51468.png)

Since I'm using a streamdeck mini, I'm using minimal buttons as possible, and keeping the less used functions in a folder

**Comment by CoinAxe** [comment]
![image](https://user-images.githubusercontent.com/65632488/117027759-adf6b380-ad05-11eb-8da6-3e410669bbf0.png)

My problem happens when I use the super macro toggle to toggle between 1 and 2, it doesn't work

**Comment by pubpub-zz** [comment]
From my understanding of streamdesk, you should use VK_1
also, from my test I used successfully
{{keydown:VK_1}}{{keyup:VK_1}}

and set the timer to 250ms

tell me if it is better like that

**Comment by CoinAxe** [comment]
Thanks that's much better. This is my current setup on streamdeck mini. It's working ok but there are room for improvements:
![image](https://user-images.githubusercontent.com/65632488/117078642-eb2d6680-ad42-11eb-8f17-7205f4f8cad6.png)


**First of all here is how I set up the top buttons**
1. The red button when pressed changes to a blue color, I have applied the following macros and enabled remember toggle state when switching profile on:
Primary Macro
{{keydown:VK_R}}{{keyup:VK_R}}
{{keydown:VK_H}}{{keyup:VK_H}}
{{keydown:VK_1}}{{keyup:VK_1}}

Secondary Macro
{{keydown:VK_R}}{{keyup:VK_R}}
{{keydown:VK_H}}{{keyup:VK_H}}
{{keydown:VK_3}}{{keyup:VK_3}}

2. The top right button, I'm using it to switch between the number tool and the rectangle tool, here I'm using the default hotkey switch without plugins, and switching between R and N, I'm also using a different image to highlight the icon and that gives me a visual cue to which tool is selected

**Now my issues that I noticed are:**
1. The switching between the colors is really slow, because its using macros, is there a way to improve here ?
2. Also say I'm on a red color and draw a bit, after that I select the rectangle tool, when I press back to the red button it changes color, I didn't find a way to preserve the same color

**Comment by pubpub-zz** [comment]
> * The switching between the colors is really slow, because its using macros, is there a way to improve here ?

The only ideas I have is to implement a full remote API. I have some ideas but it will take some time aspecially to be compatible with the streamdesk

> * Also say I'm on a red color and draw a bit, after that I select the rectangle tool, when I press back to the red button it changes color, I didn't find a way to preserve the same color

The point is that you are changing tool in both buttons... thinking about

Can you send the page export : It will be easier for me to work on

**Comment by CoinAxe** [comment]
Would be cool to see a native plugin for Streamdeck, now that would be amazing.

Sure, here is the page export:
[ppInk.txt](https://github.com/pubpub-zz/ppInk/files/6427117/ppInk.txt)

You have to rename it to *.streamDeckProfile

**Comment by CoinAxe** [comment]
Did the profile import work ?

**Comment by pubpub-zz** [comment]
Hi @CoinAxe,
   No The profile does not appear in the list 😞, but I've been able to open it with 7zip and I've been able to get images & data 
I've started to work on a REST server interface that should provide the need for remote control.
I'm currently finishing a first release that I will propose for beta testing very very soon

**Comment by CoinAxe** [comment]
Wow that's awesome news, please include me for beta testing. Should I rename this title "Streamdeck with ppInk" ?

**Comment by CoinAxe** [comment]
Thanks I'll test it out. So I wanted to know in theory would it resolve my previous two issues ?

**Comment by pubpub-zz** [comment]
With the current configuration, the red/blue button switches colors but is not changing pen, as if you were using the keyboard
I did an error  about the pointer mode in the desk this one should work better
[ppInk2.StreamDeckProfile.txt](https://github.com/pubpub-zz/ppInk/files/6464520/ppInk2.StreamDeckProfile.txt)

**Comment by pubpub-zz** [comment]
@CoinAxe 
Have you been able to test the provided beta version ?
I've completed the REST API implementation. have a look at the RTF for the different URLs.
In this version, I have introduced an option to set the pens on two lines. This can be disable in Options

[ppInk64_16a.zip](https://github.com/pubpub-zz/ppInk/files/6490156/ppInk64_16a.zip)

**Comment by CoinAxe** [comment]
Sorry I was a bit busy didn't have time to check it out. I was wondering does the current implementation allow for switching between pen and other tool while keeping the last selected color ? 
![image](https://user-images.githubusercontent.com/65632488/118953053-2778dd80-b965-11eb-8842-53f7be3d65c8.png)

So I'm trying to switch between 1 and 2, 1 would give me the pen tool, when pressed again it will change to a blue color. When going to 2 I wish to retain the same color, and then when im back to 1 I also wish to keep the same color. Do you get my point on this ? Is this currently supported in the implementation ?

**Comment by pubpub-zz** [comment]
1 is currently programmed to only switch color, and 2 will switch tool. It should be good for you

**Comment by pubpub-zz** [comment]
@CoinAxe 
Any update ?

**Comment by pubpub-zz** [comment]
@CoinAxe,
the version for REST API is released. is it ok for you ?

**Comment by pubpub-zz** [comment]
change published. @CoinAxe, feel free to open a new issue if required
