### ISSUE TITLE
Can you cancel this prompt?

### ISSUE THREAD

**Issue by tourxp** [pubpub-zz/ppInk#83]
![错误](https://user-images.githubusercontent.com/66894546/116803567-77753900-ab4b-11eb-964b-08e0e3c291b4.png)
Thank you.

**Comment by pubpub-zz** [comment]
Can you provide more context (how many strokes displayed? what were the last actions, are your using fading?) about this issue 
Meanwhile, be aware many mods are in the pipe. Can you check this version:
[ppInk02a.zip](https://github.com/pubpub-zz/ppInk/files/6411800/ppInk02a.zip)

Thnaks

**Comment by tourxp** [comment]
It often appears when using the eraser button in the pen.

**Comment by pubpub-zz** [comment]
Ok This has been already reported and is normally fixed in the beta sent. As soon as the problem I'm working on will be fixed I will release a new official version

**Comment by pubpub-zz** [comment]
I propose to close this issue. If you want to have a try, you can have a look at latest version in #100
