### ISSUE TITLE
extend cliparts import duration through toolbar

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#86]
> This is what I mean by cliparts not staying for the rest of the session. They're only persistent when the toolbar is extended after you added them, but if you collapse it and extend it back up they disappear. In version 1.4 they used to stay there until you closed the program fully I believe. I've uploaded a video file demonstrating the problem https://we.tl/t-5wtGiLS0rl

About your point, This what I've coded the 'session' time I was talking about is one inking session. At the origin, I wanted this duration, but I agree that now, it may be better for extend it and add a 'reset list' button. I will create an issue. can you subscribe to it ? I will certainly need your evaluations.

**Comment by pubpub-zz** [comment]
#84

**Comment by pubpub-zz** [comment]
fixed in this beta release
[ppInk64_17b.zip](https://github.com/pubpub-zz/ppInk/files/6492193/ppInk64_17b.zip)

**Comment by NOVAinc** [comment]
This issue is now resolved, indeed! The only issue I had is that upon launching ppInk for the first time, I loaded a clipart, and when trying to insert it by dragging a box it didn't insert on the first try. I have been unable to reproduce it, though. Cliparts do remain saved during the rest of the session :D

**Comment by pubpub-zz** [comment]
Good. I do not see what could have occured... I propose to close the issue as the function is here

**Comment by NOVAinc** [comment]
Agreed! Do I have to close it or do you have to do it?

**Comment by pubpub-zz** [comment]
next time you can do it 
PS. Have you find how to star the project

**Comment by NOVAinc** [comment]
I don't know what that is, but I just clicked the star icon at the top of this page that said "star pubpub-zz/ppInk" now. Does that help give the project more relevance? Anyway, I've done it now. Thanks a lot again for your great efforts towards improving this tool <3
