### ISSUE TITLE
Compiled version is missing the exe file

### ISSUE THREAD

**Issue by CTI-Tim** [pubpub-zz/ppInk#88]
your compiled version is missing the exe file.  recompile and reupload.

**Comment by pubpub-zz** [comment]
exe and all locally generated binaries are not present in the repository but in the releases :
Latest oficial release
https://github.com/pubpub-zz/ppInk/releases/download/1.5RC2/ppInk.zip

**Comment by pubpub-zz** [comment]
Can you tell if it is OK for you. if you want to try a beta version have a look at #84

**Comment by pubpub-zz** [comment]
This issue seems dead and addressed.
