### ISSUE TITLE
Slow toolbar animations when having large cliparts on quick access

### ISSUE THREAD

**Issue by NOVAinc** [pubpub-zz/ppInk#89]
When large images are used for clip arts, and they are put in the hotkeyable areas of the tool bar, the animation becomes a bit stuttery. My PC is pretty good, so I don't experience it as much but it might be an issue for people with lower specced devices.

I believe this might be because the tiny icons in the toolbar are the full size pictures shrunk, as opposed to resized version, but it's just my guess.

This isn't a big issue at all, but I thought it is good to report stuff anyway? 

Here is a video demonstration https://we.tl/t-iGuqjKkh7C

**Comment by pubpub-zz** [comment]
can you tell me if with the in-progress changes the loading is still long. I've preloaded as much as possible the toolbars and my measurement with one 1920x1080 image in one of the cliparts shows no delay
[ppInk64_06a.zip](https://github.com/pubpub-zz/ppInk/files/6435002/ppInk64_06a.zip)

**Comment by NOVAinc** [comment]
It's still present. I've recorded a video at 60fps since at 30fps I think it might not have been noticeable. Sorry about that!

This isn't really a big issue, hotkeys still work as soon as you click the Icon even if expansion takes a bit longer, so it is still usable.

https://we.tl/t-arQK7SCc79

**Comment by pubpub-zz** [comment]
I made a small change to regenerate thumbnails if no change. Do you see any difference ?
[ppInk64_17a.zip](https://github.com/pubpub-zz/ppInk/files/6491901/ppInk64_17a.zip)

**Comment by NOVAinc** [comment]
https://user-images.githubusercontent.com/19545604/118464023-c76d0780-b6d6-11eb-890a-b865f5e49b75.mp4

It seems to be maybe a bit better. Considering the pictures I'm loading are very high resolution, I really don't think anyone is going to have as much of an impact. If you would like, I can share the cliparts I'm using with you. Anything transparent at 2k resolution square should be about the same though.

**Comment by pubpub-zz** [comment]
Can you tell me if 17b or later versions are better, the clipart dialog "life extension" should have improved too. As you can tell me if it is better ( or not) we can close this issue as you've said the delay is I think globally improved

**Comment by NOVAinc** [comment]
It seems about the same in newer versions. I think it's ok to close it, I'm using unusually large assets and I don't think most people would run into the same issue or be too affected by it.
