### ISSUE TITLE
Unintended tool mode cycling on freehand when going back to it after having used the eraser

### ISSUE THREAD

**Issue by NOVAinc** [pubpub-zz/ppInk#91]
Hi! I have been having this issue for a while but only now I was able to do a bit more exhaustive testing.

If Handfree is selected, and then you switch to the eraser, going back to freehand will automatically switch to color fill mode. This does not happen with other tools, such as with rectangle getting switched to fill rectangle. Additionally, this doesn't happen when switching from handfree to other tools and back, such as doing handfree -> rectangle -> handfree. It seems to affect handfree in combination with eraser only from my limited testing.

**Comment by pubpub-zz** [comment]
aftermath of interim commit 4e43cc1f422ab38ca93616bd8c2123a21fde6fe6 in beta release provided in https://github.com/pubpub-zz/ppInk/issues/84#issuecomment-833534328

**Comment by NOVAinc** [comment]
Thanks for the reply! I tested the new version, but unfortunately the bug seems to still be there.

**Comment by NOVAinc** [comment]
Thank you for the update. The issue is now resolved indeed!

If I wanted to make a suggestion or had an idea for a feature/tool/mode in the software, what would be the best way to go about it?

**Comment by pubpub-zz** [comment]
raising a new issue will be the best approach I think
