### ISSUE TITLE
numbering feature bug

### ISSUE THREAD

**Issue by cmhdream** [pubpub-zz/ppInk#93]
There's a problem with the numbering feature bug
Use the middle scroll wheel to enlarge the frame so you can't see the numbers.

![2021-05-15 14-06-35](https://user-images.githubusercontent.com/24859526/118350020-0be98d80-b587-11eb-8cb4-2e931ffaa901.png).

**Comment by pubpub-zz** [comment]
the mouse wheel by default adjust the width of the pen used to draw the circle. I agree you can get to something not nice, but it is consistent with the usage

**Comment by pubpub-zz** [comment]
@cmhdream, any update about this thread ?

**Comment by cmhdream** [comment]
![Form105-29_224826](https://user-images.githubusercontent.com/24859526/120074565-05ebc480-c0d0-11eb-8ff5-2e91beede36d.jpg)
ppInk64_Dash2 version still the same..

**Comment by pubpub-zz** [comment]
as said the mouse wheel is increasing the width of the line, until it hides the number : for me it is not bug, just an inappropriate use of the mouse-wheel inhere.

**Comment by NOVAinc** [comment]
Would it be possible to have the mousewheel increase the size of the chip in general as opposed to the stroke width? I understand the behavior is consistent, but I don't see the point of being able to change the stroke size of the circle only while the text remains the same size as well. From an external point of view, it's like only some of the strokes are getting affected by the wheel if one isn't aware that the number part of it is a text element. This would be an example.

![2021-05-29 19-16-40](https://user-images.githubusercontent.com/19545604/120085898-72f06180-c0b2-11eb-9bde-4bc46650b972.png)

**Comment by pubpub-zz** [comment]
will think about it

**Comment by pubpub-zz** [comment]
Is this ok for you?
[ppInk64_01a.zip](https://github.com/pubpub-zz/ppInk/files/6577838/ppInk64_01a.zip)

**Comment by NOVAinc** [comment]
I personally find this behavior a lot better and, most importantly, a lot more usable! I'm interested to see what others think :)

**Comment by cmhdream** [comment]
@pubpub-zz This version has a good effect after testing.
