### ISSUE TITLE
Feature suggestions : Measurement tool

### ISSUE THREAD

**Issue by NOVAinc** [pubpub-zz/ppInk#94]
I have thought of a few things that might add some useful functionality to the software. Both of these apply to my usecase, but I can see how they could be useful for most people in different circumstances.

- Measuring tool: It'd be great having a tool that would allow you to measure a distance. Screen size and resolution can be taken into account for calculating actual distance, but even having a pixel distance counter would be very useful for when you need to compare things. I imagine the easiest way to achieve this would be by making the ruler tool work with straight lines only, but if it could be done with freehand strokes and other shapes it'd be even better. Imagine being able to compare circumferences of circles or poligons/polilines.
- Hotkeyable cliparts: Right know it is only possible to hotkey 3 cliparts, but it'd be great if you could hotkey many more. I think, given the current way hotkeys work, a good idea for how to add hotkeys to tools that aren't listed in the toolbar would be to right click on a tool and get a popup to either go to the tool's settings or add a hotkey for it. This could be done for individual cliparts too. This way, you would still have a manageable amount of hotkeys listed in the program software but the hotkeys file could store all of the additional hotkeys that have been assigned and weren't listed in the program. Alternatively, the hotkeys list in the program option screen could grow as people add hotkeys to features they use and it could be scrollable.

These features would fit my current use-case really well, and although I think they could be very useful to a variety of users, I think the program in its current state is already very much usable and it's the best in its class, be it open or closed source.

I would like to know if you have any short term plans for what you would like this program to be or to get to, or if you're constantly shifting depending on user feedback. The reason for this is I would like to make a video for you, that you could upload to YouTube and get more exposure as this is single handedly the best annotation software I've come across ever and I wanna help promote it!

**Comment by pubpub-zz** [comment]
Measurement tools are not simple but feasable: I foresee line, polylines, angle, For Circles It is more complex...
About Hotkeyable cliparts would be nearly impossible : due to the way key are implemented, having a dynamic number of hotkeys would impose a full code refactoring and may come to a impossibility. An alternative under development is the REST API that will provide a solution to implement such a feature within a streamdesk or similar solution : I will tell you when available.

Most of the time I' m publishing a new release once a month, but the current beta version has shown an issue (disapearing shapes) as discussed at the end of #75.

Your proposal is very interesting, Without any progress I think I will issue the new release by the end of next week (I dislike to have the memory leak still present in the official version)

**Comment by NOVAinc** [comment]
Thanks for the response. I will make sure to report bugs I come across as well to help iron the official version out as much as possible. When it is out, I can make the video for you if you'd like.

**Comment by pubpub-zz** [comment]
The clipart gallery is not limited, playing with short cut is therefore too complex.
I've issued a new version with a quite API REST
https://github.com/pubpub-zz/ppInk/issues/82#issuecomment-841886425
This version has the capability to load/select new cliparts which should fullfil your need using an external 'keyboard'
As an alternative to Streamdesk, you should have a look at Matricapp.com My API should work with this also

**Comment by NOVAinc** [comment]
I'm not really sure how to use the API. I don't use streamdeck currently, instead I use a software called TouchPortal which turns your phone into a streamdeck of sorts.

**Comment by pubpub-zz** [comment]
The API is using a standard local url. those URLs are described in  httpRequests.rtf provided next to ppink.exe

For example:
to start inkink http://localhost:7999/Inking?S=true
for ClipArt: http://localhost:7999/CurrentTool?T=22&I= **FileName of the clipart**

I've just installed TouchPortal, but from what I've seen you should use HTTP Get:
![image](https://user-images.githubusercontent.com/4083478/118480661-d671ab00-b712-11eb-804f-65a979464b5d.png)

Second topic: I've though a little about the measure tool.
To use it, it is quite easy: draw a stroke, and then select erase or moving tool : the length will be displayed in a tooltip. If you select a 3 points polyline, the angle will be also reported. The length is currently in pixels.

[ppInk64_17c.zip](https://github.com/pubpub-zz/ppInk/files/6493335/ppInk64_17c.zip)

Give me your opinion.

**Comment by NOVAinc** [comment]
The measure tool is amazing and right now it seems to work on all strokes, including freehand! You're a genius :D
![2021-05-17 16-35-07](https://user-images.githubusercontent.com/19545604/118546151-ed71c680-b72d-11eb-8939-6313fc0d20f9.png)

Both bottom strokes have about the same length, one being free drawn and the other one being a line. When adding some extra trajectory to the stroke, but making it the same width, it still takes into account the extra curves so it is absolutely fantastic. I did encounter severe lag when trying to take screenshots of these paths though. I tried with both smooth curves on/off and capture stroke only on/off, and after making those strokes, hovering the eraser on top of them seemed very laggy and taking the snapshot also lagged the toolbar really bad, which also closed itself and erased the drawing once I took the snapshot. I don't know if this last bit is expected.

For angles I found they work well! The only thing I'd suggest is flipping the negative. Since if you start drawing from the top to the bottom and then to the right on something like this, it should report a 90% angle on the second line relative to the first one, not -90% which would be the angle of the first line relative to the second.
![2021-05-17 16-42-33](https://user-images.githubusercontent.com/19545604/118546839-e4cdc000-b72e-11eb-9bf5-8856505452b4.png)

Also I noticed that when selecting the eraser after having used polyline, the tool gets reset to single line, which I'm not sure is expected either. Let me know if you would like or need more testing.

As for the REST server, the file httpsRequest showed this host address
![image](https://user-images.githubusercontent.com/19545604/118546979-19417c00-b72f-11eb-8db8-734e58b01ea4.png)which I imagine might have been a typo. When using `https://localhost:7999/CurrentPen[?P=n]` in touch portal it doesn't seem to select a pen at all. I've also tried a few of the other commands and I've been unable to make them work. This might be my own incompetence. Here is my current setup

![image](https://user-images.githubusercontent.com/19545604/118547334-940a9700-b72f-11eb-8920-a76a8772969e.png)

I thought the brackets might have been just placeholders for different parameters in the text file so I tried with both these ways, neither changes pens at all for me:

`https://localhost:7999/CurrentPen?P=2`
`https://localhost:7999/CurrentPen[?P=2]`

**Comment by pubpub-zz** [comment]
> Both bottom strokes have about the same length, one being free drawn and the other one being a line. When adding some extra trajectory to the stroke, but making it the same width, it still takes into account the extra curves so it is absolutely fantastic. I did encounter severe lag when trying to take screenshots of these paths though. I tried with both smooth curves on/off and capture stroke only on/off, and after making those strokes, hovering the eraser on top of them seemed very laggy and taking the snapshot also lagged the toolbar really bad, which also closed itself and erased the drawing once I took the snapshot. I don't know if this last bit is expected.

I'm puzzled about those laggings... I can not observe any during my tests... neither for measurement,nor for snapshots... However I've observed the toolbar unfolding before capture which I can not remember... Under investigation

> For angles I found they work well! The only thing I'd suggest is flipping the negative. Since if you start drawing from the top to the bottom and then to the right on something like this, it should report a 90% angle on the second line relative to the first one, not -90% which would be the angle of the first line relative to the second.

I am a scientist 😉, therefore I'm using the trigonometric way not the hourly way... 😆 
for final release I will add an option to select 

You made a tymistake 

> I thought the brackets might have been just placeholders for different parameters in the text file so I tried with both these ways, neither changes pens at all for me:
> 
> `https://localhost:7999/CurrentPen?P=2`
> `https://localhost:7999/CurrentPen[?P=2]`

You are right about the brackets. it is to show groups of parameters. About the URL you made a mistake I use http not https
the URL is **http://localhost:7999/CurrentPen?P=2**

**Comment by NOVAinc** [comment]
Oh, I didn't realise about that. I just copied and pasted the address presets in the httpRequests.rtf file, so that might need to be changed.

Using http instead of https does indeed result in the expected behavior! The only issue I have now is that I can't seem to target cliparts that have spaces in their name. I tried using double quotes and single quotes, as well as \ but I can't make it work.

**Comment by pubpub-zz** [comment]
Good point that integration with touchPortal and Obs. This could be a good subject for your video as I think it will be the only annotation program where you can do such interactions

Also about measurement tool, I've finished the cosmetic around (Text customizations and options) Can you give me your feed backs?
[ppInk64_19a.zip](https://github.com/pubpub-zz/ppInk/files/6511731/ppInk64_19a.zip)

**Comment by NOVAinc** [comment]
The measure pop up looks pretty good. It is already very usable in my opinion. I think something else that could add great value to the tool would be maybe having a way to add a few lines up for measurement. Like if you have the moving tool selected and you hold shift, the pop up adds the distance of all the lines you click. Or maybe with the eraser if you delete the lines it could aggregate total distance of all lines deleted during that moment you had the eraser selected. I think this might be easier than adding a "measure" tool which might be unnecessary for most use-cases I think.

Even without it, it already works really well. Thanks for considering the feature request!

**Comment by pubpub-zz** [comment]
Multi selection is addressed in another thread for further work. I think we can close this thread now
