### ISSUE TITLE
Ideas for improvements

### ISSUE THREAD

**Issue by chrisj0192** [pubpub-zz/ppInk#95]
Hello friend. I'm creating this issue in orden to explain you my ideas that I think could be of help not only for me, but for others as well.

highlighter pen:
I was thinking that the highlighter pen (with a width of 400 by default) could be another item to select with a hotkey or through the toolbar. For example, we can select the pencil and the eraser (as two different items, but you could include the highlighter pen as another item in the toolbar and in the hotkeys).
This feature would be great because if we select a highlighter pen as another element we will be also able to change its colors and we could do the same action with the pen (change colors).

Clipboard:
Another very important feature that I consider is about the clipboard, I would be pretty nice If we could have an option to select an screen area to save to clipboard with a hotkey (for example: ctrl + c) and then paste our selected screenshot in a document from the clipboard. This option would be very useful I usually use this option from windows 10 by pressing "win + shift + s" to take and cut some screenshots.

Magnifying glass option:
I don't know it it would be feasable to do it but I often use this option from windows 10 by pressing Win + "+" keys.This feature allows to move from side to side through a magnified image (in real time) If you need to zoom in a graphic related to geometry or and picture that is small, this option would be quite useful to explain and appreciate much better a picture.

Selected objects:
One of my favorite options in ppink is when I select, move and copy strokes, figures or something that I drew on the screen. That's fantastic! But sometimes I only needed to select two or three objects at a time to move them to another place on the screen. I don't know how difficult it would be implement a selector in orden to increase this marvelous function. It would be fantastic if you could implement it. For now we can move an object, copy an object and move all the objects that are on the screen.

Dashed lines:
Including a dashed line would be quite useful when we need to draw a solid shape, for example when we want to represent lines that are on the back of a prism.

I have other ideas but I'd like to read your opinion about it.

I'll stay tuned to your comment.

Thanks for your attention.

**Comment by pubpub-zz** [comment]
> highlighter pen:
> I was thinking that the highlighter pen (with a width of 400 by default) could be another item to select with a hotkey or through the toolbar. For example, we can select the pencil and the eraser (as two different items, but you could include the highlighter pen as another item in the toolbar and in the hotkeys).
> This feature would be great because if we select a highlighter pen as another element we will be also able to change its colors and we could do the same action with the pen (change colors).

I have some difficulties to see exactly what you mean: currently, you can have some pens solid, and some transparent. and where you can have different width. Also you can change pen parameters with long click(or right click) to modify it without closing your session. isn't this sufficient ?

> Clipboard:
> Another very important feature that I consider is about the clipboard, I would be pretty nice If we could have an option to select an screen area to save to clipboard with a hotkey (for example: ctrl + c) and then paste our selected screenshot in a document from the clipboard. This option would be very useful I usually use this option from windows 10 by pressing "win + shift + s" to take and cut some screenshots.

It is already behaving that way, when you are doing a snapshot. Can you clarify?

> Magnifying glass option:
> I don't know it it would be feasable to do it but I often use this option from windows 10 by pressing Win + "+" keys.This feature allows to move from side to side through a magnified image (in real time) If you need to zoom in a graphic related to geometry or and picture that is small, this option would be quite useful to explain and appreciate much better a picture.

Since 1.5.2 2 zoom functions are availables have a look at the readme.md)

 
> Selected objects:
> One of my favorite options in ppink is when I select, move and copy strokes, figures or something that I drew on the screen. That's fantastic! But sometimes I only needed to select two or three objects at a time to move them to another place on the screen. I don't know how difficult it would be implement a selector in orden to increase this marvelous function. I would be fantastic if you could implement it. For now we can move an object, copy an object and move all the objects that are on the screen.

I agree this could be interesting, but this may be quite complex for both implementation and Operator interaction(I want to keep the interface compatible with a full tablet(touch only) mode) Will think about it. 👍 

> Dashed lines:
> Including a dashed line would be quite useful when we need to draw a solid shape, for example when we want to represent lines that are on the back of a prism.

I agree this could be interesting, but Not sure how to handle that with strokes (do not know if strokes drawing can be done with that. Will think about it. 👍 

[ppInk64_19a.zip](https://github.com/pubpub-zz/ppInk/files/6511731/ppInk64_19a.zip)

**Comment by chrisj0192** [comment]
Hi @ pubpub-zz, I'd like to add some other features that I found quite useful, but I'm not sure if they would be possible to implement. About your implement of this improvements, don't worry, take your time and think about it. These ideas are just to improve ppink much more than it is.

1. A black/white background with grid
This feature is pretty useful when we need to represent figures, drawings, geometric shapes, point location, symmetry, areas. This would be like the Cartesian plane in ppink. In my case, many times I needed to use a grid to make my drawings much better, especially in geometry.

Here you are some examples (I think a black background with grids looks much better)
![2021-05-25 19-34-47](https://user-images.githubusercontent.com/20199672/119585528-7c1abf00-bd90-11eb-8e92-8ac262ec5b09.png)
![2021-05-25 19-35-14](https://user-images.githubusercontent.com/20199672/119585529-7cb35580-bd90-11eb-9d14-1b17016b04ec.png)

2. A curved line.
I find this type of line really interesting when we need to draw an arc of circumference. My idea is to represent a circumference portion or represent a circular sector without making much effort.
This is a short video example of what I mean.

https://user-images.githubusercontent.com/20199672/119590775-0d8f2e80-bd9b-11eb-935e-2407a33cc375.mp4

My idea is to put an invisible point anywhere on the screen and start drawing the curved line (as if it were a geometry compass) but I think it could be complex to implement it.


Regardig "highlighter pen" I meant hmmm, for example, currently we can select a pen or a highlighter in the options menu. We have 10 options to choose between pencils or highlighters (there is limit of selection). So I was thinking about If it would be possible to have "A pencil as a separate object" and "A highlighter as a separate object" and then we can choose colors depending on the hotkeys.
In this way we could use "hotkeys" like this (this is an example):
Keys:
1: Pencil
2: Highlighter
3. Color picker
4. Eraser
and If I press the number key "1" this key would select the pencil and then I would press the R key (to select the color red)), G (to select the green). On the other hand If I press the number key "2" and then I press the R key (it selects the red), G (to select the green) and so on,

Besides we can set the pen width with the mousewheel or with hotkeys and that's fantastic and about "its Alpha value" I think the most used value is 255.
About the highlighter, it is more common to use it with "a width value of 400" and "an Alpha value of 50 to 80).

This idea came to my mind because I needed all the same colors using the pencil and highlighter. I use a lot of colors because in my work as a teacher I need to draw a lot of graphics, lines and highlight a lot hehe.

Now I've realized that in the ppInk64_24a.zip you've implemented "Color/Pen edit" and that's fantastic, that option is really useful but It would be great to have a pencil and a highlighter (as separate objects) with the same preset colors from the options menu (this would make it faster when changing one color to another by drawing on the screen).

Well this is just an idea and I know that it would be hard to implement because it seems like the structure is different and to be honest I don't know if it is possible to do it.

Regarding clipboard and magnifying glass options I'll show you some videos in #75 to explain what I found.

By the way, I'm willing to help you with the Spanish translation if you want because you've added new features. I really like using ppink. Every day I use it and I'm testing it continually 😊

I really appreciate your work. Thanks for your attention.

**Comment by pubpub-zz** [comment]
>     1. A black/white background with grid

You have a very easy solution to do such a background : add them in the clipart and you will be able to "call" it whenever you want

>     1. A curved line.

User interface may not be so easy to implement but I will keep that in mind.

> Regarding "highlighter pen" I meant hmmm, for example, currently we can select a pen or a highlighter in the options menu. We have 10 options to choose between pencils or highlighters (there is limit of selection). So I was thinking about If it would be possible to have "A pencil as a separate object" and "A highlighter as a separate object" and then we can choose colors depending on the hotkeys.

My will is too keep ppInk usable from touchscreen, tablet pen, or mouse, and keyboard as a way to accelerate but not as a mandatory input. The secondary tool may be a solution to propose an interface usable with the cursor. will think also about that...

> Regarding clipboard and magnifying glass options I'll show you some videos in #75 to explain what I found.

Looking forward to see your tests results
 
> By the way, I'm willing to help you with the Spanish translation if you want because you've added new features. I really like using ppink. Every day I use it and I'm testing it continually 😊

Thanks for your proposal. @NovaInc  in #17 has updated a spanish (south american ?) translation. If you want to have a look. do not hesitate to post in that thread.

PS :  do not hesitate to star the project

**Comment by NOVAinc** [comment]
I updated the translation that somebody else had made in the past, but it is the Latinamerican version. Maybe having a Spanish (from Spain) version could be good, too. I don't know where you are from, but if you're not from Spain, then you could take a look at the current translation and see if you can spot a mistake or suggest a change to improve it further! This tool is awesome and quality translations is what we can currently do to help it :)

**Comment by chrisj0192** [comment]
> You have a very easy solution to do such a background : add them in the clipart and you will be able to "call" it whenever you want.

To be honest, I hadn't used the clipArt feature. Three days ago it was the first time I used it and I didn't realize that I could use it with custom backgrounds and pictures. Now I understand much better about its function and its purpose. In fact, I can work much easier than I've been working so far with that feature and do some things that I have in mind much better. Thanks!

> My will is too keep ppInk usable from touchscreen, tablet pen, or mouse, and keyboard as a way to accelerate but not as a mandatory input. The secondary tool may be a solution to propose an interface usable with the cursor. will think also about that...

I understand. Thanks for considering the idea!

>Thanks for your proposal. @NOVAinc in #17 has updated a spanish (south american ?) translation. If you want to have a look. do not hesitate to post in that thread.

Ok, I'll have a look at that thread.

>PS : do not hesitate to star the project
I think I already starred Ppink in my work. They likes it. hehe

Thanks for your attention.

**Comment by chrisj0192** [comment]
> I updated the translation that somebody else had made in the past, but it is the Latinamerican version. Maybe having a Spanish (from Spain) version could be good, too. I don't know where you are from, but if you're not from Spain, then you could take a look at the current translation and see if you can spot a mistake or suggest a change to improve it further! This tool is awesome and quality translations is what we can currently do to help it :)

Hi @NOVAinc, nice to meet you. Don't worry, I did a translation a few months ago but I couldn't complete it because I have a bit of free time 😔 I remember that I translated about 88% of its total content and I left  few 'mistakes' I wanted to edit later but I think it's time to do it (If I still find them) . I will have a look at it and if it needs some improvements I'll try to do my best.

Thanks!

**Comment by pubpub-zz** [comment]
@chrisj0192 

Can you review modify file from NOVAinc and post it into #17. Thanks

I think this thread can be closed now

**Comment by chrisj0192** [comment]
> Can you review modify file from NOVAinc and post it into #17. Thanks

@pubpub-zz I'm reviewing it, down worry, just I have two proposal. I'll explain about it into #17.

Thanks

PD: You can close this thread if you want. I have nothing more to add in this issue, but I have some new findings that I recently found in the pre-release and will post them as another issue.
