### ISSUE TITLE
Colorwheel

### ISSUE THREAD

**Issue by pubpub-zz** [pubpub-zz/ppInk#96]
(from #96 
-Can i suggest if possible to implement this thing. It would be really useful if you change the current color wheel to similar with below attached images. I guess it is called 'HSV Square'. It is common in almost all painting and coloring applications. This is efficient and convenient way for any user to choose color shades. I am more concerned about the square part in the middle which gives ability to choose dark and light values of a single color. (Highly required function)

![Choose color option_1](https://user-images.githubusercontent.com/79096837/119230678-f520d900-bb3a-11eb-96fe-6f1e79254610.png)
![Choose color option_2](https://user-images.githubusercontent.com/79096837/119230682-f6520600-bb3a-11eb-901e-744ab0b5855f.png)

-I noticed that current color wheel has somewhat sluggish response to adjusting color slider. E.g. when i open color wheel and try to move vertical triangular slider, there is slight delay to it. It doesn't move until i move slider little far away. Means, it doesn't respond to slightly adjusted distance. (Again this might not be issue with program itself but it is noticeable, especially while using graphic tablet)

-Regarding selection of strokes: When i make a drawing It consist of couple of strokes. Lets say I want to move this drawing I can use hotkey 'P'. After that i make another drawing with couple of strokes, now if i want to move it, it moves everything on screen including the first drawing that i have made before. This behavior is obvious though. But it can be avoided if there is facility to select multiple strokes at a time. Right now only one stroke can be selected at a time which is not really helpful, because drawing is made of more than one stroke. So if possible 'drag and select' function is required which is similar to when we select multiple folders on desktop.

-And one last thing, Can we have Hotkey for exiting program completely. Or 'Right click functionality' Or 'Hotkey' for desktop icon of ppink that will open context menu options. From there user can click on: Options, About and Exit.

I am also attaching 'Config.ini' and 'Hotkeys.ini' file with it.

[Config and hotkey file.zip](https://github.com/pubpub-zz/ppInk/files/6526710/Config.and.hotkey.file.zip)

Thank you very much for bearing with me. :)

_Originally posted by @gitsamhub in https://github.com/pubpub-zz/ppInk/issues/92#issuecomment-846425211_

**Comment by pubpub-zz** [comment]
@gitsamhub,
I've coded a  solution to pick color for the HSL square. you can select hue from the hue cursor on left and then pickup color from the square 
Can you give me your feed back:
[ppInk64_HSL10a.zip](https://github.com/pubpub-zz/ppInk/files/6634654/ppInk64_HSL10a.zip)

**Comment by gitsamhub** [comment]
@pubpub-zz 
This is a valuable addition. 
Is it possible to add a visual indicator in HSL square to know which color shade is being selected? Also having ability to drag that point would be helpful.
Thanks.

**Comment by pubpub-zz** [comment]
@gitsamhub,
Added.
Can you complete your test and ensure you do not detect a bug
[ppInk64_HSL11a.zip](https://github.com/pubpub-zz/ppInk/files/6638800/ppInk64_HSL11a.zip)

**Comment by gitsamhub** [comment]
Thanks for adding visual indicator.

-Some strange white stuff follows when i move courser in color picker.
-In second half of the video it can be seen, when i try to reach the far top right corner in color picker, it automatically goes to left corner. 
https://user-images.githubusercontent.com/79096837/121702303-624add00-caef-11eb-84eb-7f0495498425.mp4

**Comment by pubpub-zz** [comment]
> -Some strange white stuff follows when i move courser in color picker.

For performance the cursor is a partially transparent image, placed over the SI colormap. The white square are due to image composition in windows; I Selected this design for performance and simplicity but it introduces  so redrawing artefacts when moving too quickly. 
for me this is not prohibitive

> -In second half of the video it can be seen, when i try to reach the far top right corner in color picker, it automatically goes to left corner.

This is due to HSI =>RGB => HSI conversions with rounding. Nothing to do for me

**Comment by gitsamhub** [comment]
Yes, I agree with you. These were minor issues and not really any functionality problem. I think this tool is working great. Good job.
Thank you.
